// packages/solidaria-components/src/Toolbar.tsx
/*
 * Copyright 2023 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */

// Ported to SolidJS for Proyecto Viviana; based on packages/react-aria-components/src/Toolbar.tsx

/**
 * Toolbar component for solidaria-components
 *
 * Pre-wired headless toolbar component that combines aria hooks.
 * Port of react-aria-components/src/Toolbar.tsx
 */

import { createContext, createMemo, useContext } from "solid-js";
import type { ParentProps } from "solid-js";
import type { JSX } from "@solidjs/web";
import {
  createToolbar,
  type AriaToolbarProps,
  type Orientation,
} from "@proyecto-viviana/solidaria";
import { type SlotProps, filterDOMProps } from "./utils";
import { splitProps } from "@proyecto-viviana/solidaria/utils";

export interface ToolbarRenderProps {
  /** The orientation of the toolbar. */
  orientation: Orientation;
}

export interface ToolbarProps extends AriaToolbarProps, ParentProps, SlotProps {
  /** The CSS className for the element. A function may be provided to receive render props. */
  class?: string | ((renderProps: ToolbarRenderProps) => string);
  /** The inline style for the element. A function may be provided to receive render props. */
  style?: JSX.CSSProperties | ((renderProps: ToolbarRenderProps) => JSX.CSSProperties);
  /** Additional data-* attributes. */
  [key: `data-${string}`]: string | undefined;
  /** Ref for the toolbar element. */
  ref?: ((el: HTMLDivElement) => void) | { current?: HTMLDivElement | null };
}

export interface ToolbarContextValue {
  slots?: {
    [name: string]: Record<string, unknown>;
  };
}

export const ToolbarContext = createContext<ToolbarContextValue | null>(null);

/**
 * A toolbar is a container for a set of interactive controls,
 * such as buttons, checkboxes, or links, with arrow key navigation.
 *
 * @example
 * ```tsx
 * <Toolbar aria-label="Text formatting">
 *   <Button>Bold</Button>
 *   <Button>Italic</Button>
 *   <Button>Underline</Button>
 * </Toolbar>
 *
 * // With render props
 * <Toolbar orientation="vertical">
 *   {({ orientation }) => (
 *     <div data-orientation={orientation}>
 *       <Button>Cut</Button>
 *       <Button>Copy</Button>
 *       <Button>Paste</Button>
 *     </div>
 *   )}
 * </Toolbar>
 * ```
 */
export function Toolbar(props: ToolbarProps): JSX.Element {
  const [local, ariaProps, domProps] = splitProps(
    props,
    ["class", "style", "slot", "children", "ref"],
    ["orientation", "aria-label", "aria-labelledby"],
  );

  const ctx = useContext(ToolbarContext);
  const slotProps = () => {
    if (ctx?.slots && local.slot) {
      return ctx.slots[typeof local.slot === "string" ? local.slot : "default"] || {};
    }
    return {};
  };

  const { toolbarProps, orientation } = createToolbar({
    get orientation() {
      return ariaProps.orientation;
    },
    get "aria-label"() {
      return (
        (ariaProps["aria-label"] as string | undefined) ??
        (slotProps()["aria-label"] as string | undefined)
      );
    },
    get "aria-labelledby"() {
      return ariaProps["aria-labelledby"] as string | undefined;
    },
  });

  const renderValues = createMemo<ToolbarRenderProps>(() => ({
    orientation: orientation(),
  }));

  const resolvedClass = createMemo(() => {
    const cls = local.class;
    if (typeof cls === "function") {
      return cls(renderValues());
    }
    return cls ?? "solidaria-Toolbar";
  });

  const resolvedStyle = createMemo(() => {
    const style = local.style;
    if (typeof style === "function") {
      return style(renderValues());
    }
    return style;
  });

  const resolvedChildren = createMemo(() => {
    const children = props.children;
    if (typeof children === "function") {
      return (children as (props: ToolbarRenderProps) => JSX.Element)(renderValues());
    }
    return children;
  });

  const filteredDOMProps = createMemo(() => filterDOMProps(domProps, { global: true }));

  return (
    <div
      {...filteredDOMProps()}
      {...toolbarProps}
      class={resolvedClass()}
      style={resolvedStyle()}
      slot={local.slot}
      data-orientation={orientation()}
      ref={(el) => {
        if (!local.ref) return;
        if (typeof local.ref === "function") {
          local.ref(el);
        } else {
          local.ref.current = el;
        }
      }}
    >
      {resolvedChildren()}
    </div>
  );
}

// packages/solid-spectrum/src/toolbar/index.tsx
/*
 * Copyright 2024 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */

// Ported to SolidJS for Proyecto Viviana; based on packages/@react-spectrum/s2/src/Toolbar.tsx

// Port of packages/@react-spectrum/s2/src/Toolbar.tsx.
import type { JSX } from "@solidjs/web";
import {
  Toolbar as HeadlessToolbar,
  type ToolbarProps as HeadlessToolbarProps,
  type ToolbarRenderProps,
} from "@proyecto-viviana/solidaria-components";

export type { ToolbarRenderProps };
export type ToolbarProps = HeadlessToolbarProps;

/**
 * A toolbar is a container for a set of interactive controls, such as buttons,
 * menus, or checkboxes, with arrow key navigation between them.
 *
 * React Spectrum S2 (1.5.1) ships Toolbar as a bare passthrough over the
 * react-aria-components `Toolbar` — no styling, no variant, no size — so this
 * mirrors it exactly. See `@react-spectrum/s2/src/Toolbar.tsx`.
 *
 * @example
 * ```tsx
 * <Toolbar aria-label="Text formatting">
 *   <Button>Bold</Button>
 *   <Button>Italic</Button>
 *   <Button>Underline</Button>
 * </Toolbar>
 * ```
 */
export function Toolbar(props: ToolbarProps): JSX.Element {
  return <HeadlessToolbar {...props} />;
}
