// apps/comparison/src/components/solid/ComparisonIsland.tsx
import h from "solid-js/h";
import { createEffect, createSignal, onMount } from "solid-js";
import {
  Button as HeadlessButton,
  Popover as HeadlessPopover,
  PopoverTrigger as HeadlessPopoverTrigger,
  Tab as HeadlessTab,
  TabList as HeadlessTabList,
  TabPanels as HeadlessTabPanels,
  TabPanel as HeadlessTabPanel,
  Tabs as HeadlessTabs,
} from "@proyecto-viviana/solidaria-components";
import { createButton, UNSAFE_PortalProvider } from "@proyecto-viviana/solidaria";
import type { ComparisonLayerId, ComparisonSlug } from "@comparison/data/comparison-manifest";
import {
  comparisonReferenceDataset,
  comparisonTabItems as tabItems,
  getComparisonReferenceKind,
  type ComparisonFramework,
  type ComparisonReferenceKind,
} from "@comparison/data/comparison-contract";
import { solidStyledFixtures } from "./fixtures/styled";

interface ComparisonIslandProps {
  componentSlug: ComparisonSlug;
  layer: ComparisonLayerId;
  onFixtureReady?: () => void;
}

type TabItem = (typeof tabItems)[number];

export default function ComparisonIsland(props: ComparisonIslandProps) {
  let overlayRoot: HTMLDivElement | undefined;
  const [styledMod, setStyledMod] = createSignal<{ default: () => unknown } | null | undefined>(
    props.layer === "styled" ? undefined : null,
  );

  onMount(() => {
    if (props.layer !== "styled") {
      return;
    }
    const loader = solidStyledFixtures[props.componentSlug];
    const pending = loader == null ? Promise.resolve(null) : loader();
    void pending.then(
      (mod) => setStyledMod(() => mod ?? null),
      (error: unknown) => {
        console.error(`Failed to load Solid styled fixture "${props.componentSlug}"`, error);
        setStyledMod(null);
      },
    );
  });

  createEffect(() => {
    if (styledMod() !== undefined) {
      props.onFixtureReady?.();
    }
  });

  return h(
    "div",
    { class: "comparison-island" },
    h(
      UNSAFE_PortalProvider,
      { getContainer: () => overlayRoot ?? null },
      renderLayer(props, styledMod),
    ),
    h("div", {
      class: "comparison-overlay-root",
      ref: (element: HTMLDivElement) => {
        overlayRoot = element;
      },
    }),
  )();
}

function renderLayer(
  props: ComparisonIslandProps,
  styledMod: () => { default: () => unknown } | null | undefined,
) {
  let rendered;
  if (props.layer === "styled") {
    rendered = () => renderStyled(styledMod);
  } else if (props.layer === "components") {
    rendered = renderComponents(props.componentSlug);
  } else if (props.layer === "headless") {
    rendered = renderHeadless(props.componentSlug);
  } else {
    rendered = emptyState("This layer is tracked in the manifest but not rendered yet.");
  }

  return comparisonReferenceFrame(
    {
      componentSlug: props.componentSlug,
      framework: "solid",
      layer: props.layer,
      reference: getComparisonReferenceKind("solid", props.layer, props.componentSlug),
    },
    rendered,
  );
}

function comparisonReferenceFrame(
  input: {
    componentSlug: ComparisonSlug;
    framework: ComparisonFramework;
    layer: ComparisonLayerId;
    reference: ComparisonReferenceKind;
  },
  children: ReturnType<typeof h> | (() => unknown),
) {
  return h(
    "div",
    {
      class: "comparison-reference-frame",
      ...comparisonReferenceDataset(input),
    },
    h("div", { class: "comparison-reference-canvas" }, children),
  );
}

function renderStyled(styledMod: () => { default: () => unknown } | null | undefined) {
  const mod = styledMod();
  if (mod === undefined) {
    return h("div", {
      class: "comparison-fixture-placeholder",
      "aria-hidden": "true",
    });
  }
  if (mod?.default != null) {
    return mod.default();
  }
  return emptyState(
    "Styled Solid Spectrum implementation is missing. Start from the React Spectrum S2 source and implement this component in solid-spectrum.",
  );
}

function renderComponents(componentSlug: ComparisonSlug) {
  switch (componentSlug) {
    case "button":
      return h(
        "div",
        { class: "comparison-stack" },
        h(HeadlessButton, { class: "comparison-rac-button" }, "Component Button"),
        h(
          HeadlessButton,
          {
            isDisabled: true,
            class: "comparison-rac-button comparison-rac-button--muted",
          },
          "Disabled by props",
        ),
      );
    case "popover":
      return h(
        "div",
        { class: "comparison-stack" },
        h(
          HeadlessPopoverTrigger,
          {},
          h(HeadlessButton, { class: "comparison-rac-button" }, "Open Popover"),
          h(
            HeadlessPopover,
            {
              class: "comparison-popover",
              "aria-label": "Quick audit note",
            },
            h(
              "div",
              { class: "comparison-popover-dialog" },
              h("div", { class: "comparison-popover-title" }, "Confirm Action"),
              h(
                "p",
                {},
                "Outside press and escape should dismiss this overlay without escaping its local comparison root.",
              ),
            ),
          ),
        ),
      );
    case "tabs":
      return h(
        HeadlessTabs,
        {
          class: "comparison-rac-tabs",
          "aria-label": "solidaria-components tabs",
          items: tabItems,
          getKey: (item: TabItem) => item.id,
          getTextValue: (item: TabItem) => item.label,
        },
        h(HeadlessTabList, { class: "comparison-rac-tab-list" }, (item: TabItem) =>
          h(HeadlessTab, { id: item.id, class: "comparison-rac-tab" }, item.label),
        ),
        h(
          HeadlessTabPanels,
          { class: "comparison-tab-panels" },
          tabItems.map((item) =>
            h(HeadlessTabPanel, { id: item.id, class: "comparison-tabs-panel" }, item.content),
          ),
        ),
      );
    default:
      return emptyState("No component-layer Solid demo is wired for this component yet.");
  }
}

function renderHeadless(componentSlug: ComparisonSlug) {
  switch (componentSlug) {
    case "button":
      return h(SolidHeadlessButtonDemo, {});
    default:
      return emptyState("No headless Solid demo is wired for this component yet.");
  }
}

function SolidHeadlessButtonDemo() {
  const [pressCount, setPressCount] = createSignal(0);
  const button = createButton({
    onPress: () => setPressCount((count) => count + 1),
    "aria-label": "Headless action",
  });

  return h(
    "div",
    { class: "comparison-headless-stack" },
    h(
      "button",
      {
        ...button.buttonProps,
        type: "button",
        class: "comparison-headless-button",
      },
      () => (button.isPressed() ? "Pressed" : `Pressed ${pressCount()} times`),
    ),
    h(
      "p",
      { class: "comparison-helper-copy" },
      "This uses the raw `createButton` primitive rather than a pre-wired component.",
    ),
  );
}

function emptyState(message: string) {
  return h("div", { class: "comparison-empty-state" }, message);
}

// apps/comparison/src/components/react/ComparisonIsland.js
import { jsx, jsxs } from "react/jsx-runtime";
// Keep this module JSX-free. Vite dev import-analysis currently sees this
// client-script dependency before Astro's React JSX transform runs.
import { Fragment, Suspense, use, useEffect, useMemo, useRef, useState } from "react";
import "@react-spectrum/s2/page.css";
import {
  Button as RACButton,
  Dialog as RACDialog,
  DialogTrigger as RACDialogTrigger,
  Heading as RACHeading,
  Popover as RACPopover,
  Tab as RACTab,
  TabList as RACTabList,
  TabPanel as RACTabPanel,
  Tabs as RACTabs,
} from "react-aria-components";
import { UNSAFE_PortalProvider, useButton } from "react-aria";
import {
  comparisonReferenceDataset,
  comparisonTabItems as tabItems,
  getComparisonReferenceKind,
} from "@comparison/data/comparison-contract";
import { reactStyledFixtures } from "./fixtures/styled.js";
function ComparisonIsland(props) {
  const overlayRootRef = useRef(null);
  const isStyled = props.layer === "styled";
  useEffect(() => {
    if (!isStyled) {
      props.onFixtureReady?.();
    }
  }, [isStyled, props.onFixtureReady]);
  return /* @__PURE__ */ jsxs("div", {
    className: "comparison-island",
    children: [
      /* @__PURE__ */ jsx(UNSAFE_PortalProvider, {
        getContainer: () => document.body,
        children: renderLayer(props),
      }),
      /* @__PURE__ */ jsx("div", { ref: overlayRootRef, className: "comparison-overlay-root" }),
    ],
  });
}
function renderLayer({ componentSlug, layer, onFixtureReady }) {
  let rendered;
  if (layer === "styled") {
    rendered = renderStyled(componentSlug, onFixtureReady);
  } else if (layer === "components") {
    rendered = renderComponents(componentSlug);
  } else if (layer === "headless") {
    rendered = renderHeadless(componentSlug);
  } else {
    rendered = /* @__PURE__ */ jsx("div", {
      className: "comparison-empty-state",
      children: "This layer is tracked in the manifest but not rendered yet.",
    });
  }

  return /* @__PURE__ */ jsx(ComparisonReferenceFrame, {
    componentSlug,
    layer,
    children: rendered,
  });
}
function ComparisonReferenceFrame({ componentSlug, layer, children }) {
  const reference = getComparisonReferenceKind("react", layer, componentSlug);
  return /* @__PURE__ */ jsx("div", {
    className: "comparison-reference-frame",
    ...comparisonReferenceDataset({
      componentSlug,
      framework: "react",
      layer,
      reference,
    }),
    children: /* @__PURE__ */ jsx("div", { className: "comparison-reference-canvas", children }),
  });
}
const styledModulePromises = new Map();

function styledFixturePlaceholder() {
  return /* @__PURE__ */ jsx("div", {
    className: "comparison-fixture-placeholder",
    "aria-hidden": true,
  });
}

function styledEmptyState() {
  return /* @__PURE__ */ jsx("div", {
    className: "comparison-empty-state",
    children: "No styled React Spectrum demo is wired for this component yet.",
  });
}

function loadStyledFixtureModule(componentSlug) {
  const loader = reactStyledFixtures[componentSlug];
  if (loader == null) {
    return Promise.resolve(null);
  }
  return loader().catch((error) => {
    console.error(`Failed to load React styled fixture "${componentSlug}"`, error);
    return null;
  });
}

function styledFixtureModulePromise(componentSlug) {
  let promise = styledModulePromises.get(componentSlug);
  if (promise == null) {
    promise = loadStyledFixtureModule(componentSlug);
    styledModulePromises.set(componentSlug, promise);
  }
  return promise;
}

function StyledFixtureReady({ onReady }) {
  useEffect(() => {
    onReady?.();
  }, [onReady]);
  return null;
}

function StyledFixture({ componentSlug, onReady }) {
  const mod = use(styledFixtureModulePromise(componentSlug));
  return /* @__PURE__ */ jsxs(Fragment, {
    children: [
      mod?.default != null ? mod.default() : styledEmptyState(),
      /* @__PURE__ */ jsx(StyledFixtureReady, { onReady }),
    ],
  });
}

function renderStyled(componentSlug, onReady) {
  return /* @__PURE__ */ jsx(Suspense, {
    fallback: styledFixturePlaceholder(),
    children: /* @__PURE__ */ jsx(StyledFixture, { componentSlug, onReady }),
  });
}
function renderComponents(componentSlug) {
  switch (componentSlug) {
    case "button":
      return /* @__PURE__ */ jsxs("div", {
        className: "comparison-stack",
        children: [
          /* @__PURE__ */ jsx(RACButton, {
            className: "comparison-rac-button",
            children: "Component Button",
          }),
          /* @__PURE__ */ jsx(RACButton, {
            isDisabled: true,
            className: "comparison-rac-button comparison-rac-button--muted",
            children: "Disabled by props",
          }),
        ],
      });
    case "popover":
      return /* @__PURE__ */ jsx("div", {
        className: "comparison-stack",
        children: /* @__PURE__ */ jsxs(RACDialogTrigger, {
          children: [
            /* @__PURE__ */ jsx(RACButton, {
              className: "comparison-rac-button",
              children: "Open Popover",
            }),
            /* @__PURE__ */ jsx(RACPopover, {
              className: "comparison-popover",
              children: /* @__PURE__ */ jsxs(RACDialog, {
                "aria-label": "Quick audit note",
                className: "comparison-popover-dialog",
                children: [
                  /* @__PURE__ */ jsx(RACHeading, {
                    slot: "title",
                    className: "comparison-popover-title",
                    children: "Confirm Action",
                  }),
                  /* @__PURE__ */ jsx("p", {
                    children:
                      "Outside press and escape should dismiss this overlay without escaping its local comparison root.",
                  }),
                ],
              }),
            }),
          ],
        }),
      });
    case "tabs":
      return /* @__PURE__ */ jsxs(RACTabs, {
        className: "comparison-rac-tabs",
        "aria-label": "React Aria tabs",
        children: [
          /* @__PURE__ */ jsx(RACTabList, {
            className: "comparison-rac-tab-list",
            children: tabItems.map((item) =>
              /* @__PURE__ */ jsx(
                RACTab,
                {
                  id: item.id,
                  className: "comparison-rac-tab",
                  children: item.label,
                },
                item.id,
              ),
            ),
          }),
          tabItems.map((item) =>
            /* @__PURE__ */ jsx(
              RACTabPanel,
              {
                id: item.id,
                className: "comparison-tabs-panel",
                children: item.content,
              },
              item.id,
            ),
          ),
        ],
      });
    default:
      return /* @__PURE__ */ jsx("div", {
        className: "comparison-empty-state",
        children: "No component-layer React demo is wired for this component yet.",
      });
  }
}
function renderHeadless(componentSlug) {
  switch (componentSlug) {
    case "button":
      return /* @__PURE__ */ jsx(ReactHeadlessButtonDemo, {});
    default:
      return /* @__PURE__ */ jsx("div", {
        className: "comparison-empty-state",
        children: "No headless React demo is wired for this component yet.",
      });
  }
}
function ReactHeadlessButtonDemo() {
  const ref = useRef(null);
  const [pressCount, setPressCount] = useState(0);
  const { buttonProps, isPressed } = useButton(
    {
      onPress: () => setPressCount((count) => count + 1),
      "aria-label": "Headless action",
    },
    ref,
  );
  const label = useMemo(() => {
    if (isPressed) {
      return "Pressed";
    }
    return `Pressed ${pressCount} times`;
  }, [isPressed, pressCount]);
  return /* @__PURE__ */ jsxs("div", {
    className: "comparison-headless-stack",
    children: [
      /* @__PURE__ */ jsx("button", {
        ...buttonProps,
        ref,
        type: "button",
        className: "comparison-headless-button",
        children: label,
      }),
      /* @__PURE__ */ jsx("p", {
        className: "comparison-helper-copy",
        children: "This uses the raw `useButton` hook rather than a pre-wired component.",
      }),
    ],
  });
}
export { ComparisonIsland as default };
