// apps/comparison/src/components/solid/fixtures/styled/accordion.tsx
import h from "@solidjs/h";
import { createMemo, createSignal, onSettled } from "solid-js";
import { hc } from "../../solid-h";
import {
  Accordion as SolidSpectrumAccordion,
  AccordionItem as SolidSpectrumAccordionItem,
  AccordionItemHeader as SolidSpectrumAccordionItemHeader,
  AccordionItemPanel as SolidSpectrumAccordionItemPanel,
  AccordionItemTitle as SolidSpectrumAccordionItemTitle,
} from "@proyecto-viviana/solid-spectrum/Accordion";
import { ActionButton as SolidSpectrumActionButton } from "@proyecto-viviana/solid-spectrum/ActionButton";
import { Provider as SolidSpectrumProvider } from "@proyecto-viviana/solid-spectrum/Provider";
import {
  accordionDemoLocaleFromWindow,
  accordionDemoPropsFromWindow,
  normalizeAccordionDemoProps,
  serializeAccordionKeys,
  serializeAccordionDemoProps,
  type AccordionDemoProps,
} from "@comparison/data/accordion-demo";
import { comparisonControlsEvent } from "@comparison/data/button-demo";
import {
  comparisonThemeChangeEvent,
  getComparisonResolvedThemeFromDocument,
  type ComparisonResolvedTheme,
} from "@comparison/data/theme";
import { providerShellStyle, SolidNewIcon } from "../styled-shared.tsx";

function SolidSpectrumAccordionDemo() {
  const [demoProps, setDemoProps] = createSignal<AccordionDemoProps>(
    accordionDemoPropsFromWindow(),
  );
  const locale = accordionDemoLocaleFromWindow();
  const [expandedKeys, setExpandedKeys] = createSignal<Set<string>>(new Set(["personal"]));
  const [expandedChangeCount, setExpandedChangeCount] = createSignal(0);
  const [lastExpandedChangeKeys, setLastExpandedChangeKeys] = createSignal("");
  const [colorScheme, setColorScheme] = createSignal<ComparisonResolvedTheme>(
    getComparisonResolvedThemeFromDocument(),
  );

  onSettled(() => {
    const handleControlsChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.component === "accordion") {
        setDemoProps(normalizeAccordionDemoProps(event.detail.props ?? {}));
      }
    };
    const handleThemeChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.resolvedTheme) {
        setColorScheme(event.detail.resolvedTheme as ComparisonResolvedTheme);
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    window.addEventListener(comparisonThemeChangeEvent, handleThemeChange);
    setColorScheme(getComparisonResolvedThemeFromDocument());
    return () => {
      window.removeEventListener(comparisonControlsEvent, handleControlsChange);
      window.removeEventListener(comparisonThemeChangeEvent, handleThemeChange);
    };
  });

  const controlledExpandedKeys = createMemo(() => {
    const keys = Array.from(expandedKeys());
    return new Set(demoProps().allowsMultipleExpanded ? keys : keys.slice(0, 1));
  });

  return hc(
    SolidSpectrumProvider,
    {
      get colorScheme() {
        return colorScheme();
      },
      locale,
      background: "base",
      style: providerShellStyle,
    },
    [
      hc(
        "div",
        {
          class: "comparison-accordion-row",
          "data-comparison-control-root": "accordion",
          get "data-comparison-control-props"() {
            return serializeAccordionDemoProps(demoProps());
          },
          get "data-comparison-expanded-keys"() {
            return serializeAccordionKeys(controlledExpandedKeys());
          },
          get "data-comparison-expanded-change-count"() {
            return String(expandedChangeCount());
          },
          get "data-comparison-expanded-change-keys"() {
            return lastExpandedChangeKeys();
          },
        },
        [
          hc(
            SolidSpectrumAccordion,
            {
              UNSAFE_style: { width: "220px" },
              get size() {
                return demoProps().size;
              },
              get density() {
                return demoProps().density;
              },
              get isQuiet() {
                return demoProps().isQuiet;
              },
              get isDisabled() {
                return demoProps().isDisabled;
              },
              get allowsMultipleExpanded() {
                return demoProps().allowsMultipleExpanded;
              },
              get expandedKeys() {
                return controlledExpandedKeys();
              },
              onExpandedChange(keys: Set<string>) {
                const nextKeys = new Set(Array.from(keys).map(String));
                setExpandedKeys(nextKeys);
                setExpandedChangeCount((count) => count + 1);
                setLastExpandedChangeKeys(serializeAccordionKeys(nextKeys));
              },
            },
            [
              hc(SolidSpectrumAccordionItem, { id: "personal" }, [
                hc(SolidSpectrumAccordionItemTitle, {}, ["Personal Information"]),
                hc(SolidSpectrumAccordionItemPanel, {}, [
                  hc("div", { class: "comparison-accordion-panel-copy" }, [
                    h("span", {}, "Name"),
                    h("span", {}, "Phone number"),
                    h("span", {}, "Email address"),
                  ]),
                ]),
              ]),
              hc(SolidSpectrumAccordionItem, { id: "billing" }, [
                hc(SolidSpectrumAccordionItemHeader, {}, [
                  hc(SolidSpectrumAccordionItemTitle, {}, ["Billing Address"]),
                  hc(SolidSpectrumActionButton, { "aria-label": "More billing actions" }, [
                    h(SolidNewIcon, { "aria-hidden": "true" }),
                  ]),
                ]),
                hc(SolidSpectrumAccordionItemPanel, {}, [
                  hc("div", { class: "comparison-accordion-panel-copy" }, [
                    h("span", {}, "Street address"),
                    h("span", {}, "City"),
                    h("span", {}, "Postal code"),
                  ]),
                ]),
              ]),
            ],
          ),
        ],
      ),
    ],
  );
}

export default () => h(SolidSpectrumAccordionDemo, {});

// apps/comparison/src/components/react/fixtures/styled/accordion.js
import { jsx, jsxs } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import {
  Accordion as SpectrumAccordion,
  AccordionItem as SpectrumAccordionItem,
  AccordionItemHeader as SpectrumAccordionItemHeader,
  AccordionItemPanel as SpectrumAccordionItemPanel,
  AccordionItemTitle as SpectrumAccordionItemTitle,
  ActionButton as SpectrumActionButton,
} from "@react-spectrum/s2";
import {
  accordionDemoLocaleFromWindow,
  accordionDemoPropsFromWindow,
  normalizeAccordionDemoProps,
  serializeAccordionKeys,
  serializeAccordionDemoProps,
} from "@comparison/data/accordion-demo";
import { comparisonControlsEvent } from "@comparison/data/button-demo";
import {
  useComparisonResolvedTheme,
  renderReactSpectrumReference,
  ReactButtonIcon,
} from "../styled-shared.js";

function ReactAccordionDemo() {
  const colorScheme = useComparisonResolvedTheme();
  const locale = accordionDemoLocaleFromWindow();
  const [demoProps, setDemoProps] = useState(accordionDemoPropsFromWindow);
  const [expandedKeys, setExpandedKeys] = useState(() => new Set(["personal"]));
  const [expandedChangeCount, setExpandedChangeCount] = useState(0);
  const [lastExpandedChangeKeys, setLastExpandedChangeKeys] = useState("");

  useEffect(() => {
    const handleControlsChange = (event) => {
      if (event instanceof CustomEvent && event.detail?.component === "accordion") {
        setDemoProps(normalizeAccordionDemoProps(event.detail.props ?? {}));
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    return () => window.removeEventListener(comparisonControlsEvent, handleControlsChange);
  }, []);

  const controlledExpandedKeys = demoProps.allowsMultipleExpanded
    ? expandedKeys
    : new Set(Array.from(expandedKeys).slice(0, 1));
  const handleExpandedChange = (keys) => {
    const nextKeys = new Set(Array.from(keys).map(String));
    setExpandedKeys(nextKeys);
    setExpandedChangeCount((count) => count + 1);
    setLastExpandedChangeKeys(serializeAccordionKeys(nextKeys));
  };

  return renderReactSpectrumReference(
    jsx("div", {
      className: "comparison-accordion-row",
      "data-comparison-control-root": "accordion",
      "data-comparison-control-props": serializeAccordionDemoProps(demoProps),
      "data-comparison-expanded-keys": serializeAccordionKeys(controlledExpandedKeys),
      "data-comparison-expanded-change-count": String(expandedChangeCount),
      "data-comparison-expanded-change-keys": lastExpandedChangeKeys,
      children: jsxs(SpectrumAccordion, {
        UNSAFE_style: { width: 220 },
        size: demoProps.size,
        density: demoProps.density,
        isQuiet: demoProps.isQuiet,
        isDisabled: demoProps.isDisabled,
        allowsMultipleExpanded: demoProps.allowsMultipleExpanded,
        expandedKeys: controlledExpandedKeys,
        onExpandedChange: handleExpandedChange,
        children: [
          jsxs(SpectrumAccordionItem, {
            id: "personal",
            children: [
              jsx(SpectrumAccordionItemTitle, {
                children: "Personal Information",
              }),
              jsx(SpectrumAccordionItemPanel, {
                children: jsxs("div", {
                  className: "comparison-accordion-panel-copy",
                  children: [
                    jsx("span", { children: "Name" }),
                    jsx("span", { children: "Phone number" }),
                    jsx("span", { children: "Email address" }),
                  ],
                }),
              }),
            ],
          }),
          jsxs(SpectrumAccordionItem, {
            id: "billing",
            children: [
              jsxs(SpectrumAccordionItemHeader, {
                children: [
                  jsx(SpectrumAccordionItemTitle, {
                    children: "Billing Address",
                  }),
                  jsx(SpectrumActionButton, {
                    "aria-label": "More billing actions",
                    children: jsx(ReactButtonIcon, { "aria-hidden": "true" }),
                  }),
                ],
              }),
              jsx(SpectrumAccordionItemPanel, {
                children: jsxs("div", {
                  className: "comparison-accordion-panel-copy",
                  children: [
                    jsx("span", { children: "Street address" }),
                    jsx("span", { children: "City" }),
                    jsx("span", { children: "Postal code" }),
                  ],
                }),
              }),
            ],
          }),
        ],
      }),
    }),
    colorScheme,
    locale,
  );
}

export default () => jsx(ReactAccordionDemo, {});
