// apps/comparison/src/components/solid/fixtures/styled/badge.tsx
import h from "@solidjs/h";
import { createSignal, onSettled } from "solid-js";
import { hc } from "../../solid-h";
import { Badge as SolidSpectrumBadge } from "@proyecto-viviana/solid-spectrum/Badge";
import { Provider as SolidSpectrumProvider } from "@proyecto-viviana/solid-spectrum/Provider";
import { Text as SolidSpectrumText } from "@proyecto-viviana/solid-spectrum/Text";
import {
  badgeDemoPropsFromWindow,
  normalizeBadgeDemoProps,
  serializeBadgeDemoProps,
  type BadgeDemoProps,
} from "@comparison/data/badge-demo";
import { comparisonControlsEvent } from "@comparison/data/button-demo";
import {
  comparisonThemeChangeEvent,
  getComparisonResolvedThemeFromDocument,
  type ComparisonResolvedTheme,
} from "@comparison/data/theme";
import { providerShellStyle, SolidNewIcon } from "../styled-shared.tsx";

function solidBadgeChildren(props: BadgeDemoProps) {
  if (props.iconPlacement === "start") {
    return [
      () => [h(SolidNewIcon, { "aria-hidden": "true" }), h(SolidSpectrumText, {}, props.children)],
    ];
  }

  return [props.children];
}

function SolidSpectrumBadgeDemo() {
  const [demoProps, setDemoProps] = createSignal<BadgeDemoProps>(badgeDemoPropsFromWindow());
  const [colorScheme, setColorScheme] = createSignal<ComparisonResolvedTheme>(
    getComparisonResolvedThemeFromDocument(),
  );

  onSettled(() => {
    const handleControlsChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.component === "badge") {
        setDemoProps(normalizeBadgeDemoProps(event.detail.props ?? {}));
      }
    };
    const handleThemeChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.resolvedTheme) {
        setColorScheme(event.detail.resolvedTheme as ComparisonResolvedTheme);
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    window.addEventListener(comparisonThemeChangeEvent, handleThemeChange);
    setColorScheme(getComparisonResolvedThemeFromDocument());
    return () => {
      window.removeEventListener(comparisonControlsEvent, handleControlsChange);
      window.removeEventListener(comparisonThemeChangeEvent, handleThemeChange);
    };
  });

  const renderedBadge = hc(SolidSpectrumBadge, {
    "data-comparison-control-root": "badge",
    get "data-comparison-control-props"() {
      return serializeBadgeDemoProps(demoProps());
    },
    id: "badge-route-root",
    "aria-label": "Badge route label",
    "aria-labelledby": "badge-route-labelledby",
    "aria-describedby": "badge-route-description",
    "aria-details": "badge-route-details",
    hidden: true,
    get variant() {
      return demoProps().variant;
    },
    get fillStyle() {
      return demoProps().fillStyle;
    },
    get size() {
      return demoProps().size;
    },
    get overflowMode() {
      return demoProps().overflowMode;
    },
    get children() {
      return solidBadgeChildren(demoProps());
    },
  });

  return hc(
    SolidSpectrumProvider,
    {
      get colorScheme() {
        return colorScheme();
      },
      background: "base",
      style: providerShellStyle,
    },
    [
      hc(
        "div",
        {
          class: "comparison-badge-row",
          get "data-comparison-color-scheme"() {
            return colorScheme();
          },
        },
        [renderedBadge],
      ),
    ],
  );
}

export default () => h(SolidSpectrumBadgeDemo, {});

// apps/comparison/src/components/react/fixtures/styled/badge.js
import { jsx, jsxs } from "react/jsx-runtime";
import { Fragment, useEffect, useState } from "react";
import { Badge as SpectrumBadge, Text as SpectrumText } from "@react-spectrum/s2";
import {
  badgeDemoPropsFromWindow,
  normalizeBadgeDemoProps,
  serializeBadgeDemoProps,
} from "@comparison/data/badge-demo";
import { comparisonControlsEvent } from "@comparison/data/button-demo";
import {
  useComparisonResolvedTheme,
  renderReactSpectrumReference,
  ReactButtonIcon,
} from "../styled-shared.js";

function renderBadgeChildren(demoProps) {
  if (demoProps.iconPlacement === "start") {
    return jsxs(Fragment, {
      children: [
        jsx(ReactButtonIcon, { "aria-hidden": "true" }),
        jsx(SpectrumText, { children: demoProps.children }),
      ],
    });
  }

  return demoProps.children;
}

function ReactBadgeDemo() {
  const colorScheme = useComparisonResolvedTheme();
  const [demoProps, setDemoProps] = useState(badgeDemoPropsFromWindow);
  useEffect(() => {
    const handleControlsChange = (event) => {
      if (event instanceof CustomEvent && event.detail?.component === "badge") {
        setDemoProps(normalizeBadgeDemoProps(event.detail.props ?? {}));
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    return () => window.removeEventListener(comparisonControlsEvent, handleControlsChange);
  }, []);

  return renderReactSpectrumReference(
    jsx("div", {
      className: "comparison-badge-row",
      children: jsx(SpectrumBadge, {
        "data-comparison-control-root": "badge",
        "data-comparison-control-props": serializeBadgeDemoProps(demoProps),
        id: "badge-route-root",
        "aria-label": "Badge route label",
        "aria-labelledby": "badge-route-labelledby",
        "aria-describedby": "badge-route-description",
        "aria-details": "badge-route-details",
        hidden: true,
        variant: demoProps.variant,
        fillStyle: demoProps.fillStyle,
        size: demoProps.size,
        overflowMode: demoProps.overflowMode,
        children: renderBadgeChildren(demoProps),
      }),
    }),
    colorScheme,
  );
}

export default () => jsx(ReactBadgeDemo, {});
