// apps/comparison/src/components/solid/fixtures/styled/calendar.tsx
import h from "solid-js/h";
import { createMemo, createSignal, onCleanup, onMount } from "solid-js";
import { hc } from "../../solid-h";
import {
  Calendar as SolidSpectrumCalendar,
  Provider as SolidSpectrumProvider,
} from "@proyecto-viviana/solid-spectrum";
import {
  calendarCreateCalendarForDemo,
  calendarDateFromString,
  calendarDemoPropsFromWindow,
  calendarMaxValue,
  calendarMinValue,
  calendarVisibleMonthsFromString,
  comparisonControlsEvent as calendarControlsEvent,
  isCalendarDateUnavailable,
  normalizeCalendarDemoProps,
  serializeCalendarDemoProps,
  type CalendarDemoProps,
} from "@comparison/data/calendar-demo";
import {
  comparisonThemeChangeEvent,
  getComparisonResolvedThemeFromDocument,
  type ComparisonResolvedTheme,
} from "@comparison/data/theme";
import { providerShellStyle } from "../styled-shared.tsx";

function SolidSpectrumCalendarDemo() {
  const [demoProps, setDemoProps] = createSignal<CalendarDemoProps>(calendarDemoPropsFromWindow());
  const [value, setValue] = createSignal(
    calendarDateFromString(calendarDemoPropsFromWindow().value),
  );
  const [focusedValue, setFocusedValue] = createSignal(
    calendarDateFromString(
      calendarDemoPropsFromWindow().focusedValue || calendarDemoPropsFromWindow().value,
    ),
  );
  const [colorScheme, setColorScheme] = createSignal<ComparisonResolvedTheme>(
    getComparisonResolvedThemeFromDocument(),
  );

  onMount(() => {
    const handleControlsChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.component === "calendar") {
        const nextProps = normalizeCalendarDemoProps({
          ...demoProps(),
          ...(event.detail.props ?? {}),
        });
        setDemoProps(nextProps);
        setValue(() => calendarDateFromString(nextProps.value));
        setFocusedValue(() => calendarDateFromString(nextProps.focusedValue || nextProps.value));
      }
    };
    const handleThemeChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.resolvedTheme) {
        setColorScheme(event.detail.resolvedTheme as ComparisonResolvedTheme);
      }
    };
    window.addEventListener(calendarControlsEvent, handleControlsChange);
    window.addEventListener(comparisonThemeChangeEvent, handleThemeChange);
    setColorScheme(getComparisonResolvedThemeFromDocument());
    onCleanup(() => {
      window.removeEventListener(calendarControlsEvent, handleControlsChange);
      window.removeEventListener(comparisonThemeChangeEvent, handleThemeChange);
    });
  });

  const serializedProps = createMemo(() => serializeCalendarDemoProps(demoProps()));

  return hc(
    SolidSpectrumProvider,
    {
      get colorScheme() {
        return colorScheme();
      },
      get locale() {
        return demoProps().locale || undefined;
      },
      background: "base",
      style: providerShellStyle,
    },
    [
      hc(
        "div",
        {
          get "data-comparison-color-scheme"() {
            return colorScheme();
          },
          get "data-comparison-value"() {
            return value() ? String(value()) : "";
          },
          get "data-comparison-focused-value"() {
            return focusedValue() ? String(focusedValue()) : "";
          },
          "data-comparison-control-root": "calendar",
          get "data-comparison-control-props"() {
            return serializedProps();
          },
        },
        [
          hc(SolidSpectrumCalendar, {
            class: "comparison-calendar-root",
            "aria-label": "Event date",
            get value() {
              return value() ?? undefined;
            },
            onChange: (nextValue: NonNullable<ReturnType<typeof calendarDateFromString>>) => {
              setValue(() => nextValue);
            },
            get minValue() {
              return demoProps().constrainRange ? calendarMinValue : undefined;
            },
            get maxValue() {
              return demoProps().constrainRange ? calendarMaxValue : undefined;
            },
            get isDateUnavailable() {
              return demoProps().unavailableDates ? isCalendarDateUnavailable : undefined;
            },
            get isDisabled() {
              return demoProps().isDisabled;
            },
            get isReadOnly() {
              return demoProps().isReadOnly;
            },
            get isInvalid() {
              return demoProps().isInvalid;
            },
            get errorMessage() {
              return demoProps().errorMessage;
            },
            get firstDayOfWeek() {
              return demoProps().firstDayOfWeek || undefined;
            },
            get visibleMonths() {
              return calendarVisibleMonthsFromString(demoProps().visibleMonths);
            },
            get pageBehavior() {
              return demoProps().pageBehavior || undefined;
            },
            get selectionAlignment() {
              return demoProps().selectionAlignment || undefined;
            },
            get createCalendar() {
              return calendarCreateCalendarForDemo(demoProps().calendarSystem);
            },
            get UNSAFE_style() {
              const visibleMonths = calendarVisibleMonthsFromString(demoProps().visibleMonths);
              const resolvedVisibleMonths = visibleMonths ?? 1;
              return {
                "--cell-responsive-size": "32px",
                width: `${resolvedVisibleMonths * 224 + (resolvedVisibleMonths - 1) * 24}px`,
                maxWidth: "100%",
              };
            },
            get focusedValue() {
              return demoProps().focusedValue ? (focusedValue() ?? undefined) : undefined;
            },
            onFocusChange: (
              nextFocusedValue: NonNullable<ReturnType<typeof calendarDateFromString>>,
            ) => {
              setFocusedValue(() => nextFocusedValue);
            },
          }),
        ],
      ),
    ],
  );
}

export default () => h(SolidSpectrumCalendarDemo, {});

// apps/comparison/src/components/react/fixtures/styled/calendar.js
import { jsx } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import { Calendar as SpectrumCalendar } from "@react-spectrum/s2";
import {
  calendarCreateCalendarForDemo,
  calendarDateFromString,
  calendarDemoPropsFromWindow,
  calendarMaxValue,
  calendarMinValue,
  calendarVisibleMonthsFromString,
  comparisonControlsEvent as calendarControlsEvent,
  isCalendarDateUnavailable,
  normalizeCalendarDemoProps,
  serializeCalendarDemoProps,
} from "@comparison/data/calendar-demo";
import { useComparisonResolvedTheme, renderReactSpectrumReference } from "../styled-shared.js";

function ReactCalendarDemo() {
  const [demoProps, setDemoProps] = useState(calendarDemoPropsFromWindow);
  const [value, setValue] = useState(() =>
    calendarDateFromString(calendarDemoPropsFromWindow().value),
  );
  const [focusedValue, setFocusedValue] = useState(() =>
    calendarDateFromString(
      calendarDemoPropsFromWindow().focusedValue || calendarDemoPropsFromWindow().value,
    ),
  );
  const colorScheme = useComparisonResolvedTheme();

  useEffect(() => {
    const handleControlsChange = (event) => {
      if (event instanceof CustomEvent && event.detail?.component === "calendar") {
        setDemoProps((currentProps) => {
          const nextProps = normalizeCalendarDemoProps({
            ...currentProps,
            ...(event.detail.props ?? {}),
          });
          setValue(calendarDateFromString(nextProps.value));
          setFocusedValue(calendarDateFromString(nextProps.focusedValue || nextProps.value));
          return nextProps;
        });
      }
    };
    window.addEventListener(calendarControlsEvent, handleControlsChange);
    return () => window.removeEventListener(calendarControlsEvent, handleControlsChange);
  }, []);

  const selectedValue = value;
  const visibleMonths = calendarVisibleMonthsFromString(demoProps.visibleMonths);
  const resolvedVisibleMonths = visibleMonths ?? 1;
  const calendarReferenceWidth = `${resolvedVisibleMonths * 224 + (resolvedVisibleMonths - 1) * 24}px`;
  const calendarProps = {
    "aria-label": "Event date",
    onChange: (nextValue) => setValue(nextValue),
    minValue: demoProps.constrainRange ? calendarMinValue : undefined,
    maxValue: demoProps.constrainRange ? calendarMaxValue : undefined,
    isDateUnavailable: demoProps.unavailableDates ? isCalendarDateUnavailable : undefined,
    isDisabled: demoProps.isDisabled,
    isReadOnly: demoProps.isReadOnly,
    isInvalid: demoProps.isInvalid,
    errorMessage: demoProps.errorMessage,
    firstDayOfWeek: demoProps.firstDayOfWeek || undefined,
    visibleMonths,
    pageBehavior: demoProps.pageBehavior || undefined,
    selectionAlignment: demoProps.selectionAlignment || undefined,
    createCalendar: calendarCreateCalendarForDemo(demoProps.calendarSystem),
    focusedValue: demoProps.focusedValue ? (focusedValue ?? undefined) : undefined,
    onFocusChange: (nextFocusedValue) => setFocusedValue(nextFocusedValue),
    UNSAFE_className: "comparison-calendar-root",
    UNSAFE_style: {
      "--cell-responsive-size": "32px",
      width: calendarReferenceWidth,
      maxWidth: "100%",
    },
  };

  if (selectedValue) {
    calendarProps.value = selectedValue;
  }

  return renderReactSpectrumReference(
    jsx("div", {
      "data-comparison-control-root": "calendar",
      "data-comparison-control-props": serializeCalendarDemoProps(demoProps),
      "data-comparison-value": selectedValue ? String(selectedValue) : "",
      "data-comparison-focused-value": focusedValue ? String(focusedValue) : "",
      "data-comparison-color-scheme": colorScheme,
      children: jsx(SpectrumCalendar, calendarProps),
    }),
    colorScheme,
    demoProps.locale || undefined,
  );
}

export default () => jsx(ReactCalendarDemo, {});
