// apps/comparison/src/components/solid/fixtures/styled/checkboxgroup.tsx
import h from "@solidjs/h";
import { createMemo, createSignal, onSettled } from "solid-js";
import { createComponent } from "@solidjs/web";
import { hc, Keyed } from "../../solid-h";
import { Checkbox as SolidSpectrumCheckbox } from "@proyecto-viviana/solid-spectrum/Checkbox";
import { CheckboxGroup as SolidSpectrumCheckboxGroup } from "@proyecto-viviana/solid-spectrum/CheckboxGroup";
import { ContextualHelp as SolidSpectrumContextualHelp } from "@proyecto-viviana/solid-spectrum/ContextualHelp";
import { Heading as SolidSpectrumHeading } from "@proyecto-viviana/solid-spectrum/Heading";
import { Provider as SolidSpectrumProvider } from "@proyecto-viviana/solid-spectrum/Provider";
import { Text as SolidSpectrumText } from "@proyecto-viviana/solid-spectrum/Text";
import {
  checkboxGroupDemoPropsFromWindow,
  initialCheckboxGroupDemoValue,
  normalizeCheckboxGroupDemoProps,
  serializeCheckboxGroupDemoProps,
  type CheckboxGroupDemoProps,
  comparisonControlsEvent,
} from "@comparison/data/checkboxgroup-demo";
import {
  comparisonThemeChangeEvent,
  getComparisonResolvedThemeFromDocument,
  type ComparisonResolvedTheme,
} from "@comparison/data/theme";
import { providerShellStyle } from "../styled-shared.tsx";

const checkboxGroupItems = [
  { value: "email", label: "Email" },
  { value: "sms", label: "SMS" },
  { value: "push", label: "Push" },
];

function SolidSpectrumCheckboxGroupDemo() {
  const [demoProps, setDemoProps] = createSignal<CheckboxGroupDemoProps>(
    checkboxGroupDemoPropsFromWindow(),
  );
  const [value, setValue] = createSignal<string[]>(initialCheckboxGroupDemoValue(demoProps()));
  const [colorScheme, setColorScheme] = createSignal<ComparisonResolvedTheme>(
    getComparisonResolvedThemeFromDocument(),
  );

  onSettled(() => {
    const handleControlsChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.component === "checkboxgroup") {
        const nextProps = normalizeCheckboxGroupDemoProps(event.detail.props ?? {});
        setDemoProps(nextProps);
        setValue(initialCheckboxGroupDemoValue(nextProps));
      }
    };
    const handleThemeChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.resolvedTheme) {
        setColorScheme(event.detail.resolvedTheme as ComparisonResolvedTheme);
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    window.addEventListener(comparisonThemeChangeEvent, handleThemeChange);
    setColorScheme(getComparisonResolvedThemeFromDocument());
    return () => {
      window.removeEventListener(comparisonControlsEvent, handleControlsChange);
      window.removeEventListener(comparisonThemeChangeEvent, handleThemeChange);
    };
  });

  const selectedValues = createMemo(() => value().join(","));
  const serializedProps = createMemo(() => serializeCheckboxGroupDemoProps(demoProps()));
  const renderKey = createMemo(() =>
    [
      demoProps().valueSource,
      demoProps().valueSource === "defaultValue" ? demoProps().defaultValue : "controlled",
      demoProps().name,
      demoProps().form,
      demoProps().validationBehavior,
    ].join("|"),
  );

  return hc(
    SolidSpectrumProvider,
    {
      get colorScheme() {
        return colorScheme();
      },
      background: "base",
      style: providerShellStyle,
    },
    [
      () =>
        hc(
          "div",
          {
            get "data-comparison-color-scheme"() {
              return colorScheme();
            },
            get "data-comparison-selected-values"() {
              return selectedValues();
            },
            "data-comparison-control-root": "checkboxgroup",
            get "data-comparison-control-props"() {
              return serializedProps();
            },
          },
          [
            createComponent(Keyed, {
              get when() {
                return renderKey();
              },
              children: (_key: string) =>
                hc(
                  SolidSpectrumCheckboxGroup,
                  {
                    get label() {
                      return demoProps().label;
                    },
                    get value() {
                      return demoProps().valueSource === "value" ? value() : undefined;
                    },
                    get defaultValue() {
                      return demoProps().valueSource === "defaultValue"
                        ? initialCheckboxGroupDemoValue(demoProps())
                        : undefined;
                    },
                    get size() {
                      return demoProps().size;
                    },
                    get orientation() {
                      return demoProps().orientation;
                    },
                    get labelPosition() {
                      return demoProps().labelPosition;
                    },
                    get labelAlign() {
                      return demoProps().labelAlign;
                    },
                    get necessityIndicator() {
                      return demoProps().necessityIndicator;
                    },
                    get name() {
                      return demoProps().name || undefined;
                    },
                    get form() {
                      return demoProps().form || undefined;
                    },
                    get validationBehavior() {
                      return demoProps().validationBehavior || undefined;
                    },
                    get description() {
                      return demoProps().description;
                    },
                    get errorMessage() {
                      return demoProps().errorMessage;
                    },
                    get contextualHelp() {
                      return demoProps().withContextualHelp
                        ? hc(SolidSpectrumContextualHelp, {}, [
                            hc(SolidSpectrumHeading, { slot: "title" }, ["Notification help"]),
                            hc(SolidSpectrumText, {}, [
                              "Choose every channel that should alert you.",
                            ]),
                          ])
                        : undefined;
                    },
                    get isEmphasized() {
                      return demoProps().isEmphasized;
                    },
                    get isDisabled() {
                      return demoProps().isDisabled;
                    },
                    get isReadOnly() {
                      return demoProps().isReadOnly;
                    },
                    get isRequired() {
                      return demoProps().isRequired;
                    },
                    get isInvalid() {
                      return demoProps().isInvalid;
                    },
                    onChange: (nextValue: string[]) => {
                      const nextSelectedValues = nextValue.map(String);
                      setValue(nextSelectedValues);
                      setDemoProps((current: CheckboxGroupDemoProps) =>
                        current.valueSource === "value"
                          ? { ...current, selectedValues: nextSelectedValues.join(",") }
                          : current,
                      );
                    },
                  },
                  checkboxGroupItems.map((item) =>
                    hc(SolidSpectrumCheckbox, { value: item.value }, [item.label]),
                  ),
                )(),
            }),
          ],
        ),
    ],
  );
}

export default () => h(SolidSpectrumCheckboxGroupDemo, {});

// apps/comparison/src/components/react/fixtures/styled/checkboxgroup.js
import { jsx, jsxs } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import {
  Checkbox as SpectrumCheckbox,
  CheckboxGroup as SpectrumCheckboxGroup,
  ContextualHelp as SpectrumContextualHelp,
  Content as SpectrumContent,
  Heading as SpectrumHeading,
} from "@react-spectrum/s2";
import {
  checkboxGroupDemoPropsFromWindow,
  initialCheckboxGroupDemoValue,
  normalizeCheckboxGroupDemoProps,
  serializeCheckboxGroupDemoProps,
  comparisonControlsEvent,
} from "@comparison/data/checkboxgroup-demo";
import { useComparisonResolvedTheme, renderReactSpectrumReference } from "../styled-shared.js";

const checkboxGroupItems = [
  { value: "email", label: "Email" },
  { value: "sms", label: "SMS" },
  { value: "push", label: "Push" },
];

function ReactCheckboxGroupDemo() {
  const [demoProps, setDemoProps] = useState(checkboxGroupDemoPropsFromWindow);
  const [value, setValue] = useState(() => initialCheckboxGroupDemoValue(demoProps));
  const colorScheme = useComparisonResolvedTheme();
  useEffect(() => {
    const handleControlsChange = (event) => {
      if (event instanceof CustomEvent && event.detail?.component === "checkboxgroup") {
        const nextProps = normalizeCheckboxGroupDemoProps(event.detail.props ?? {});
        setDemoProps(nextProps);
        setValue(initialCheckboxGroupDemoValue(nextProps));
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    return () => window.removeEventListener(comparisonControlsEvent, handleControlsChange);
  }, []);

  const selectedValues = value.join(",");
  const valueProps =
    demoProps.valueSource === "defaultValue"
      ? { defaultValue: initialCheckboxGroupDemoValue(demoProps) }
      : { value };
  const renderKey = [
    demoProps.valueSource,
    demoProps.valueSource === "defaultValue" ? demoProps.defaultValue : "controlled",
    demoProps.name,
    demoProps.form,
    demoProps.validationBehavior,
  ].join("|");

  return renderReactSpectrumReference(
    jsx("div", {
      "data-comparison-selected-values": selectedValues,
      "data-comparison-control-root": "checkboxgroup",
      "data-comparison-control-props": serializeCheckboxGroupDemoProps(demoProps),
      children: jsx(
        SpectrumCheckboxGroup,
        {
          label: demoProps.label,
          ...valueProps,
          size: demoProps.size,
          orientation: demoProps.orientation,
          labelPosition: demoProps.labelPosition,
          labelAlign: demoProps.labelAlign,
          necessityIndicator: demoProps.necessityIndicator,
          name: demoProps.name || undefined,
          form: demoProps.form || undefined,
          validationBehavior: demoProps.validationBehavior || undefined,
          description: demoProps.description,
          errorMessage: demoProps.errorMessage,
          contextualHelp: demoProps.withContextualHelp
            ? jsxs(SpectrumContextualHelp, {
                children: [
                  jsx(SpectrumHeading, { children: "Notification help" }),
                  jsx(SpectrumContent, { children: "Choose every channel that should alert you." }),
                ],
              })
            : undefined,
          isEmphasized: demoProps.isEmphasized,
          isDisabled: demoProps.isDisabled,
          isReadOnly: demoProps.isReadOnly,
          isRequired: demoProps.isRequired,
          isInvalid: demoProps.isInvalid,
          onChange: (nextValue) => {
            const nextSelectedValues = nextValue.map(String);
            setValue(nextSelectedValues);
            setDemoProps((current) =>
              current.valueSource === "value"
                ? { ...current, selectedValues: nextSelectedValues.join(",") }
                : current,
            );
          },
          children: checkboxGroupItems.map((item) =>
            jsx(SpectrumCheckbox, { value: item.value, children: item.label }, item.value),
          ),
        },
        renderKey,
      ),
    }),
    colorScheme,
  );
}

export default () => jsx(ReactCheckboxGroupDemo, {});
