// apps/comparison/src/components/solid/fixtures/styled/colorwheel.tsx
import h from "solid-js/h";
import { createMemo, createSignal, onCleanup, onMount } from "solid-js";
import { hc } from "../../solid-h";
import {
  ColorWheel as SolidSpectrumColorWheel,
  Provider as SolidSpectrumProvider,
  parseColor as parseSolidSpectrumColor,
} from "@proyecto-viviana/solid-spectrum";
import { buttonDemoLocaleFromWindow } from "@comparison/data/button-demo";
import {
  colorWheelDemoDefaults,
  colorWheelDemoPropsFromWindow,
  colorWheelDemoSizeNumber,
  initialColorWheelDemoValue,
  normalizeColorWheelDemoProps,
  serializeColorWheelDemoProps,
  type ColorWheelDemoProps,
  comparisonControlsEvent,
} from "@comparison/data/colorwheel-demo";
import {
  comparisonThemeChangeEvent,
  getComparisonResolvedThemeFromDocument,
  type ComparisonResolvedTheme,
} from "@comparison/data/theme";
import { providerShellStyle } from "../styled-shared.tsx";

function parseSolidColorWheelValue(value: string, fallback = colorWheelDemoDefaults.value) {
  try {
    return parseSolidSpectrumColor(value || fallback);
  } catch {
    return parseSolidSpectrumColor(fallback);
  }
}

function solidColorWheelToCssString(color: ReturnType<typeof parseSolidColorWheelValue>) {
  return color.toString("css");
}

function SolidSpectrumColorWheelDemo() {
  const [demoProps, setDemoProps] = createSignal<ColorWheelDemoProps>(
    colorWheelDemoPropsFromWindow(),
  );
  const [value, setValue] = createSignal(
    parseSolidColorWheelValue(initialColorWheelDemoValue(demoProps())),
  );
  const [finalValue, setFinalValue] = createSignal(
    parseSolidColorWheelValue(initialColorWheelDemoValue(demoProps())),
  );
  const [colorScheme, setColorScheme] = createSignal<ComparisonResolvedTheme>(
    getComparisonResolvedThemeFromDocument(),
  );
  const locale = buttonDemoLocaleFromWindow();

  onMount(() => {
    const handleControlsChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.component === "colorwheel") {
        const nextProps = normalizeColorWheelDemoProps(event.detail.props ?? {});
        const nextValue = parseSolidColorWheelValue(initialColorWheelDemoValue(nextProps));
        setDemoProps(nextProps);
        setValue(nextValue);
        setFinalValue(nextValue);
      }
    };
    const handleThemeChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.resolvedTheme) {
        setColorScheme(event.detail.resolvedTheme as ComparisonResolvedTheme);
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    window.addEventListener(comparisonThemeChangeEvent, handleThemeChange);
    setColorScheme(getComparisonResolvedThemeFromDocument());
    onCleanup(() => {
      window.removeEventListener(comparisonControlsEvent, handleControlsChange);
      window.removeEventListener(comparisonThemeChangeEvent, handleThemeChange);
    });
  });

  const serializedProps = createMemo(() => serializeColorWheelDemoProps(demoProps()));

  return hc(
    SolidSpectrumProvider,
    {
      get colorScheme() {
        return colorScheme();
      },
      locale,
      background: "base",
      style: providerShellStyle,
    },
    [
      hc(
        "div",
        {
          "data-comparison-control-root": "colorwheel",
          get "data-comparison-color-scheme"() {
            return colorScheme();
          },
          get "data-comparison-control-props"() {
            return serializedProps();
          },
          get "data-comparison-value"() {
            return solidColorWheelToCssString(value());
          },
          get "data-comparison-final-value"() {
            return solidColorWheelToCssString(finalValue());
          },
        },
        [
          hc(SolidSpectrumColorWheel, {
            get "aria-label"() {
              return demoProps().ariaLabel || undefined;
            },
            get "aria-labelledby"() {
              return demoProps().ariaLabelledBy || undefined;
            },
            get "aria-describedby"() {
              return demoProps().ariaDescribedBy || undefined;
            },
            get "aria-details"() {
              return demoProps().ariaDetails || undefined;
            },
            get value() {
              return demoProps().valueSource === "value" ? value() : undefined;
            },
            get defaultValue() {
              return demoProps().valueSource === "defaultValue"
                ? parseSolidColorWheelValue(
                    demoProps().defaultValue,
                    colorWheelDemoDefaults.defaultValue,
                  )
                : undefined;
            },
            get size() {
              return colorWheelDemoSizeNumber(demoProps());
            },
            get name() {
              return demoProps().name || undefined;
            },
            get form() {
              return demoProps().form || undefined;
            },
            get id() {
              return demoProps().id || undefined;
            },
            get slot() {
              return demoProps().slot || undefined;
            },
            get isDisabled() {
              return demoProps().isDisabled;
            },
            onChange: (nextValue: ReturnType<typeof parseSolidColorWheelValue>) => {
              setValue(nextValue);
              setDemoProps((current: ColorWheelDemoProps) =>
                current.valueSource === "value"
                  ? { ...current, value: solidColorWheelToCssString(nextValue) }
                  : current,
              );
            },
            onChangeEnd: (nextValue: ReturnType<typeof parseSolidColorWheelValue>) => {
              setFinalValue(nextValue);
            },
          }),
        ],
      ),
    ],
  );
}

export default () => h(SolidSpectrumColorWheelDemo, {});

// apps/comparison/src/components/react/fixtures/styled/colorwheel.js
import { jsx } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import {
  ColorWheel as SpectrumColorWheel,
  parseColor as spectrumParseWheelColor,
} from "@react-spectrum/s2/ColorWheel";
import { buttonDemoLocaleFromWindow } from "@comparison/data/button-demo";
import {
  colorWheelDemoDefaults,
  colorWheelDemoPropsFromWindow,
  colorWheelDemoSizeNumber,
  comparisonControlsEvent as colorWheelControlsEvent,
  initialColorWheelDemoValue,
  normalizeColorWheelDemoProps,
  serializeColorWheelDemoProps,
} from "@comparison/data/colorwheel-demo";
import {
  useComparisonResolvedTheme,
  renderReactSpectrumReference,
  colorToCssString,
} from "../styled-shared.js";

function parseSpectrumColorWheelValue(value, fallback = colorWheelDemoDefaults.value) {
  try {
    return spectrumParseWheelColor(value || fallback);
  } catch {
    return spectrumParseWheelColor(fallback);
  }
}

function ReactColorWheelDemo() {
  const [demoProps, setDemoProps] = useState(colorWheelDemoPropsFromWindow);
  const [value, setValue] = useState(() =>
    parseSpectrumColorWheelValue(initialColorWheelDemoValue(demoProps)),
  );
  const [finalValue, setFinalValue] = useState(() =>
    parseSpectrumColorWheelValue(initialColorWheelDemoValue(demoProps)),
  );
  const colorScheme = useComparisonResolvedTheme();
  const locale = buttonDemoLocaleFromWindow();

  useEffect(() => {
    const handleControlsChange = (event) => {
      if (event instanceof CustomEvent && event.detail?.component === "colorwheel") {
        const nextProps = normalizeColorWheelDemoProps(event.detail.props ?? {});
        const nextValue = parseSpectrumColorWheelValue(initialColorWheelDemoValue(nextProps));
        setDemoProps(nextProps);
        setValue(nextValue);
        setFinalValue(nextValue);
      }
    };
    window.addEventListener(colorWheelControlsEvent, handleControlsChange);
    return () => window.removeEventListener(colorWheelControlsEvent, handleControlsChange);
  }, []);

  const valueProps =
    demoProps.valueSource === "defaultValue"
      ? {
          defaultValue: parseSpectrumColorWheelValue(
            demoProps.defaultValue,
            colorWheelDemoDefaults.defaultValue,
          ),
        }
      : { value };
  const renderKey = [
    demoProps.valueSource,
    demoProps.valueSource === "defaultValue" ? demoProps.defaultValue : "controlled",
    demoProps.size,
    demoProps.ariaLabel,
    demoProps.ariaLabelledBy,
    demoProps.ariaDescribedBy,
    demoProps.ariaDetails,
    demoProps.id,
    demoProps.slot,
    demoProps.name,
    demoProps.form,
    demoProps.isDisabled,
  ].join("|");

  return renderReactSpectrumReference(
    jsx("div", {
      "data-comparison-control-root": "colorwheel",
      "data-comparison-control-props": serializeColorWheelDemoProps(demoProps),
      "data-comparison-value": colorToCssString(value),
      "data-comparison-final-value": colorToCssString(finalValue),
      children: jsx(
        SpectrumColorWheel,
        {
          "aria-label": demoProps.ariaLabel || undefined,
          "aria-labelledby": demoProps.ariaLabelledBy || undefined,
          "aria-describedby": demoProps.ariaDescribedBy || undefined,
          "aria-details": demoProps.ariaDetails || undefined,
          ...valueProps,
          size: colorWheelDemoSizeNumber(demoProps),
          name: demoProps.name || undefined,
          form: demoProps.form || undefined,
          id: demoProps.id || undefined,
          slot: demoProps.slot || undefined,
          isDisabled: demoProps.isDisabled,
          onChange: (nextValue) => {
            setValue(nextValue);
            setDemoProps((current) =>
              current.valueSource === "value"
                ? { ...current, value: colorToCssString(nextValue) }
                : current,
            );
          },
          onChangeEnd: setFinalValue,
        },
        renderKey,
      ),
    }),
    colorScheme,
    locale,
  );
}

export default () => jsx(ReactColorWheelDemo, {});
