// apps/comparison/src/components/solid/fixtures/styled/colorfield.tsx
import h from "solid-js/h";
import { createMemo, createSignal, onCleanup, onMount } from "solid-js";
import { hc } from "../../solid-h";
import { ColorField as SolidSpectrumColorField } from "@proyecto-viviana/solid-spectrum/ColorField";
import { Provider as SolidSpectrumProvider } from "@proyecto-viviana/solid-spectrum/Provider";
import { parseColor as parseSolidSpectrumColor } from "@proyecto-viviana/solid-spectrum/ColorArea";
import { buttonDemoLocaleFromWindow } from "@comparison/data/button-demo";
import {
  colorFieldDemoDefaults,
  colorFieldDemoPropsFromWindow,
  initialColorFieldDemoValue,
  normalizeColorFieldDemoProps,
  serializeColorFieldDemoProps,
  type ColorFieldDemoProps,
  comparisonControlsEvent,
} from "@comparison/data/colorfield-demo";
import {
  comparisonThemeChangeEvent,
  getComparisonResolvedThemeFromDocument,
  type ComparisonResolvedTheme,
} from "@comparison/data/theme";
import { providerShellStyle } from "../styled-shared.tsx";

function parseSolidColorFieldValue(value: string, fallback = colorFieldDemoDefaults.value) {
  try {
    return value ? parseSolidSpectrumColor(value) : null;
  } catch {
    return parseSolidSpectrumColor(fallback);
  }
}

function solidColorFieldToCssString(color: ReturnType<typeof parseSolidColorFieldValue>) {
  return color?.toString("css") ?? "";
}

function SolidSpectrumColorFieldDemo() {
  const [demoProps, setDemoProps] = createSignal<ColorFieldDemoProps>(
    colorFieldDemoPropsFromWindow(),
  );
  const [value, setValue] = createSignal(
    parseSolidColorFieldValue(initialColorFieldDemoValue(demoProps())),
  );
  const [colorScheme, setColorScheme] = createSignal<ComparisonResolvedTheme>(
    getComparisonResolvedThemeFromDocument(),
  );
  const locale = buttonDemoLocaleFromWindow();

  onMount(() => {
    const handleControlsChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.component === "colorfield") {
        const nextProps = normalizeColorFieldDemoProps(event.detail.props ?? {});
        const nextValue = parseSolidColorFieldValue(initialColorFieldDemoValue(nextProps));
        setDemoProps(nextProps);
        setValue(nextValue);
      }
    };
    const handleThemeChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.resolvedTheme) {
        setColorScheme(event.detail.resolvedTheme as ComparisonResolvedTheme);
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    window.addEventListener(comparisonThemeChangeEvent, handleThemeChange);
    setColorScheme(getComparisonResolvedThemeFromDocument());
    onCleanup(() => {
      window.removeEventListener(comparisonControlsEvent, handleControlsChange);
      window.removeEventListener(comparisonThemeChangeEvent, handleThemeChange);
    });
  });

  const serializedProps = createMemo(() => serializeColorFieldDemoProps(demoProps()));

  return hc(
    SolidSpectrumProvider,
    {
      get colorScheme() {
        return colorScheme();
      },
      locale,
      background: "base",
      style: providerShellStyle,
    },
    [
      hc(
        "div",
        {
          "data-comparison-control-root": "colorfield",
          get "data-comparison-color-scheme"() {
            return colorScheme();
          },
          get "data-comparison-control-props"() {
            return serializedProps();
          },
          get "data-comparison-value"() {
            return solidColorFieldToCssString(value());
          },
        },
        [
          hc(SolidSpectrumColorField, {
            get "aria-label"() {
              return demoProps().ariaLabel || undefined;
            },
            get "aria-labelledby"() {
              return demoProps().ariaLabelledBy || undefined;
            },
            get "aria-describedby"() {
              return demoProps().ariaDescribedBy || undefined;
            },
            get "aria-details"() {
              return demoProps().ariaDetails || undefined;
            },
            get value() {
              return demoProps().valueSource === "value" ? value() : undefined;
            },
            get defaultValue() {
              return demoProps().valueSource === "defaultValue"
                ? parseSolidColorFieldValue(
                    demoProps().defaultValue,
                    colorFieldDemoDefaults.defaultValue,
                  )
                : undefined;
            },
            get label() {
              return demoProps().label || undefined;
            },
            get description() {
              return demoProps().description || undefined;
            },
            get errorMessage() {
              return demoProps().errorMessage || undefined;
            },
            get placeholder() {
              return demoProps().placeholder || undefined;
            },
            get channel() {
              return demoProps().channel || undefined;
            },
            get colorSpace() {
              return demoProps().colorSpace || undefined;
            },
            get name() {
              return demoProps().name || undefined;
            },
            get form() {
              return demoProps().form || undefined;
            },
            get id() {
              return demoProps().id || undefined;
            },
            get slot() {
              return demoProps().slot || undefined;
            },
            get isDisabled() {
              return demoProps().isDisabled;
            },
            get isReadOnly() {
              return demoProps().isReadOnly;
            },
            get isRequired() {
              return demoProps().isRequired;
            },
            get isInvalid() {
              return demoProps().isInvalid;
            },
            get validationBehavior() {
              return demoProps().validationBehavior || undefined;
            },
            get isWheelDisabled() {
              return demoProps().isWheelDisabled;
            },
            get size() {
              return demoProps().size;
            },
            get labelPosition() {
              return demoProps().labelPosition;
            },
            get labelAlign() {
              return demoProps().labelAlign;
            },
            get necessityIndicator() {
              return demoProps().necessityIndicator;
            },
            onChange: (nextValue: ReturnType<typeof parseSolidColorFieldValue>) => {
              setValue(nextValue);
              setDemoProps((current: ColorFieldDemoProps) =>
                current.valueSource === "value"
                  ? { ...current, value: solidColorFieldToCssString(nextValue) }
                  : current,
              );
            },
          }),
        ],
      ),
    ],
  );
}

export default () => h(SolidSpectrumColorFieldDemo, {});

// apps/comparison/src/components/react/fixtures/styled/colorfield.js
import { jsx } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import { parseColor as spectrumParseColor } from "@react-spectrum/s2/ColorArea";
import { ColorField as SpectrumColorField } from "@react-spectrum/s2/ColorField";
import { buttonDemoLocaleFromWindow } from "@comparison/data/button-demo";
import {
  colorFieldDemoDefaults,
  colorFieldDemoPropsFromWindow,
  initialColorFieldDemoValue,
  normalizeColorFieldDemoProps,
  serializeColorFieldDemoProps,
  comparisonControlsEvent,
} from "@comparison/data/colorfield-demo";
import {
  useComparisonResolvedTheme,
  renderReactSpectrumReference,
  colorToCssString,
} from "../styled-shared.js";

function parseSpectrumColorFieldValue(value, fallback = colorFieldDemoDefaults.value) {
  try {
    return value ? spectrumParseColor(value) : null;
  } catch {
    return spectrumParseColor(fallback);
  }
}

function ReactColorFieldDemo() {
  const [demoProps, setDemoProps] = useState(colorFieldDemoPropsFromWindow);
  const [value, setValue] = useState(() =>
    parseSpectrumColorFieldValue(initialColorFieldDemoValue(demoProps)),
  );
  const colorScheme = useComparisonResolvedTheme();
  const locale = buttonDemoLocaleFromWindow();

  useEffect(() => {
    const handleControlsChange = (event) => {
      if (event instanceof CustomEvent && event.detail?.component === "colorfield") {
        const nextProps = normalizeColorFieldDemoProps(event.detail.props ?? {});
        const nextValue = parseSpectrumColorFieldValue(initialColorFieldDemoValue(nextProps));
        setDemoProps(nextProps);
        setValue(nextValue);
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    return () => window.removeEventListener(comparisonControlsEvent, handleControlsChange);
  }, []);

  const valueProps =
    demoProps.valueSource === "defaultValue"
      ? {
          defaultValue: parseSpectrumColorFieldValue(
            demoProps.defaultValue,
            colorFieldDemoDefaults.defaultValue,
          ),
        }
      : { value };
  const renderKey = [
    demoProps.valueSource,
    demoProps.valueSource === "defaultValue" ? demoProps.defaultValue : "controlled",
    demoProps.channel,
    demoProps.colorSpace,
    demoProps.ariaLabel,
    demoProps.ariaLabelledBy,
    demoProps.ariaDescribedBy,
    demoProps.ariaDetails,
    demoProps.id,
    demoProps.slot,
    demoProps.label,
    demoProps.description,
    demoProps.errorMessage,
    demoProps.placeholder,
    demoProps.name,
    demoProps.form,
    demoProps.isDisabled,
    demoProps.isReadOnly,
    demoProps.isRequired,
    demoProps.isInvalid,
    demoProps.validationBehavior,
    demoProps.isWheelDisabled,
    demoProps.size,
    demoProps.labelPosition,
    demoProps.labelAlign,
    demoProps.necessityIndicator,
  ].join("|");

  return renderReactSpectrumReference(
    jsx("div", {
      "data-comparison-control-root": "colorfield",
      "data-comparison-control-props": serializeColorFieldDemoProps(demoProps),
      "data-comparison-value": colorToCssString(value),
      children: jsx(
        SpectrumColorField,
        {
          "aria-label": demoProps.ariaLabel || undefined,
          "aria-labelledby": demoProps.ariaLabelledBy || undefined,
          "aria-describedby": demoProps.ariaDescribedBy || undefined,
          "aria-details": demoProps.ariaDetails || undefined,
          ...valueProps,
          label: demoProps.label || undefined,
          description: demoProps.description || undefined,
          errorMessage: demoProps.errorMessage || undefined,
          placeholder: demoProps.placeholder || undefined,
          channel: demoProps.channel || undefined,
          colorSpace: demoProps.colorSpace || undefined,
          name: demoProps.name || undefined,
          form: demoProps.form || undefined,
          id: demoProps.id || undefined,
          slot: demoProps.slot || undefined,
          isDisabled: demoProps.isDisabled,
          isReadOnly: demoProps.isReadOnly,
          isRequired: demoProps.isRequired,
          isInvalid: demoProps.isInvalid,
          validationBehavior: demoProps.validationBehavior || undefined,
          isWheelDisabled: demoProps.isWheelDisabled,
          size: demoProps.size,
          labelPosition: demoProps.labelPosition,
          labelAlign: demoProps.labelAlign,
          necessityIndicator: demoProps.necessityIndicator,
          onChange: (nextValue) => {
            setValue(nextValue);
            setDemoProps((current) =>
              current.valueSource === "value"
                ? { ...current, value: colorToCssString(nextValue) }
                : current,
            );
          },
        },
        renderKey,
      ),
    }),
    colorScheme,
    locale,
  );
}

export default () => jsx(ReactColorFieldDemo, {});
