// apps/comparison/src/components/solid/fixtures/styled/colorarea.tsx
import h from "solid-js/h";
import { createMemo, createSignal, onCleanup, onMount } from "solid-js";
import { hc } from "../../solid-h";
import {
  ColorArea as SolidSpectrumColorArea,
  parseColor as parseSolidSpectrumColor,
} from "@proyecto-viviana/solid-spectrum/ColorArea";
import { Provider as SolidSpectrumProvider } from "@proyecto-viviana/solid-spectrum/Provider";
import { buttonDemoLocaleFromWindow } from "@comparison/data/button-demo";
import {
  colorAreaDemoDefaults,
  colorAreaDemoPropsFromWindow,
  initialColorAreaDemoValue,
  normalizeColorAreaDemoProps,
  serializeColorAreaDemoProps,
  type ColorAreaDemoProps,
  comparisonControlsEvent,
} from "@comparison/data/colorarea-demo";
import {
  comparisonThemeChangeEvent,
  getComparisonResolvedThemeFromDocument,
  type ComparisonResolvedTheme,
} from "@comparison/data/theme";
import { providerShellStyle } from "../styled-shared.tsx";

function parseSolidColorAreaValue(value: string, fallback = colorAreaDemoDefaults.value) {
  try {
    return parseSolidSpectrumColor(value || fallback);
  } catch {
    return parseSolidSpectrumColor(fallback);
  }
}

function solidColorToCssString(color: ReturnType<typeof parseSolidColorAreaValue>) {
  return color.toString("css");
}

function SolidSpectrumColorAreaDemo() {
  const [demoProps, setDemoProps] = createSignal<ColorAreaDemoProps>(
    colorAreaDemoPropsFromWindow(),
  );
  const [value, setValue] = createSignal(
    parseSolidColorAreaValue(initialColorAreaDemoValue(demoProps())),
  );
  const [finalValue, setFinalValue] = createSignal(
    parseSolidColorAreaValue(initialColorAreaDemoValue(demoProps())),
  );
  const [colorScheme, setColorScheme] = createSignal<ComparisonResolvedTheme>(
    getComparisonResolvedThemeFromDocument(),
  );
  const locale = buttonDemoLocaleFromWindow();

  onMount(() => {
    const handleControlsChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.component === "colorarea") {
        const nextProps = normalizeColorAreaDemoProps(event.detail.props ?? {});
        const nextValue = parseSolidColorAreaValue(initialColorAreaDemoValue(nextProps));
        setDemoProps(nextProps);
        setValue(nextValue);
        setFinalValue(nextValue);
      }
    };
    const handleThemeChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.resolvedTheme) {
        setColorScheme(event.detail.resolvedTheme as ComparisonResolvedTheme);
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    window.addEventListener(comparisonThemeChangeEvent, handleThemeChange);
    setColorScheme(getComparisonResolvedThemeFromDocument());
    onCleanup(() => {
      window.removeEventListener(comparisonControlsEvent, handleControlsChange);
      window.removeEventListener(comparisonThemeChangeEvent, handleThemeChange);
    });
  });

  const serializedProps = createMemo(() => serializeColorAreaDemoProps(demoProps()));

  return hc(
    SolidSpectrumProvider,
    {
      get colorScheme() {
        return colorScheme();
      },
      locale,
      background: "base",
      style: providerShellStyle,
    },
    [
      hc(
        "div",
        {
          "data-comparison-control-root": "colorarea",
          get "data-comparison-color-scheme"() {
            return colorScheme();
          },
          get "data-comparison-control-props"() {
            return serializedProps();
          },
          get "data-comparison-value"() {
            return solidColorToCssString(value());
          },
          get "data-comparison-final-value"() {
            return solidColorToCssString(finalValue());
          },
        },
        [
          hc(SolidSpectrumColorArea, {
            get "aria-label"() {
              return demoProps().ariaLabel || undefined;
            },
            get "aria-labelledby"() {
              return demoProps().ariaLabelledBy || undefined;
            },
            get "aria-describedby"() {
              return demoProps().ariaDescribedBy || undefined;
            },
            get "aria-details"() {
              return demoProps().ariaDetails || undefined;
            },
            get value() {
              return demoProps().valueSource === "value" ? value() : undefined;
            },
            get defaultValue() {
              return demoProps().valueSource === "defaultValue"
                ? parseSolidColorAreaValue(
                    demoProps().defaultValue,
                    colorAreaDemoDefaults.defaultValue,
                  )
                : undefined;
            },
            get colorSpace() {
              return demoProps().colorSpace || undefined;
            },
            get xChannel() {
              return demoProps().xChannel;
            },
            get yChannel() {
              return demoProps().yChannel;
            },
            get xName() {
              return demoProps().xName || undefined;
            },
            get yName() {
              return demoProps().yName || undefined;
            },
            get form() {
              return demoProps().form || undefined;
            },
            get id() {
              return demoProps().id || undefined;
            },
            get slot() {
              return demoProps().slot || undefined;
            },
            get isDisabled() {
              return demoProps().isDisabled;
            },
            onChange: (nextValue: ReturnType<typeof parseSolidColorAreaValue>) => {
              setValue(nextValue);
              setDemoProps((current: ColorAreaDemoProps) =>
                current.valueSource === "value"
                  ? { ...current, value: solidColorToCssString(nextValue) }
                  : current,
              );
            },
            onChangeEnd: (nextValue: ReturnType<typeof parseSolidColorAreaValue>) => {
              setFinalValue(nextValue);
            },
          }),
        ],
      ),
    ],
  );
}

export default () => h(SolidSpectrumColorAreaDemo, {});

// apps/comparison/src/components/react/fixtures/styled/colorarea.js
import { jsx } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import {
  ColorArea as SpectrumColorArea,
  parseColor as spectrumParseColor,
} from "@react-spectrum/s2/ColorArea";
import { buttonDemoLocaleFromWindow } from "@comparison/data/button-demo";
import {
  colorAreaDemoDefaults,
  colorAreaDemoPropsFromWindow,
  comparisonControlsEvent as colorAreaControlsEvent,
  initialColorAreaDemoValue,
  normalizeColorAreaDemoProps,
  serializeColorAreaDemoProps,
} from "@comparison/data/colorarea-demo";
import {
  useComparisonResolvedTheme,
  renderReactSpectrumReference,
  colorToCssString,
} from "../styled-shared.js";

function parseSpectrumColorForDemo(value, fallback = colorAreaDemoDefaults.value) {
  try {
    return spectrumParseColor(value || fallback);
  } catch {
    return spectrumParseColor(fallback);
  }
}

function ReactColorAreaDemo() {
  const [demoProps, setDemoProps] = useState(colorAreaDemoPropsFromWindow);
  const [value, setValue] = useState(() =>
    parseSpectrumColorForDemo(initialColorAreaDemoValue(demoProps)),
  );
  const [finalValue, setFinalValue] = useState(() =>
    parseSpectrumColorForDemo(initialColorAreaDemoValue(demoProps)),
  );
  const colorScheme = useComparisonResolvedTheme();
  const locale = buttonDemoLocaleFromWindow();

  useEffect(() => {
    const handleControlsChange = (event) => {
      if (event instanceof CustomEvent && event.detail?.component === "colorarea") {
        const nextProps = normalizeColorAreaDemoProps(event.detail.props ?? {});
        const nextValue = parseSpectrumColorForDemo(initialColorAreaDemoValue(nextProps));
        setDemoProps(nextProps);
        setValue(nextValue);
        setFinalValue(nextValue);
      }
    };
    window.addEventListener(colorAreaControlsEvent, handleControlsChange);
    return () => window.removeEventListener(colorAreaControlsEvent, handleControlsChange);
  }, []);

  const valueProps =
    demoProps.valueSource === "defaultValue"
      ? {
          defaultValue: parseSpectrumColorForDemo(
            demoProps.defaultValue,
            colorAreaDemoDefaults.defaultValue,
          ),
        }
      : { value };
  const renderKey = [
    demoProps.valueSource,
    demoProps.valueSource === "defaultValue" ? demoProps.defaultValue : "controlled",
    demoProps.colorSpace,
    demoProps.xChannel,
    demoProps.yChannel,
    demoProps.ariaLabel,
    demoProps.ariaLabelledBy,
    demoProps.ariaDescribedBy,
    demoProps.ariaDetails,
    demoProps.id,
    demoProps.slot,
    demoProps.xName,
    demoProps.yName,
    demoProps.form,
    demoProps.isDisabled,
  ].join("|");

  return renderReactSpectrumReference(
    jsx("div", {
      "data-comparison-control-root": "colorarea",
      "data-comparison-control-props": serializeColorAreaDemoProps(demoProps),
      "data-comparison-value": colorToCssString(value),
      "data-comparison-final-value": colorToCssString(finalValue),
      children: jsx(
        SpectrumColorArea,
        {
          "aria-label": demoProps.ariaLabel || undefined,
          "aria-labelledby": demoProps.ariaLabelledBy || undefined,
          "aria-describedby": demoProps.ariaDescribedBy || undefined,
          "aria-details": demoProps.ariaDetails || undefined,
          ...valueProps,
          colorSpace: demoProps.colorSpace || undefined,
          xChannel: demoProps.xChannel,
          yChannel: demoProps.yChannel,
          xName: demoProps.xName || undefined,
          yName: demoProps.yName || undefined,
          form: demoProps.form || undefined,
          id: demoProps.id || undefined,
          slot: demoProps.slot || undefined,
          isDisabled: demoProps.isDisabled,
          onChange: (nextValue) => {
            setValue(nextValue);
            setDemoProps((current) =>
              current.valueSource === "value"
                ? { ...current, value: colorToCssString(nextValue) }
                : current,
            );
          },
          onChangeEnd: setFinalValue,
        },
        renderKey,
      ),
    }),
    colorScheme,
    locale,
  );
}

export default () => jsx(ReactColorAreaDemo, {});
