// apps/comparison/src/components/solid/fixtures/styled/combobox.tsx
import h from "solid-js/h";
import { createMemo, createSignal, onCleanup, onMount } from "solid-js";
import { hc, renderProp } from "../../solid-h";
import {
  ComboBox as SolidSpectrumComboBox,
  ComboBoxItem as SolidSpectrumComboBoxItem,
} from "@proyecto-viviana/solid-spectrum/ComboBox";
import { ContextualHelp as SolidSpectrumContextualHelp } from "@proyecto-viviana/solid-spectrum/ContextualHelp";
import { Heading as SolidSpectrumHeading } from "@proyecto-viviana/solid-spectrum/Heading";
import { Provider as SolidSpectrumProvider } from "@proyecto-viviana/solid-spectrum/Provider";
import {
  comboBoxDemoLocaleFromWindow,
  comboBoxDemoPropsFromWindow,
  comboBoxItems,
  comboBoxLabelForKey,
  normalizeComboBoxDemoProps,
  serializeComboBoxDemoProps,
  type ComboBoxDemoProps,
  comparisonControlsEvent,
} from "@comparison/data/combobox-demo";
import {
  comparisonThemeChangeEvent,
  getComparisonResolvedThemeFromDocument,
  type ComparisonResolvedTheme,
} from "@comparison/data/theme";
import { providerShellStyle } from "../styled-shared.tsx";

function SolidSpectrumComboBoxDemo() {
  const locale = comboBoxDemoLocaleFromWindow();
  const [demoProps, setDemoProps] = createSignal<ComboBoxDemoProps>(comboBoxDemoPropsFromWindow());
  const [selectedKey, setSelectedKey] = createSignal(demoProps().selectedKey);
  const [inputValue, setInputValue] = createSignal(demoProps().inputValue);
  const [colorScheme, setColorScheme] = createSignal<ComparisonResolvedTheme>(
    getComparisonResolvedThemeFromDocument(),
  );
  const menuWidth = createMemo(() => {
    const parsed = Number.parseInt(demoProps().menuWidth, 10);
    return Number.isFinite(parsed) && parsed > 0 ? parsed : undefined;
  });
  const disabledKeys = createMemo(() =>
    demoProps().disableEnterprise ? ["enterprise"] : undefined,
  );
  const contextualHelp = createMemo(() =>
    demoProps().withContextualHelp
      ? hc(SolidSpectrumContextualHelp, {}, [
          hc(SolidSpectrumHeading, { slot: "title" }, ["Plan help"]),
          h("p", {}, ["Pick the plan that matches expected usage."]),
        ])
      : undefined,
  );

  onMount(() => {
    const handleControlsChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.component === "combobox") {
        const nextProps = normalizeComboBoxDemoProps(event.detail.props ?? {});
        setDemoProps(nextProps);
        setSelectedKey(nextProps.selectedKey);
        setInputValue(nextProps.inputValue);
      }
    };
    const handleThemeChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.resolvedTheme) {
        setColorScheme(event.detail.resolvedTheme as ComparisonResolvedTheme);
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    window.addEventListener(comparisonThemeChangeEvent, handleThemeChange);
    setColorScheme(getComparisonResolvedThemeFromDocument());
    onCleanup(() => {
      window.removeEventListener(comparisonControlsEvent, handleControlsChange);
      window.removeEventListener(comparisonThemeChangeEvent, handleThemeChange);
    });
  });

  const serializedProps = createMemo(() => serializeComboBoxDemoProps(demoProps()));

  return hc(
    SolidSpectrumProvider,
    {
      get colorScheme() {
        return colorScheme();
      },
      // Threaded so the D10 RTL driver's `?locale=ar-AE` gives the Provider
      // `direction: 'rtl'` and the portaled listbox popover inherits `dir="rtl"`.
      locale,
      background: "base",
      style: providerShellStyle,
    },
    [
      demoProps().form
        ? h("form", {
            hidden: true,
            get id() {
              return demoProps().form;
            },
          })
        : null,
      hc(
        "div",
        {
          "data-comparison-control-root": "combobox",
          get "data-comparison-color-scheme"() {
            return colorScheme();
          },
          get "data-comparison-control-props"() {
            return serializedProps();
          },
          get "data-comparison-value"() {
            return selectedKey();
          },
          get "data-comparison-input-value"() {
            return inputValue();
          },
        },
        [
          hc(
            SolidSpectrumComboBox,
            {
              items: comboBoxItems,
              getKey: (item: (typeof comboBoxItems)[number]) => item.id,
              getTextValue: (item: (typeof comboBoxItems)[number]) => item.label,
              get label() {
                return demoProps().label;
              },
              get selectedKey() {
                return demoProps().selectionSource === "selectedKey" ? selectedKey() : undefined;
              },
              get defaultSelectedKey() {
                return demoProps().selectionSource === "defaultSelectedKey"
                  ? demoProps().selectedKey
                  : undefined;
              },
              get inputValue() {
                return demoProps().inputSource === "inputValue" ? inputValue() : undefined;
              },
              get defaultInputValue() {
                return demoProps().inputSource === "defaultInputValue"
                  ? demoProps().inputValue
                  : undefined;
              },
              get placeholder() {
                return demoProps().placeholder;
              },
              get size() {
                return demoProps().size;
              },
              get labelPosition() {
                return demoProps().labelPosition;
              },
              get labelAlign() {
                return demoProps().labelAlign;
              },
              get necessityIndicator() {
                return demoProps().necessityIndicator;
              },
              get contextualHelp() {
                return contextualHelp();
              },
              get description() {
                return demoProps().description;
              },
              get errorMessage() {
                return demoProps().errorMessage;
              },
              get name() {
                return demoProps().name || undefined;
              },
              get form() {
                return demoProps().form || undefined;
              },
              get formValue() {
                return demoProps().formValue;
              },
              get validationBehavior() {
                return demoProps().validationBehavior;
              },
              get menuTrigger() {
                return demoProps().menuTrigger;
              },
              get direction() {
                return demoProps().direction;
              },
              get align() {
                return demoProps().align;
              },
              get menuWidth() {
                return menuWidth();
              },
              get shouldFlip() {
                return demoProps().shouldFlip;
              },
              get disabledKeys() {
                return disabledKeys();
              },
              get allowsCustomValue() {
                return demoProps().allowsCustomValue;
              },
              get isDisabled() {
                return demoProps().isDisabled;
              },
              get isReadOnly() {
                return demoProps().isReadOnly;
              },
              get isRequired() {
                return demoProps().isRequired;
              },
              get isInvalid() {
                return demoProps().isInvalid;
              },
              onSelectionChange: (nextKey: unknown) => {
                if (nextKey == null) {
                  return;
                }
                const nextSelectedKey = String(nextKey);
                const nextInputValue = comboBoxLabelForKey(nextSelectedKey);
                setSelectedKey(nextSelectedKey as ComboBoxDemoProps["selectedKey"]);
                setInputValue(nextInputValue);
                setDemoProps((current: ComboBoxDemoProps) => ({
                  ...current,
                  ...(current.selectionSource === "selectedKey"
                    ? { selectedKey: nextSelectedKey as ComboBoxDemoProps["selectedKey"] }
                    : {}),
                  ...(current.inputSource === "inputValue" ? { inputValue: nextInputValue } : {}),
                }));
              },
              onInputChange: (nextValue: string) => {
                setInputValue(nextValue);
                setDemoProps((current: ComboBoxDemoProps) =>
                  current.inputSource === "inputValue"
                    ? { ...current, inputValue: nextValue }
                    : current,
                );
              },
            },
            renderProp((item: (typeof comboBoxItems)[number]) =>
              hc(
                SolidSpectrumComboBoxItem,
                {
                  id: item.id,
                  get isDisabled() {
                    return item.id === "enterprise" && demoProps().disableEnterprise;
                  },
                },
                [item.label],
              ),
            ),
          ),
        ],
      ),
    ],
  );
}

export default () => h(SolidSpectrumComboBoxDemo, {});

// apps/comparison/src/components/react/fixtures/styled/combobox.js
import { jsx, jsxs } from "react/jsx-runtime";
import { Fragment, useEffect, useState } from "react";
import {
  ComboBox as SpectrumComboBox,
  ComboBoxItem as SpectrumComboBoxItem,
  ContextualHelp as SpectrumContextualHelp,
  Content as SpectrumContent,
  Heading as SpectrumHeading,
} from "@react-spectrum/s2";
import {
  comboBoxDemoLocaleFromWindow,
  comboBoxDemoPropsFromWindow,
  comboBoxItems,
  comboBoxLabelForKey,
  normalizeComboBoxDemoProps,
  serializeComboBoxDemoProps,
  comparisonControlsEvent,
} from "@comparison/data/combobox-demo";
import { useComparisonResolvedTheme, renderReactSpectrumReference } from "../styled-shared.js";

function ReactComboBoxDemo() {
  const [demoProps, setDemoProps] = useState(comboBoxDemoPropsFromWindow);
  const [selectedKey, setSelectedKey] = useState(() => demoProps.selectedKey);
  const [inputValue, setInputValue] = useState(() => demoProps.inputValue);
  const colorScheme = useComparisonResolvedTheme();
  const locale = comboBoxDemoLocaleFromWindow();
  const menuWidth = Number.parseInt(demoProps.menuWidth, 10);
  const numericMenuWidth = Number.isFinite(menuWidth) && menuWidth > 0 ? menuWidth : undefined;
  const disabledKeys = demoProps.disableEnterprise ? ["enterprise"] : undefined;
  const selectionProps =
    demoProps.selectionSource === "selectedKey"
      ? { selectedKey }
      : { defaultSelectedKey: demoProps.selectedKey };
  const inputProps =
    demoProps.inputSource === "inputValue"
      ? { inputValue }
      : { defaultInputValue: demoProps.inputValue };
  const contextualHelp = demoProps.withContextualHelp
    ? jsxs(SpectrumContextualHelp, {
        children: [
          jsx(SpectrumHeading, { slot: "title", children: "Plan help" }),
          jsx(SpectrumContent, { children: "Pick the plan that matches expected usage." }),
        ],
      })
    : undefined;
  const renderKey = [
    demoProps.selectionSource,
    demoProps.selectionSource === "defaultSelectedKey" ? demoProps.selectedKey : "controlled",
    demoProps.inputSource,
    demoProps.inputSource === "defaultInputValue" ? demoProps.inputValue : "controlled",
    demoProps.withContextualHelp,
  ].join("|");

  useEffect(() => {
    const handleControlsChange = (event) => {
      if (event instanceof CustomEvent && event.detail?.component === "combobox") {
        const nextProps = normalizeComboBoxDemoProps(event.detail.props ?? {});
        setDemoProps(nextProps);
        setSelectedKey(nextProps.selectedKey);
        setInputValue(nextProps.inputValue);
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    return () => window.removeEventListener(comparisonControlsEvent, handleControlsChange);
  }, []);

  return renderReactSpectrumReference(
    jsxs(Fragment, {
      children: [
        demoProps.form ? jsx("form", { id: demoProps.form, hidden: true }) : null,
        jsx("div", {
          "data-comparison-control-root": "combobox",
          "data-comparison-control-props": serializeComboBoxDemoProps(demoProps),
          "data-comparison-value": selectedKey,
          "data-comparison-input-value": inputValue,
          children: jsx(
            SpectrumComboBox,
            {
              label: demoProps.label,
              ...selectionProps,
              ...inputProps,
              placeholder: demoProps.placeholder,
              size: demoProps.size,
              labelPosition: demoProps.labelPosition,
              labelAlign: demoProps.labelAlign,
              necessityIndicator: demoProps.necessityIndicator,
              contextualHelp,
              description: demoProps.description,
              errorMessage: demoProps.errorMessage,
              name: demoProps.name || undefined,
              form: demoProps.form || undefined,
              formValue: demoProps.formValue,
              validationBehavior: demoProps.validationBehavior,
              menuTrigger: demoProps.menuTrigger,
              direction: demoProps.direction,
              align: demoProps.align,
              menuWidth: numericMenuWidth,
              shouldFlip: demoProps.shouldFlip,
              disabledKeys,
              allowsCustomValue: demoProps.allowsCustomValue,
              isDisabled: demoProps.isDisabled,
              isReadOnly: demoProps.isReadOnly,
              isRequired: demoProps.isRequired,
              isInvalid: demoProps.isInvalid,
              onSelectionChange: (nextKey) => {
                if (nextKey == null) {
                  return;
                }
                const nextSelectedKey = String(nextKey);
                const nextInputValue = comboBoxLabelForKey(nextSelectedKey);
                setSelectedKey(nextSelectedKey);
                setInputValue(nextInputValue);
                setDemoProps((current) => ({
                  ...current,
                  ...(current.selectionSource === "selectedKey"
                    ? { selectedKey: nextSelectedKey }
                    : {}),
                  ...(current.inputSource === "inputValue" ? { inputValue: nextInputValue } : {}),
                }));
              },
              onInputChange: (nextValue) => {
                setInputValue(nextValue);
                setDemoProps((current) =>
                  current.inputSource === "inputValue"
                    ? { ...current, inputValue: nextValue }
                    : current,
                );
              },
              children: (item) =>
                jsx(
                  SpectrumComboBoxItem,
                  {
                    id: item.id,
                    isDisabled: item.id === "enterprise" && demoProps.disableEnterprise,
                    children: item.label,
                  },
                  item.id,
                ),
              items: comboBoxItems,
            },
            renderKey,
          ),
        }),
      ],
    }),
    colorScheme,
    locale,
  );
}

export default () => jsx(ReactComboBoxDemo, {});
