// apps/comparison/src/components/solid/fixtures/styled/dialog.tsx
import h from "solid-js/h";
import { createMemo, createSignal, onCleanup, onMount } from "solid-js";
import { hc } from "../../solid-h";
import { Button as SolidSpectrumButton } from "@proyecto-viviana/solid-spectrum/Button";
import { Content as SolidSpectrumContent } from "@proyecto-viviana/solid-spectrum/Content";
import { AlertDialog as SolidSpectrumAlertDialog } from "@proyecto-viviana/solid-spectrum/AlertDialog";
import {
  Dialog as SolidSpectrumDialog,
  DialogTrigger as SolidSpectrumDialogTrigger,
} from "@proyecto-viviana/solid-spectrum/Dialog";
import { Heading as SolidSpectrumHeading } from "@proyecto-viviana/solid-spectrum/Heading";
import { Provider as SolidSpectrumProvider } from "@proyecto-viviana/solid-spectrum/Provider";
import { Text as SolidSpectrumText } from "@proyecto-viviana/solid-spectrum/Text";
import { dispatchComparisonCallback } from "@comparison/data/event-log";
import {
  dialogDemoPropsFromWindow,
  normalizeDialogDemoProps,
  serializeDialogDemoProps,
  type DialogDemoProps,
  comparisonControlsEvent,
} from "@comparison/data/dialog-demo";
import {
  comparisonThemeChangeEvent,
  getComparisonResolvedThemeFromDocument,
  type ComparisonResolvedTheme,
} from "@comparison/data/theme";
import { providerShellStyle } from "../styled-shared.tsx";

function SolidSpectrumDialogDemo() {
  const [demoProps, setDemoProps] = createSignal<DialogDemoProps>(dialogDemoPropsFromWindow());
  const [isOpen, setIsOpen] = createSignal(demoProps().isOpen);
  const [colorScheme, setColorScheme] = createSignal<ComparisonResolvedTheme>(
    getComparisonResolvedThemeFromDocument(),
  );

  onMount(() => {
    const handleControlsChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.component === "dialog") {
        const nextProps = normalizeDialogDemoProps(event.detail.props ?? {});
        setDemoProps(nextProps);
        setIsOpen(nextProps.isOpen);
      }
    };
    const handleThemeChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.resolvedTheme) {
        setColorScheme(event.detail.resolvedTheme as ComparisonResolvedTheme);
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    window.addEventListener(comparisonThemeChangeEvent, handleThemeChange);
    setColorScheme(getComparisonResolvedThemeFromDocument());
    onCleanup(() => {
      window.removeEventListener(comparisonControlsEvent, handleControlsChange);
      window.removeEventListener(comparisonThemeChangeEvent, handleThemeChange);
    });
  });

  const serializedProps = createMemo(() =>
    serializeDialogDemoProps({
      ...demoProps(),
      isOpen: isOpen(),
    }),
  );

  const handleOpenChange = (nextOpen: boolean) => {
    dispatchComparisonCallback("dialog", "onOpenChange", {
      target: document.activeElement,
      value: nextOpen,
    });
    // Track open state in its own signal only. Folding `isOpen` back into
    // `demoProps` is redundant — `serializedProps` already overlays `isOpen()`
    // — and harmful in Solid: the role-conditional child below reads
    // `demoProps()`, so perturbing it on every open/close re-runs that thunk and
    // recreates the whole Dialog subtree (tearing the focused section's portal
    // out mid-gesture, before `keyup`). React reconciles the same conditional by
    // type and keeps it mounted; decoupling `isOpen` here matches that so the D4
    // event-sequence oracle isolates dismiss/focus behavior, not fixture churn.
    setIsOpen(nextOpen);
  };

  return hc(
    SolidSpectrumProvider,
    {
      get colorScheme() {
        return colorScheme();
      },
      background: "base",
      style: providerShellStyle,
    },
    [
      hc(
        "div",
        {
          "data-comparison-control-root": "dialog",
          get "data-comparison-control-props"() {
            return serializedProps();
          },
          get "data-comparison-open"() {
            return String(isOpen());
          },
        },
        [
          hc(
            SolidSpectrumDialogTrigger,
            {
              get isOpen() {
                return isOpen();
              },
              onOpenChange: handleOpenChange,
            },
            [
              () =>
                hc(
                  SolidSpectrumButton,
                  {
                    variant: "primary",
                  },
                  [() => demoProps().triggerLabel],
                ),
              () =>
                demoProps().role === "alertdialog"
                  ? hc(
                      SolidSpectrumAlertDialog,
                      {
                        get title() {
                          return demoProps().title;
                        },
                        get variant() {
                          return demoProps().variant;
                        },
                        get size() {
                          // AlertDialog is S | M | L only; fold XL onto L.
                          return demoProps().size === "XL" ? "L" : demoProps().size;
                        },
                        get primaryActionLabel() {
                          return demoProps().primaryActionLabel;
                        },
                        get secondaryActionLabel() {
                          return demoProps().secondaryActionLabel || undefined;
                        },
                        get cancelLabel() {
                          return demoProps().cancelLabel || undefined;
                        },
                      },
                      [() => demoProps().body],
                    )
                  : hc(
                      SolidSpectrumDialog,
                      {
                        get size() {
                          return demoProps().size;
                        },
                        get role() {
                          return demoProps().role;
                        },
                        get isDismissible() {
                          return demoProps().isDismissible;
                        },
                        get isKeyboardDismissDisabled() {
                          return demoProps().isKeyboardDismissDisabled;
                        },
                      },
                      [
                        () => [
                          demoProps().hasTitle
                            ? hc(
                                SolidSpectrumHeading,
                                {
                                  slot: "title",
                                },
                                [() => demoProps().title],
                              )
                            : null,
                          hc(SolidSpectrumContent, {}, [
                            () => hc(SolidSpectrumText, {}, [() => demoProps().body]),
                          ]),
                        ],
                      ],
                    ),
            ],
          ),
        ],
      ),
    ],
  );
}

export default () => h(SolidSpectrumDialogDemo, {});

// apps/comparison/src/components/react/fixtures/styled/dialog.js
import { jsx, jsxs } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import {
  Button as SpectrumButton,
  Content as SpectrumContent,
  AlertDialog as SpectrumAlertDialog,
  Dialog as SpectrumDialog,
  DialogTrigger as SpectrumDialogTrigger,
  Heading as SpectrumHeading,
  Text as SpectrumText,
} from "@react-spectrum/s2";
import { dispatchComparisonCallback } from "@comparison/data/event-log";
import {
  dialogDemoPropsFromWindow,
  normalizeDialogDemoProps,
  serializeDialogDemoProps,
  comparisonControlsEvent,
} from "@comparison/data/dialog-demo";
import { useComparisonResolvedTheme, renderReactSpectrumReference } from "../styled-shared.js";

function ReactDialogDemo() {
  const [demoProps, setDemoProps] = useState(dialogDemoPropsFromWindow);
  const [isOpen, setIsOpen] = useState(() => demoProps.isOpen);
  const colorScheme = useComparisonResolvedTheme();

  useEffect(() => {
    const handleControlsChange = (event) => {
      if (event instanceof CustomEvent && event.detail?.component === "dialog") {
        const nextProps = normalizeDialogDemoProps(event.detail.props ?? {});
        setDemoProps(nextProps);
        setIsOpen(nextProps.isOpen);
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    return () => window.removeEventListener(comparisonControlsEvent, handleControlsChange);
  }, []);

  const serializedProps = serializeDialogDemoProps({
    ...demoProps,
    isOpen,
  });

  return renderReactSpectrumReference(
    jsx("div", {
      "data-comparison-control-root": "dialog",
      "data-comparison-control-props": serializedProps,
      "data-comparison-open": String(isOpen),
      children: jsxs(SpectrumDialogTrigger, {
        isOpen,
        onOpenChange: (nextOpen) => {
          dispatchComparisonCallback("dialog", "onOpenChange", {
            target: document.activeElement,
            value: nextOpen,
          });
          setIsOpen(nextOpen);
          setDemoProps((current) => ({ ...current, isOpen: nextOpen }));
        },
        children: [
          jsx(SpectrumButton, { variant: "primary", children: demoProps.triggerLabel }),
          demoProps.role === "alertdialog"
            ? jsx(SpectrumAlertDialog, {
                title: demoProps.title,
                variant: demoProps.variant,
                // AlertDialog is S | M | L only; fold XL onto L.
                size: demoProps.size === "XL" ? "L" : demoProps.size,
                primaryActionLabel: demoProps.primaryActionLabel,
                secondaryActionLabel: demoProps.secondaryActionLabel || undefined,
                cancelLabel: demoProps.cancelLabel || undefined,
                children: demoProps.body,
              })
            : jsxs(SpectrumDialog, {
                isDismissible: demoProps.isDismissible,
                isKeyboardDismissDisabled: demoProps.isKeyboardDismissDisabled,
                role: demoProps.role,
                size: demoProps.size,
                children: [
                  demoProps.hasTitle
                    ? jsx(SpectrumHeading, { slot: "title", children: demoProps.title })
                    : null,
                  jsx(SpectrumContent, {
                    children: jsx(SpectrumText, {
                      children: demoProps.body,
                    }),
                  }),
                ],
              }),
        ],
      }),
    }),
    colorScheme,
  );
}

export default () => jsx(ReactDialogDemo, {});
