// apps/comparison/src/components/solid/fixtures/styled/dnd-listbox.tsx
import h from "solid-js/h";
import { createEffect, createMemo, createSignal, onCleanup, onMount } from "solid-js";
import { hc, renderProp } from "../../solid-h";
import { Provider as SolidSpectrumProvider } from "@proyecto-viviana/solid-spectrum";
import {
  ListBox as SolidHeadlessListBox,
  ListBoxOption as SolidHeadlessListBoxOption,
  useDragAndDrop as useSolidDragAndDrop,
  createListData as createSolidListData,
} from "@proyecto-viviana/solidaria-components";
import {
  dndListBoxDemoItems,
  dndListBoxDemoPropsFromWindow,
  normalizeDndListBoxDemoProps,
  serializeDndListBoxDemoProps,
  serializeDndListBoxOrder,
  type DndListBoxDemoItem,
  type DndListBoxDemoProps,
  comparisonControlsEvent,
} from "@comparison/data/dnd-listbox-demo";
import {
  comparisonThemeChangeEvent,
  getComparisonResolvedThemeFromDocument,
  type ComparisonResolvedTheme,
} from "@comparison/data/theme";
import { providerShellStyle } from "../styled-shared.tsx";

// Keyboard-DnD port: the Solid `useDragAndDrop`/`createListData` pair driving the
// headless ListBox, mirroring the RAC reorderable-ListBox oracle field for field
// (getItems + onReorder branching on dropPosition → moveBefore/moveAfter). The
// live item order is published on the listbox root as `data-comparison-order` so
// the reorder cert pair-diffs the keyboard-drag result against RAC.
function SolidSpectrumDndListBoxDemo() {
  const [demoProps, setDemoProps] = createSignal<DndListBoxDemoProps>(
    dndListBoxDemoPropsFromWindow(),
  );
  const [colorScheme, setColorScheme] = createSignal<ComparisonResolvedTheme>(
    getComparisonResolvedThemeFromDocument(),
  );
  const list = createSolidListData<DndListBoxDemoItem>({ initialItems: dndListBoxDemoItems });

  onMount(() => {
    const handleControlsChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.component === "dnd-listbox") {
        setDemoProps(normalizeDndListBoxDemoProps(event.detail.props ?? {}));
      }
    };
    const handleThemeChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.resolvedTheme) {
        setColorScheme(event.detail.resolvedTheme as ComparisonResolvedTheme);
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    window.addEventListener(comparisonThemeChangeEvent, handleThemeChange);
    setColorScheme(getComparisonResolvedThemeFromDocument());
    onCleanup(() => {
      window.removeEventListener(comparisonControlsEvent, handleControlsChange);
      window.removeEventListener(comparisonThemeChangeEvent, handleThemeChange);
    });
  });

  const { dragAndDropHooks } = useSolidDragAndDrop<DndListBoxDemoItem>({
    getItems: (keys) =>
      [...keys].map((key) => {
        const item = list.getItem(key);
        return { "text/plain": item?.label ?? String(key) };
      }),
    onReorder(e) {
      if (e.target.dropPosition === "before") {
        list.moveBefore(e.target.key, e.keys);
      } else if (e.target.dropPosition === "after") {
        list.moveAfter(e.target.key, e.keys);
      }
    },
  });

  const renderedListBox = createMemo(() =>
    hc(
      SolidHeadlessListBox,
      {
        "aria-label": "Permissions",
        get selectionMode() {
          return demoProps().selectionMode;
        },
        get items() {
          return list.items;
        },
        dragAndDropHooks,
        getKey: (item: DndListBoxDemoItem) => item.id,
        getTextValue: (item: DndListBoxDemoItem) => item.label,
        "data-comparison-control-root": "dnd-listbox",
        get "data-comparison-control-props"() {
          return serializeDndListBoxDemoProps(demoProps());
        },
        // Publish the live reorder result on the listbox root via a ref effect
        // rather than a spread-delivered `data-*` prop. The React oracle re-renders
        // the whole tree on each store change so a spread attribute stays live for
        // it; Solid renders the root once and binds spread attributes statically, so
        // a reactive test-only attribute routed through the DOM-prop spread would
        // freeze at first paint. An explicit ref effect (the same reactive path the
        // component's own `data-focused`/`data-orientation` attributes use) keeps the
        // published order in lockstep with `list.items` after each keyboard drop.
        ref: (el: HTMLElement) => {
          createEffect(() => {
            el.setAttribute("data-comparison-order", serializeDndListBoxOrder(list.items));
          });
        },
      },
      renderProp((item: DndListBoxDemoItem) =>
        hc(SolidHeadlessListBoxOption, { id: item.id, textValue: item.label }, [item.label]),
      ),
    ),
  );

  return hc(
    SolidSpectrumProvider,
    {
      get colorScheme() {
        return colorScheme();
      },
      background: "base",
      style: providerShellStyle,
    },
    [
      hc(
        "div",
        {
          class: "comparison-listbox-row",
        },
        [h("button", {}, "Before"), renderedListBox, h("button", {}, "After")],
      ),
    ],
  );
}

export default () => h(SolidSpectrumDndListBoxDemo, {});

// apps/comparison/src/components/react/fixtures/styled/dnd-listbox.js
import { jsx, jsxs } from "react/jsx-runtime";
import { Fragment, useEffect, useState } from "react";
import {
  ListBox as AriaListBox,
  ListBoxItem as AriaListBoxItem,
  useDragAndDrop as useAriaDragAndDrop,
} from "react-aria-components";
import { useListData as useAriaListData } from "react-stately";
import {
  dndListBoxDemoItems,
  dndListBoxDemoPropsFromWindow,
  normalizeDndListBoxDemoProps,
  serializeDndListBoxDemoProps,
  serializeDndListBoxOrder,
  comparisonControlsEvent,
} from "@comparison/data/dnd-listbox-demo";
import { useComparisonResolvedTheme, renderReactSpectrumReference } from "../styled-shared.js";

// Keyboard-DnD oracle: RAC's own reorderable ListBox — `useDragAndDrop`
// (getItems + onReorder) wired to a `useListData` list, exactly as the vendored
// `ListBoxDnd` story does. The live item order is published on the listbox root
// as `data-comparison-order` so the reorder cert can pair-diff the result of a
// keyboard drag against the Solid port. Before/After boundary buttons let the
// D5-style walk cross the tab boundary to enter the collection by keyboard.
function ReactDndListBoxDemo() {
  const [demoProps, setDemoProps] = useState(dndListBoxDemoPropsFromWindow);
  const colorScheme = useComparisonResolvedTheme();
  const list = useAriaListData({ initialItems: dndListBoxDemoItems });

  useEffect(() => {
    const handleControlsChange = (event) => {
      if (event instanceof CustomEvent && event.detail?.component === "dnd-listbox") {
        setDemoProps(normalizeDndListBoxDemoProps(event.detail.props ?? {}));
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    return () => window.removeEventListener(comparisonControlsEvent, handleControlsChange);
  }, []);

  const { dragAndDropHooks } = useAriaDragAndDrop({
    getItems: (keys) =>
      [...keys].map((key) => {
        const item = list.getItem(key);
        return { "text/plain": item?.label ?? String(key) };
      }),
    onReorder(e) {
      if (e.target.dropPosition === "before") {
        list.moveBefore(e.target.key, e.keys);
      } else if (e.target.dropPosition === "after") {
        list.moveAfter(e.target.key, e.keys);
      }
    },
  });

  return renderReactSpectrumReference(
    jsxs(Fragment, {
      children: [
        jsx("button", { children: "Before" }),
        jsx(AriaListBox, {
          "aria-label": "Permissions",
          selectionMode: demoProps.selectionMode,
          items: list.items,
          dragAndDropHooks,
          "data-comparison-control-root": "dnd-listbox",
          "data-comparison-control-props": serializeDndListBoxDemoProps(demoProps),
          "data-comparison-order": serializeDndListBoxOrder(list.items),
          children: (item) => jsx(AriaListBoxItem, { id: item.id, children: item.label }, item.id),
        }),
        jsx("button", { children: "After" }),
      ],
    }),
    colorScheme,
  );
}

export default () => jsx(ReactDndListBoxDemo, {});
