// apps/comparison/src/components/solid/fixtures/styled/dropzone.tsx
import h from "solid-js/h";
import { createMemo, createSignal, onCleanup, onMount } from "solid-js";
import { hc } from "../../solid-h";
import { Content as SolidSpectrumContent } from "@proyecto-viviana/solid-spectrum/Content";
import { DropZone as SolidSpectrumDropZone } from "@proyecto-viviana/solid-spectrum/DropZone";
import { Heading as SolidSpectrumHeading } from "@proyecto-viviana/solid-spectrum/Heading";
import { IllustratedMessage as SolidSpectrumIllustratedMessage } from "@proyecto-viviana/solid-spectrum/IllustratedMessage";
import { Provider as SolidSpectrumProvider } from "@proyecto-viviana/solid-spectrum/Provider";
import {
  dropZoneDemoPropsFromWindow,
  normalizeDropZoneDemoProps,
  serializeDropZoneDemoProps,
  type DropZoneDemoProps,
} from "@comparison/data/dropzone-demo";
import { comparisonControlsEvent } from "@comparison/data/button-demo";
import {
  comparisonThemeChangeEvent,
  getComparisonResolvedThemeFromDocument,
  type ComparisonResolvedTheme,
} from "@comparison/data/theme";
import { SolidDropZoneIllustration, providerShellStyle } from "../styled-shared.tsx";

interface DropZoneCounts {
  activate: number;
  drop: number;
  enter: number;
  exit: number;
  move: number;
}

type DropZoneCountKey = keyof DropZoneCounts;

function SolidSpectrumDropZoneDemo() {
  const [demoProps, setDemoProps] = createSignal<DropZoneDemoProps>(dropZoneDemoPropsFromWindow());
  const [counts, setCounts] = createSignal<DropZoneCounts>({
    activate: 0,
    drop: 0,
    enter: 0,
    exit: 0,
    move: 0,
  });
  const [colorScheme, setColorScheme] = createSignal<ComparisonResolvedTheme>(
    getComparisonResolvedThemeFromDocument(),
  );

  onMount(() => {
    const handleControlsChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.component === "dropzone") {
        setDemoProps(normalizeDropZoneDemoProps(event.detail.props ?? {}));
      }
    };
    const handleThemeChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.resolvedTheme) {
        setColorScheme(event.detail.resolvedTheme as ComparisonResolvedTheme);
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    window.addEventListener(comparisonThemeChangeEvent, handleThemeChange);
    setColorScheme(getComparisonResolvedThemeFromDocument());
    onCleanup(() => {
      window.removeEventListener(comparisonControlsEvent, handleControlsChange);
      window.removeEventListener(comparisonThemeChangeEvent, handleThemeChange);
    });
  });

  const bump = (key: DropZoneCountKey) => {
    setCounts((current) => ({ ...current, [key]: current[key] + 1 }));
  };

  const renderedDropZone = createMemo(() =>
    hc(SolidSpectrumDropZone, {
      "data-comparison-control-root": "dropzone",
      get "data-comparison-control-props"() {
        return serializeDropZoneDemoProps(demoProps());
      },
      get "data-comparison-drop-activate-count"() {
        return counts().activate;
      },
      get "data-comparison-drop-count"() {
        return counts().drop;
      },
      get "data-comparison-drop-enter-count"() {
        return counts().enter;
      },
      get "data-comparison-drop-exit-count"() {
        return counts().exit;
      },
      get "data-comparison-drop-move-count"() {
        return counts().move;
      },
      id: "dropzone-route-root",
      get "aria-label"() {
        return demoProps().ariaLabel;
      },
      "aria-describedby": "dropzone-route-description",
      "aria-details": "dropzone-route-details",
      get size() {
        return demoProps().size;
      },
      get isFilled() {
        return demoProps().isFilled;
      },
      get replaceMessage() {
        return demoProps().replaceMessage || undefined;
      },
      onDropActivate: () => bump("activate"),
      onDrop: () => bump("drop"),
      onDropEnter: () => bump("enter"),
      onDropExit: () => bump("exit"),
      onDropMove: () => bump("move"),
      get children() {
        return hc(SolidSpectrumIllustratedMessage, {}, [
          h(SolidDropZoneIllustration, { slot: "illustration" }),
          h(SolidSpectrumHeading, {}, "Upload assets"),
          h(SolidSpectrumContent, {}, "Drop a PNG, SVG, or PDF."),
          h(
            "span",
            {
              id: "dropzone-route-description",
              hidden: true,
            },
            "Drop target accepts project files.",
          ),
          h(
            "span",
            {
              id: "dropzone-route-details",
              hidden: true,
            },
            "The comparison route records drag and drop callback counts.",
          ),
        ]);
      },
    }),
  );

  return hc(
    SolidSpectrumProvider,
    {
      get colorScheme() {
        return colorScheme();
      },
      background: "base",
      style: providerShellStyle,
    },
    [
      hc(
        "div",
        {
          class: "comparison-dropzone-row",
          get "data-comparison-color-scheme"() {
            return colorScheme();
          },
        },
        [renderedDropZone],
      ),
    ],
  );
}

export default () => h(SolidSpectrumDropZoneDemo, {});

// apps/comparison/src/components/react/fixtures/styled/dropzone.js
import { jsx, jsxs } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import {
  Content as SpectrumContent,
  DropZone as SpectrumDropZone,
  Heading as SpectrumHeading,
  IllustratedMessage as SpectrumIllustratedMessage,
} from "@react-spectrum/s2";
import {
  dropZoneDemoPropsFromWindow,
  normalizeDropZoneDemoProps,
  serializeDropZoneDemoProps,
} from "@comparison/data/dropzone-demo";
import { comparisonControlsEvent } from "@comparison/data/button-demo";
import {
  useComparisonResolvedTheme,
  renderReactSpectrumReference,
  ReactDropZoneIllustration,
} from "../styled-shared.js";

function ReactDropZoneDemo() {
  const colorScheme = useComparisonResolvedTheme();
  const [demoProps, setDemoProps] = useState(dropZoneDemoPropsFromWindow);
  const [counts, setCounts] = useState({
    activate: 0,
    drop: 0,
    enter: 0,
    exit: 0,
    move: 0,
  });
  useEffect(() => {
    const handleControlsChange = (event) => {
      if (event instanceof CustomEvent && event.detail?.component === "dropzone") {
        setDemoProps(normalizeDropZoneDemoProps(event.detail.props ?? {}));
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    return () => window.removeEventListener(comparisonControlsEvent, handleControlsChange);
  }, []);

  const bump = (key) => {
    setCounts((current) => ({ ...current, [key]: current[key] + 1 }));
  };

  return renderReactSpectrumReference(
    jsx("div", {
      className: "comparison-dropzone-row",
      "data-comparison-color-scheme": colorScheme,
      children: jsx(SpectrumDropZone, {
        "data-comparison-control-root": "dropzone",
        "data-comparison-control-props": serializeDropZoneDemoProps(demoProps),
        "data-comparison-drop-activate-count": counts.activate,
        "data-comparison-drop-count": counts.drop,
        "data-comparison-drop-enter-count": counts.enter,
        "data-comparison-drop-exit-count": counts.exit,
        "data-comparison-drop-move-count": counts.move,
        id: "dropzone-route-root",
        "aria-label": demoProps.ariaLabel,
        "aria-describedby": "dropzone-route-description",
        "aria-details": "dropzone-route-details",
        size: demoProps.size,
        isFilled: demoProps.isFilled,
        replaceMessage: demoProps.replaceMessage || undefined,
        onDropActivate: () => bump("activate"),
        onDrop: () => bump("drop"),
        onDropEnter: () => bump("enter"),
        onDropExit: () => bump("exit"),
        onDropMove: () => bump("move"),
        children: jsxs(SpectrumIllustratedMessage, {
          children: [
            jsx(ReactDropZoneIllustration, { slot: "illustration" }),
            jsx(SpectrumHeading, { children: "Upload assets" }),
            jsx(SpectrumContent, { children: "Drop a PNG, SVG, or PDF." }),
            jsx("span", {
              id: "dropzone-route-description",
              hidden: true,
              children: "Drop target accepts project files.",
            }),
            jsx("span", {
              id: "dropzone-route-details",
              hidden: true,
              children: "The comparison route records drag and drop callback counts.",
            }),
          ],
        }),
      }),
    }),
    colorScheme,
  );
}

export default () => jsx(ReactDropZoneDemo, {});
