// apps/comparison/src/components/solid/fixtures/styled/form.tsx
import h from "solid-js/h";
import { createMemo, createSignal, onCleanup, onMount } from "solid-js";
import { hc } from "../../solid-h";
import { Button as SolidSpectrumButton } from "@proyecto-viviana/solid-spectrum/Button";
import { Form as SolidSpectrumForm } from "@proyecto-viviana/solid-spectrum/Form";
import { Provider as SolidSpectrumProvider } from "@proyecto-viviana/solid-spectrum/Provider";
import { TextField as SolidSpectrumTextField } from "@proyecto-viviana/solid-spectrum/TextField";
import { s2ButtonText } from "../../../../../../../packages/solid-spectrum/src/button/s2-button-styles";
import {
  formDemoPropsFromWindow,
  normalizeFormDemoProps,
  serializeFormDemoProps,
  type FormDemoProps,
  comparisonControlsEvent,
} from "@comparison/data/form-demo";
import {
  comparisonThemeChangeEvent,
  getComparisonResolvedThemeFromDocument,
  type ComparisonResolvedTheme,
} from "@comparison/data/theme";
import { providerShellStyle } from "../styled-shared.tsx";

function SolidSpectrumFormDemo() {
  const [demoProps, setDemoProps] = createSignal<FormDemoProps>(formDemoPropsFromWindow());
  const [value, setValue] = createSignal(demoProps().value);
  const [colorScheme, setColorScheme] = createSignal<ComparisonResolvedTheme>(
    getComparisonResolvedThemeFromDocument(),
  );

  onMount(() => {
    const handleControlsChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.component === "form") {
        const nextProps = normalizeFormDemoProps(event.detail.props ?? {});
        setDemoProps(nextProps);
        setValue(nextProps.value);
      }
    };
    const handleThemeChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.resolvedTheme) {
        setColorScheme(event.detail.resolvedTheme as ComparisonResolvedTheme);
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    window.addEventListener(comparisonThemeChangeEvent, handleThemeChange);
    setColorScheme(getComparisonResolvedThemeFromDocument());
    onCleanup(() => {
      window.removeEventListener(comparisonControlsEvent, handleControlsChange);
      window.removeEventListener(comparisonThemeChangeEvent, handleThemeChange);
    });
  });

  const serializedProps = createMemo(() =>
    serializeFormDemoProps({
      ...demoProps(),
      value: value(),
    }),
  );

  return hc(
    SolidSpectrumProvider,
    {
      get colorScheme() {
        return colorScheme();
      },
      background: "base",
      style: providerShellStyle,
    },
    [
      hc(
        "div",
        {
          class: "comparison-form-row",
          get "data-comparison-color-scheme"() {
            return colorScheme();
          },
        },
        [
          hc(
            SolidSpectrumForm,
            {
              "data-comparison-control-root": "form",
              get "data-comparison-control-props"() {
                return serializedProps();
              },
              get "data-comparison-value"() {
                return value();
              },
              get size() {
                return demoProps().size;
              },
              get labelPosition() {
                return demoProps().labelPosition;
              },
              get labelAlign() {
                return demoProps().labelAlign;
              },
              get necessityIndicator() {
                return demoProps().necessityIndicator;
              },
              get validationBehavior() {
                return demoProps().validationBehavior;
              },
              get isRequired() {
                return demoProps().isRequired;
              },
              get isDisabled() {
                return demoProps().isDisabled;
              },
              get isEmphasized() {
                return demoProps().isEmphasized;
              },
              onSubmit: (event: SubmitEvent) => event.preventDefault(),
            },
            [
              hc(SolidSpectrumTextField, {
                "data-comparison-form-field": "name",
                get label() {
                  return demoProps().label;
                },
                name: "name",
                get value() {
                  return value();
                },
                description: "Inherited from the parent form.",
                onInput: (event: InputEvent & { currentTarget: HTMLInputElement }) => {
                  const nextValue = event.currentTarget.value;
                  setValue(nextValue);
                  setDemoProps((current: FormDemoProps) => ({
                    ...current,
                    value: nextValue,
                  }));
                },
                onChange: (nextValue: string) => {
                  setValue(nextValue);
                  setDemoProps((current: FormDemoProps) => ({
                    ...current,
                    value: nextValue,
                  }));
                },
              }),
              hc(
                SolidSpectrumButton,
                {
                  "data-comparison-form-submit": "true",
                  type: "submit",
                },
                [
                  () =>
                    h(
                      "span",
                      {
                        class: s2ButtonText({ isProgressVisible: false }),
                        "data-rsp-slot": "text",
                      },
                      demoProps().actionLabel,
                    ),
                ],
              ),
            ],
          ),
        ],
      ),
    ],
  );
}

export default () => h(SolidSpectrumFormDemo, {});

// apps/comparison/src/components/react/fixtures/styled/form.js
import { jsx, jsxs } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import {
  Button as SpectrumButton,
  Form as SpectrumForm,
  TextField as SpectrumTextField,
} from "@react-spectrum/s2";
import {
  formDemoPropsFromWindow,
  normalizeFormDemoProps,
  serializeFormDemoProps,
  comparisonControlsEvent,
} from "@comparison/data/form-demo";
import { useComparisonResolvedTheme, renderReactSpectrumReference } from "../styled-shared.js";

function ReactFormDemo() {
  const [demoProps, setDemoProps] = useState(formDemoPropsFromWindow);
  const [value, setValue] = useState(() => demoProps.value);
  const colorScheme = useComparisonResolvedTheme();

  useEffect(() => {
    const handleControlsChange = (event) => {
      if (event instanceof CustomEvent && event.detail?.component === "form") {
        const nextProps = normalizeFormDemoProps(event.detail.props ?? {});
        setDemoProps(nextProps);
        setValue(nextProps.value);
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    return () => window.removeEventListener(comparisonControlsEvent, handleControlsChange);
  }, []);

  return renderReactSpectrumReference(
    jsx("div", {
      className: "comparison-form-row",
      children: jsxs(SpectrumForm, {
        "data-comparison-control-root": "form",
        "data-comparison-control-props": serializeFormDemoProps({
          ...demoProps,
          value,
        }),
        "data-comparison-value": value,
        size: demoProps.size,
        labelPosition: demoProps.labelPosition,
        labelAlign: demoProps.labelAlign,
        necessityIndicator: demoProps.necessityIndicator,
        validationBehavior: demoProps.validationBehavior,
        isRequired: demoProps.isRequired,
        isDisabled: demoProps.isDisabled,
        isEmphasized: demoProps.isEmphasized,
        onSubmit: (event) => event.preventDefault(),
        children: [
          jsx(SpectrumTextField, {
            "data-comparison-form-field": "name",
            label: demoProps.label,
            name: "name",
            value,
            description: "Inherited from the parent form.",
            onChange: (nextValue) => {
              setValue(nextValue);
              setDemoProps((current) => ({ ...current, value: nextValue }));
            },
          }),
          jsx(SpectrumButton, {
            "data-comparison-form-submit": "true",
            type: "submit",
            children: demoProps.actionLabel,
          }),
        ],
      }),
    }),
    colorScheme,
  );
}

export default () => jsx(ReactFormDemo, {});
