// apps/comparison/src/components/solid/fixtures/styled/link.tsx
import h from "@solidjs/h";
import { createSignal, onSettled } from "solid-js";
import { hc } from "../../solid-h";
import { Link as SolidSpectrumLink } from "@proyecto-viviana/solid-spectrum/Link";
import { Provider as SolidSpectrumProvider } from "@proyecto-viviana/solid-spectrum/Provider";
import {
  linkDemoPropsFromWindow,
  normalizeLinkDemoProps,
  serializeLinkDemoProps,
  type LinkDemoProps,
} from "@comparison/data/link-demo";
import { comparisonControlsEvent } from "@comparison/data/button-demo";
import {
  comparisonThemeChangeEvent,
  getComparisonResolvedThemeFromDocument,
  type ComparisonResolvedTheme,
} from "@comparison/data/theme";
import {
  providerShellStyle,
  staticColorBackdropClass,
  staticColorBackdropValue,
} from "../styled-shared.tsx";

function SolidSpectrumLinkDemo() {
  const [colorScheme, setColorScheme] = createSignal<ComparisonResolvedTheme>(
    getComparisonResolvedThemeFromDocument(),
  );
  const [demoProps, setDemoProps] = createSignal<LinkDemoProps>(linkDemoPropsFromWindow());

  onSettled(() => {
    const handleControlsChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.component === "link") {
        setDemoProps(normalizeLinkDemoProps(event.detail.props ?? {}));
      }
    };
    const handleThemeChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.resolvedTheme) {
        setColorScheme(event.detail.resolvedTheme as ComparisonResolvedTheme);
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    window.addEventListener(comparisonThemeChangeEvent, handleThemeChange);
    setColorScheme(getComparisonResolvedThemeFromDocument());
    return () => {
      window.removeEventListener(comparisonControlsEvent, handleControlsChange);
      window.removeEventListener(comparisonThemeChangeEvent, handleThemeChange);
    };
  });

  const renderedLink = hc(
    SolidSpectrumLink,
    {
      "data-comparison-control-root": "link",
      get "data-comparison-control-props"() {
        return serializeLinkDemoProps(demoProps());
      },
      get href() {
        return demoProps().href;
      },
      get variant() {
        return demoProps().variant;
      },
      get staticColor() {
        return demoProps().staticColor;
      },
      get isStandalone() {
        return demoProps().isStandalone;
      },
      get isQuiet() {
        return demoProps().isQuiet;
      },
    },
    [() => demoProps().children],
  );

  return hc(
    SolidSpectrumProvider,
    {
      get colorScheme() {
        return colorScheme();
      },
      background: "base",
      style: providerShellStyle,
    },
    [
      hc(
        "p",
        {
          get class() {
            return staticColorBackdropClass(demoProps().staticColor, "comparison-link-row");
          },
          get "data-comparison-static-color"() {
            return staticColorBackdropValue(demoProps().staticColor);
          },
          get "data-comparison-color-scheme"() {
            return colorScheme();
          },
        },
        [renderedLink],
      ),
    ],
  );
}

export default () => h(SolidSpectrumLinkDemo, {});

// apps/comparison/src/components/react/fixtures/styled/link.js
import { jsx } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import { Link as SpectrumLink } from "@react-spectrum/s2";
import {
  linkDemoPropsFromWindow,
  normalizeLinkDemoProps,
  serializeLinkDemoProps,
} from "@comparison/data/link-demo";
import { comparisonControlsEvent } from "@comparison/data/button-demo";
import {
  useComparisonResolvedTheme,
  renderReactSpectrumReference,
  staticColorBackdropProps,
} from "../styled-shared.js";

function ReactLinkDemo() {
  const colorScheme = useComparisonResolvedTheme();
  const [demoProps, setDemoProps] = useState(linkDemoPropsFromWindow);
  useEffect(() => {
    const handleControlsChange = (event) => {
      if (event instanceof CustomEvent && event.detail?.component === "link") {
        setDemoProps(normalizeLinkDemoProps(event.detail.props ?? {}));
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    return () => window.removeEventListener(comparisonControlsEvent, handleControlsChange);
  }, []);

  return renderReactSpectrumReference(
    jsx("p", {
      ...staticColorBackdropProps(demoProps.staticColor, "comparison-link-row"),
      children: jsx(SpectrumLink, {
        "data-comparison-control-root": "link",
        "data-comparison-control-props": serializeLinkDemoProps(demoProps),
        href: demoProps.href,
        variant: demoProps.variant,
        staticColor: demoProps.staticColor,
        isStandalone: demoProps.isStandalone,
        isQuiet: demoProps.isQuiet,
        children: demoProps.children,
      }),
    }),
    colorScheme,
  );
}

export default () => jsx(ReactLinkDemo, {});
