// apps/comparison/src/components/solid/fixtures/styled/meter.tsx
import h from "@solidjs/h";
import { createSignal, onSettled } from "solid-js";
import { hc } from "../../solid-h";
import { Meter as SolidSpectrumMeter } from "@proyecto-viviana/solid-spectrum/Meter";
import { Provider as SolidSpectrumProvider } from "@proyecto-viviana/solid-spectrum/Provider";
import {
  meterDemoPropsFromWindow,
  normalizeMeterDemoProps,
  serializeMeterDemoProps,
  type MeterDemoProps,
} from "@comparison/data/meter-demo";
import { comparisonControlsEvent } from "@comparison/data/button-demo";
import {
  comparisonThemeChangeEvent,
  getComparisonResolvedThemeFromDocument,
  type ComparisonResolvedTheme,
} from "@comparison/data/theme";
import {
  providerShellStyle,
  staticColorBackdropClass,
  staticColorBackdropValue,
} from "../styled-shared.tsx";

function SolidSpectrumMeterDemo() {
  const [demoProps, setDemoProps] = createSignal<MeterDemoProps>(meterDemoPropsFromWindow());
  const [colorScheme, setColorScheme] = createSignal<ComparisonResolvedTheme>(
    getComparisonResolvedThemeFromDocument(),
  );

  onSettled(() => {
    const handleControlsChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.component === "meter") {
        setDemoProps(normalizeMeterDemoProps(event.detail.props ?? {}));
      }
    };
    const handleThemeChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.resolvedTheme) {
        setColorScheme(event.detail.resolvedTheme as ComparisonResolvedTheme);
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    window.addEventListener(comparisonThemeChangeEvent, handleThemeChange);
    setColorScheme(getComparisonResolvedThemeFromDocument());
    return () => {
      window.removeEventListener(comparisonControlsEvent, handleControlsChange);
      window.removeEventListener(comparisonThemeChangeEvent, handleThemeChange);
    };
  });

  const renderedMeter = h(SolidSpectrumMeter, {
    "data-comparison-control-root": "meter",
    get "data-comparison-control-props"() {
      return serializeMeterDemoProps(demoProps());
    },
    get label() {
      return demoProps().label;
    },
    get value() {
      return demoProps().value;
    },
    get minValue() {
      return demoProps().minValue;
    },
    get maxValue() {
      return demoProps().maxValue;
    },
    get valueLabel() {
      return demoProps().valueLabel || undefined;
    },
    get variant() {
      return demoProps().variant;
    },
    get size() {
      return demoProps().size;
    },
    get staticColor() {
      return demoProps().staticColor || undefined;
    },
    get labelPosition() {
      return demoProps().labelPosition;
    },
  });

  return hc(
    SolidSpectrumProvider,
    {
      get colorScheme() {
        return colorScheme();
      },
      background: "base",
      style: providerShellStyle,
    },
    [
      hc(
        "div",
        {
          get class() {
            return staticColorBackdropClass(demoProps().staticColor, "comparison-meter-row");
          },
          get "data-comparison-static-color"() {
            return staticColorBackdropValue(demoProps().staticColor);
          },
          get "data-comparison-color-scheme"() {
            return colorScheme();
          },
        },
        [renderedMeter],
      ),
    ],
  );
}

export default () => h(SolidSpectrumMeterDemo, {});

// apps/comparison/src/components/react/fixtures/styled/meter.js
import { jsx } from "react/jsx-runtime";
import { useEffect, useRef, useState } from "react";
import { Meter as SpectrumMeter } from "@react-spectrum/s2";
import {
  meterDemoPropsFromWindow,
  normalizeMeterDemoProps,
  serializeMeterDemoProps,
} from "@comparison/data/meter-demo";
import { comparisonControlsEvent } from "@comparison/data/button-demo";
import {
  useComparisonResolvedTheme,
  renderReactSpectrumReference,
  staticColorBackdropProps,
} from "../styled-shared.js";

function ReactMeterDemo() {
  const colorScheme = useComparisonResolvedTheme();
  const [demoProps, setDemoProps] = useState(meterDemoPropsFromWindow);
  const meterRef = useRef(null);
  useEffect(() => {
    const handleControlsChange = (event) => {
      if (event instanceof CustomEvent && event.detail?.component === "meter") {
        setDemoProps(normalizeMeterDemoProps(event.detail.props ?? {}));
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    return () => window.removeEventListener(comparisonControlsEvent, handleControlsChange);
  }, []);

  return renderReactSpectrumReference(
    jsx("div", {
      ...staticColorBackdropProps(demoProps.staticColor, "comparison-meter-row"),
      children: jsx(SpectrumMeter, {
        "data-comparison-control-root": "meter",
        "data-comparison-control-props": serializeMeterDemoProps(demoProps),
        label: demoProps.label,
        ref: meterRef,
        value: demoProps.value,
        minValue: demoProps.minValue,
        maxValue: demoProps.maxValue,
        valueLabel: demoProps.valueLabel || undefined,
        variant: demoProps.variant,
        size: demoProps.size,
        staticColor: demoProps.staticColor || undefined,
        labelPosition: demoProps.labelPosition,
      }),
    }),
    colorScheme,
  );
}

export default () => jsx(ReactMeterDemo, {});
