// apps/comparison/src/components/solid/fixtures/styled/provider.tsx
import h from "@solidjs/h";
import { createSignal, onSettled } from "solid-js";
import { hc } from "../../solid-h";
import { Button as SolidSpectrumButton } from "@proyecto-viviana/solid-spectrum/Button";
import { Provider as SolidSpectrumProvider } from "@proyecto-viviana/solid-spectrum/Provider";
import {
  normalizeProviderDemoProps,
  providerDemoPropsFromWindow,
  serializeProviderDemoProps,
  type ProviderDemoProps,
} from "@comparison/data/provider-demo";
import { comparisonControlsEvent } from "@comparison/data/button-demo";
import { providerShellStyle } from "../styled-shared.tsx";

function SolidSpectrumProviderDemo() {
  const [demoProps, setDemoProps] = createSignal<ProviderDemoProps>(providerDemoPropsFromWindow());

  onSettled(() => {
    const handleControlsChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.component === "provider") {
        setDemoProps(normalizeProviderDemoProps(event.detail.props ?? {}));
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    return () => window.removeEventListener(comparisonControlsEvent, handleControlsChange);
  });

  return hc(
    SolidSpectrumProvider,
    {
      "data-comparison-control-root": "provider",
      get "data-comparison-control-props"() {
        return serializeProviderDemoProps(demoProps());
      },
      get colorScheme() {
        return demoProps().colorScheme;
      },
      get background() {
        return demoProps().background;
      },
      style: providerShellStyle,
    },
    [
      hc("div", { class: "comparison-provider-stack" }, [
        hc(
          "div",
          {
            class: "comparison-provider-caption",
            get "data-comparison-caption-scheme"() {
              return demoProps().colorScheme;
            },
          },
          [() => `Outer provider: ${demoProps().colorScheme} / ${demoProps().background}`],
        ),
        h(SolidSpectrumButton, { variant: "primary" }, "Inherited Action"),
        h(
          SolidSpectrumProvider,
          { colorScheme: "light", background: "base", style: nestedProviderStyle },
          h(
            "div",
            {
              class: "comparison-provider-caption",
              "data-comparison-caption-scheme": "light",
            },
            "Nested provider: local light override",
          ),
          h(SolidSpectrumButton, { variant: "accent" }, "Nested Override"),
        ),
      ]),
    ],
  );
}

const nestedProviderStyle = {
  padding: "16px",
  margin: "16px 0 0",
  "border-radius": "16px",
};

export default () => h(SolidSpectrumProviderDemo, {});

// apps/comparison/src/components/react/fixtures/styled/provider.js
import { jsx, jsxs } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import { Button as SpectrumButton, Provider as SpectrumProvider } from "@react-spectrum/s2";
import {
  normalizeProviderDemoProps,
  providerDemoPropsFromWindow,
  serializeProviderDemoProps,
} from "@comparison/data/provider-demo";
import { comparisonControlsEvent } from "@comparison/data/button-demo";
import { providerShellStyle } from "../styled-shared.js";

function ReactProviderDemo() {
  const [demoProps, setDemoProps] = useState(providerDemoPropsFromWindow);
  useEffect(() => {
    const handleControlsChange = (event) => {
      if (event instanceof CustomEvent && event.detail?.component === "provider") {
        setDemoProps(normalizeProviderDemoProps(event.detail.props ?? {}));
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    return () => window.removeEventListener(comparisonControlsEvent, handleControlsChange);
  }, []);

  return jsx(SpectrumProvider, {
    "data-comparison-control-root": "provider",
    "data-comparison-control-props": serializeProviderDemoProps(demoProps),
    colorScheme: demoProps.colorScheme,
    background: demoProps.background,
    UNSAFE_style: providerShellStyle,
    children: jsxs("div", {
      className: "comparison-provider-stack",
      children: [
        jsx("div", {
          className: "comparison-provider-caption",
          "data-comparison-caption-scheme": demoProps.colorScheme,
          children: `Outer provider: ${demoProps.colorScheme} / ${demoProps.background}`,
        }),
        jsx(SpectrumButton, {
          variant: "primary",
          children: "Inherited Action",
        }),
        jsxs(SpectrumProvider, {
          colorScheme: "light",
          background: "base",
          UNSAFE_style: nestedProviderStyle,
          children: [
            jsx("div", {
              className: "comparison-provider-caption",
              "data-comparison-caption-scheme": "light",
              children: "Nested provider: local light override",
            }),
            jsx(SpectrumButton, {
              variant: "accent",
              children: "Nested Override",
            }),
          ],
        }),
      ],
    }),
  });
}

const nestedProviderStyle = {
  padding: 16,
  marginTop: 16,
  borderRadius: 16,
};

export default () => jsx(ReactProviderDemo, {});
