// apps/comparison/src/components/solid/fixtures/styled/radiogroup.tsx
import h from "@solidjs/h";
import { createMemo, createSignal, onSettled } from "solid-js";
import { hc } from "../../solid-h";
import { Content as SolidSpectrumContent } from "@proyecto-viviana/solid-spectrum/Content";
import { ContextualHelp as SolidSpectrumContextualHelp } from "@proyecto-viviana/solid-spectrum/ContextualHelp";
import { Heading as SolidSpectrumHeading } from "@proyecto-viviana/solid-spectrum/Heading";
import { Provider as SolidSpectrumProvider } from "@proyecto-viviana/solid-spectrum/Provider";
import {
  Radio as SolidSpectrumRadio,
  RadioGroup as SolidSpectrumRadioGroup,
} from "@proyecto-viviana/solid-spectrum/RadioGroup";
import {
  normalizeRadioGroupDemoProps,
  radioGroupDemoPropsFromWindow,
  serializeRadioGroupDemoProps,
  type RadioGroupDemoProps,
  comparisonControlsEvent,
} from "@comparison/data/radiogroup-demo";
import {
  comparisonThemeChangeEvent,
  getComparisonResolvedThemeFromDocument,
  type ComparisonResolvedTheme,
} from "@comparison/data/theme";
import { providerShellStyle } from "../styled-shared.tsx";

const radioGroupItems = [
  { value: "starter", label: "Starter" },
  { value: "pro", label: "Pro" },
  { value: "enterprise", label: "Enterprise" },
];

function SolidSpectrumRadioGroupDemo() {
  const [demoProps, setDemoProps] = createSignal<RadioGroupDemoProps>(
    radioGroupDemoPropsFromWindow(),
  );
  const [value, setValue] = createSignal(demoProps().selectedValue);
  const [colorScheme, setColorScheme] = createSignal<ComparisonResolvedTheme>(
    getComparisonResolvedThemeFromDocument(),
  );

  onSettled(() => {
    const handleControlsChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.component === "radiogroup") {
        const nextProps = normalizeRadioGroupDemoProps(event.detail.props ?? {});
        setDemoProps(nextProps);
        setValue(nextProps.selectedValue);
      }
    };
    const handleThemeChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.resolvedTheme) {
        setColorScheme(event.detail.resolvedTheme as ComparisonResolvedTheme);
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    window.addEventListener(comparisonThemeChangeEvent, handleThemeChange);
    setColorScheme(getComparisonResolvedThemeFromDocument());
    return () => {
      window.removeEventListener(comparisonControlsEvent, handleControlsChange);
      window.removeEventListener(comparisonThemeChangeEvent, handleThemeChange);
    };
  });

  const serializedProps = createMemo(() =>
    serializeRadioGroupDemoProps({
      ...demoProps(),
      selectedValue: value(),
    }),
  );
  const contextualHelp = createMemo(() =>
    demoProps().withContextualHelp
      ? hc(SolidSpectrumContextualHelp, {}, [
          hc(SolidSpectrumHeading, { slot: "title" }, ["Plan help"]),
          hc(SolidSpectrumContent, {}, ["Choose the plan that matches this workspace."]),
        ])
      : undefined,
  );

  return hc(
    SolidSpectrumProvider,
    {
      get colorScheme() {
        return colorScheme();
      },
      background: "base",
      style: providerShellStyle,
    },
    [
      hc(
        "div",
        {
          get "data-comparison-color-scheme"() {
            return colorScheme();
          },
          get "data-comparison-selected-value"() {
            return value();
          },
          "data-comparison-control-root": "radiogroup",
          get "data-comparison-control-props"() {
            return serializedProps();
          },
        },
        [
          hc(
            SolidSpectrumRadioGroup,
            {
              get label() {
                return demoProps().label;
              },
              get value() {
                return value();
              },
              get size() {
                return demoProps().size;
              },
              get orientation() {
                return demoProps().orientation;
              },
              get labelPosition() {
                return demoProps().labelPosition;
              },
              get labelAlign() {
                return demoProps().labelAlign;
              },
              get necessityIndicator() {
                return demoProps().necessityIndicator;
              },
              get name() {
                return demoProps().name || undefined;
              },
              get form() {
                return demoProps().form || undefined;
              },
              get validationBehavior() {
                return demoProps().validationBehavior || undefined;
              },
              get description() {
                return demoProps().description;
              },
              get errorMessage() {
                return demoProps().errorMessage;
              },
              get contextualHelp() {
                return contextualHelp();
              },
              get isEmphasized() {
                return demoProps().isEmphasized;
              },
              get isDisabled() {
                return demoProps().isDisabled;
              },
              get isReadOnly() {
                return demoProps().isReadOnly;
              },
              get isRequired() {
                return demoProps().isRequired;
              },
              get isInvalid() {
                return demoProps().isInvalid;
              },
              onChange: (nextValue: string) => {
                setValue(nextValue);
                setDemoProps((current: RadioGroupDemoProps) => ({
                  ...current,
                  selectedValue: nextValue,
                }));
              },
            },
            radioGroupItems.map((item) =>
              hc(SolidSpectrumRadio, { value: item.value }, [item.label]),
            ),
          ),
        ],
      ),
    ],
  );
}

export default () => h(SolidSpectrumRadioGroupDemo, {});

// apps/comparison/src/components/react/fixtures/styled/radiogroup.js
import { jsx, jsxs } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import {
  ContextualHelp as SpectrumContextualHelp,
  Content as SpectrumContent,
  Heading as SpectrumHeading,
  Radio as SpectrumRadio,
  RadioGroup as SpectrumRadioGroup,
} from "@react-spectrum/s2";
import {
  normalizeRadioGroupDemoProps,
  radioGroupDemoPropsFromWindow,
  serializeRadioGroupDemoProps,
  comparisonControlsEvent,
} from "@comparison/data/radiogroup-demo";
import { useComparisonResolvedTheme, renderReactSpectrumReference } from "../styled-shared.js";

const radioGroupItems = [
  { value: "starter", label: "Starter" },
  { value: "pro", label: "Pro" },
  { value: "enterprise", label: "Enterprise" },
];

function ReactRadioGroupDemo() {
  const [demoProps, setDemoProps] = useState(radioGroupDemoPropsFromWindow);
  const [value, setValue] = useState(() => demoProps.selectedValue);
  const colorScheme = useComparisonResolvedTheme();
  useEffect(() => {
    const handleControlsChange = (event) => {
      if (event instanceof CustomEvent && event.detail?.component === "radiogroup") {
        const nextProps = normalizeRadioGroupDemoProps(event.detail.props ?? {});
        setDemoProps(nextProps);
        setValue(nextProps.selectedValue);
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    return () => window.removeEventListener(comparisonControlsEvent, handleControlsChange);
  }, []);

  return renderReactSpectrumReference(
    jsx("div", {
      "data-comparison-selected-value": value,
      "data-comparison-control-root": "radiogroup",
      "data-comparison-control-props": serializeRadioGroupDemoProps({
        ...demoProps,
        selectedValue: value,
      }),
      children: jsx(SpectrumRadioGroup, {
        label: demoProps.label,
        value,
        size: demoProps.size,
        orientation: demoProps.orientation,
        labelPosition: demoProps.labelPosition,
        labelAlign: demoProps.labelAlign,
        necessityIndicator: demoProps.necessityIndicator,
        name: demoProps.name || undefined,
        form: demoProps.form || undefined,
        validationBehavior: demoProps.validationBehavior || undefined,
        description: demoProps.description,
        errorMessage: demoProps.errorMessage,
        contextualHelp: demoProps.withContextualHelp
          ? jsxs(SpectrumContextualHelp, {
              children: [
                jsx(SpectrumHeading, { children: "Plan help" }),
                jsx(SpectrumContent, { children: "Choose the plan that matches this workspace." }),
              ],
            })
          : undefined,
        isEmphasized: demoProps.isEmphasized,
        isDisabled: demoProps.isDisabled,
        isReadOnly: demoProps.isReadOnly,
        isRequired: demoProps.isRequired,
        isInvalid: demoProps.isInvalid,
        onChange: (nextValue) => {
          setValue(nextValue);
          setDemoProps((current) => ({ ...current, selectedValue: nextValue }));
        },
        children: radioGroupItems.map((item) =>
          jsx(SpectrumRadio, { value: item.value, children: item.label }, item.value),
        ),
      }),
    }),
    colorScheme,
  );
}

export default () => jsx(ReactRadioGroupDemo, {});
