// apps/comparison/src/components/solid/fixtures/styled/rangeslider.tsx
import h from "solid-js/h";
import { createMemo, createSignal, onCleanup, onMount } from "solid-js";
import { hc } from "../../solid-h";
import { ContextualHelp as SolidSpectrumContextualHelp } from "@proyecto-viviana/solid-spectrum/ContextualHelp";
import { Heading as SolidSpectrumHeading } from "@proyecto-viviana/solid-spectrum/Heading";
import { Provider as SolidSpectrumProvider } from "@proyecto-viviana/solid-spectrum/Provider";
import { RangeSlider as SolidSpectrumRangeSlider } from "@proyecto-viviana/solid-spectrum/RangeSlider";
import { Text as SolidSpectrumText } from "@proyecto-viviana/solid-spectrum/Text";
import {
  initialRangeSliderDemoValue,
  normalizeRangeSliderDemoProps,
  rangeSliderDemoPropsFromWindow,
  rangeSliderFormatOptionsForPreset,
  serializeRangeSliderDemoProps,
  type RangeSliderDemoProps,
  comparisonControlsEvent,
} from "@comparison/data/rangeslider-demo";
import {
  comparisonThemeChangeEvent,
  getComparisonResolvedThemeFromDocument,
  type ComparisonResolvedTheme,
} from "@comparison/data/theme";
import { providerShellStyle } from "../styled-shared.tsx";

function SolidSpectrumRangeSliderDemo() {
  const [demoProps, setDemoProps] = createSignal<RangeSliderDemoProps>(
    rangeSliderDemoPropsFromWindow(),
  );
  const [value, setValue] = createSignal(initialRangeSliderDemoValue(demoProps()));
  const [colorScheme, setColorScheme] = createSignal<ComparisonResolvedTheme>(
    getComparisonResolvedThemeFromDocument(),
  );

  onMount(() => {
    const handleControlsChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.component === "rangeslider") {
        const nextProps = normalizeRangeSliderDemoProps(event.detail.props ?? {});
        setDemoProps(nextProps);
        setValue(initialRangeSliderDemoValue(nextProps));
      }
    };
    const handleThemeChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.resolvedTheme) {
        setColorScheme(event.detail.resolvedTheme as ComparisonResolvedTheme);
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    window.addEventListener(comparisonThemeChangeEvent, handleThemeChange);
    setColorScheme(getComparisonResolvedThemeFromDocument());
    onCleanup(() => {
      window.removeEventListener(comparisonControlsEvent, handleControlsChange);
      window.removeEventListener(comparisonThemeChangeEvent, handleThemeChange);
    });
  });

  const serializedProps = createMemo(() => serializeRangeSliderDemoProps(demoProps()));

  return hc(
    SolidSpectrumProvider,
    {
      get colorScheme() {
        return colorScheme();
      },
      background: "base",
      style: providerShellStyle,
    },
    [
      hc(
        "div",
        {
          style: rangeSliderStackStyle,
          "data-comparison-control-root": "rangeslider",
          get "data-comparison-color-scheme"() {
            return colorScheme();
          },
          get "data-comparison-control-props"() {
            return serializedProps();
          },
          get "data-comparison-value"() {
            const currentValue = value();
            return `${currentValue.start}:${currentValue.end}`;
          },
        },
        [
          hc(SolidSpectrumRangeSlider, {
            get label() {
              return demoProps().label;
            },
            get value() {
              return demoProps().valueSource === "value" ? value() : undefined;
            },
            get defaultValue() {
              return demoProps().valueSource === "defaultValue"
                ? {
                    start: demoProps().defaultStartValue,
                    end: demoProps().defaultEndValue,
                  }
                : undefined;
            },
            get minValue() {
              return demoProps().minValue;
            },
            get maxValue() {
              return demoProps().maxValue;
            },
            get step() {
              return demoProps().step;
            },
            get size() {
              return demoProps().size;
            },
            get trackStyle() {
              return demoProps().trackStyle;
            },
            get thumbStyle() {
              return demoProps().thumbStyle;
            },
            get labelPosition() {
              return demoProps().labelPosition;
            },
            get labelAlign() {
              return demoProps().labelAlign;
            },
            get formatOptions() {
              return rangeSliderFormatOptionsForPreset(demoProps().formatOptions);
            },
            get contextualHelp() {
              return demoProps().withContextualHelp
                ? hc(SolidSpectrumContextualHelp, {}, [
                    hc(SolidSpectrumHeading, { slot: "title" }, ["Range help"]),
                    hc(SolidSpectrumText, {}, ["Choose minimum and maximum values."]),
                  ])
                : undefined;
            },
            get startName() {
              return demoProps().startName || undefined;
            },
            get endName() {
              return demoProps().endName || undefined;
            },
            get form() {
              return demoProps().form || undefined;
            },
            get isEmphasized() {
              return demoProps().isEmphasized;
            },
            get isDisabled() {
              return demoProps().isDisabled;
            },
            onChange: (nextValue: { start: number; end: number }) => {
              setValue(nextValue);
              setDemoProps((current: RangeSliderDemoProps) =>
                current.valueSource === "value"
                  ? normalizeRangeSliderDemoProps({
                      ...current,
                      startValue: nextValue.start,
                      endValue: nextValue.end,
                    })
                  : current,
              );
            },
            "data-comparison-rangeslider": "modeled",
          }),
        ],
      ),
    ],
  );
}

const rangeSliderStackStyle = {
  display: "flex",
  "flex-direction": "column",
  gap: "28px",
  width: "420px",
  padding: "12px",
};

export default () => h(SolidSpectrumRangeSliderDemo, {});

// apps/comparison/src/components/react/fixtures/styled/rangeslider.js
import { jsx, jsxs } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import {
  ContextualHelp as SpectrumContextualHelp,
  Content as SpectrumContent,
  Heading as SpectrumHeading,
  RangeSlider as SpectrumRangeSlider,
} from "@react-spectrum/s2";
import {
  initialRangeSliderDemoValue,
  normalizeRangeSliderDemoProps,
  rangeSliderDemoPropsFromWindow,
  rangeSliderFormatOptionsForPreset,
  serializeRangeSliderDemoProps,
  comparisonControlsEvent,
} from "@comparison/data/rangeslider-demo";
import { useComparisonResolvedTheme, renderReactSpectrumReference } from "../styled-shared.js";

function ReactRangeSliderDemo() {
  const [demoProps, setDemoProps] = useState(rangeSliderDemoPropsFromWindow);
  const [value, setValue] = useState(() => initialRangeSliderDemoValue(demoProps));
  const colorScheme = useComparisonResolvedTheme();

  useEffect(() => {
    const handleControlsChange = (event) => {
      if (event instanceof CustomEvent && event.detail?.component === "rangeslider") {
        const nextProps = normalizeRangeSliderDemoProps(event.detail.props ?? {});
        setDemoProps(nextProps);
        setValue(initialRangeSliderDemoValue(nextProps));
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    return () => window.removeEventListener(comparisonControlsEvent, handleControlsChange);
  }, []);

  const valueProps =
    demoProps.valueSource === "defaultValue"
      ? {
          defaultValue: {
            start: demoProps.defaultStartValue,
            end: demoProps.defaultEndValue,
          },
        }
      : { value };
  const renderKey = [
    demoProps.valueSource,
    demoProps.defaultStartValue,
    demoProps.defaultEndValue,
    demoProps.minValue,
    demoProps.maxValue,
    demoProps.step,
    demoProps.labelPosition,
    demoProps.labelAlign,
    demoProps.startName,
    demoProps.endName,
    demoProps.form,
    demoProps.withContextualHelp,
    demoProps.formatOptions,
  ].join("|");

  return renderReactSpectrumReference(
    jsx("div", {
      style: rangeSliderStackStyle,
      "data-comparison-control-root": "rangeslider",
      "data-comparison-control-props": serializeRangeSliderDemoProps(demoProps),
      "data-comparison-value": `${value.start}:${value.end}`,
      children: jsx(
        SpectrumRangeSlider,
        {
          label: demoProps.label,
          ...valueProps,
          minValue: demoProps.minValue,
          maxValue: demoProps.maxValue,
          step: demoProps.step,
          size: demoProps.size,
          trackStyle: demoProps.trackStyle,
          thumbStyle: demoProps.thumbStyle,
          labelPosition: demoProps.labelPosition,
          labelAlign: demoProps.labelAlign,
          formatOptions: rangeSliderFormatOptionsForPreset(demoProps.formatOptions),
          contextualHelp: demoProps.withContextualHelp
            ? jsxs(SpectrumContextualHelp, {
                children: [
                  jsx(SpectrumHeading, { children: "Range help" }),
                  jsx(SpectrumContent, { children: "Choose minimum and maximum values." }),
                ],
              })
            : undefined,
          startName: demoProps.startName || undefined,
          endName: demoProps.endName || undefined,
          form: demoProps.form || undefined,
          isEmphasized: demoProps.isEmphasized,
          isDisabled: demoProps.isDisabled,
          onChange: (nextValue) => {
            setValue(nextValue);
            setDemoProps((current) =>
              current.valueSource === "value"
                ? normalizeRangeSliderDemoProps({
                    ...current,
                    startValue: nextValue.start,
                    endValue: nextValue.end,
                  })
                : current,
            );
          },
          "data-comparison-rangeslider": "modeled",
        },
        renderKey,
      ),
    }),
    colorScheme,
  );
}

const rangeSliderStackStyle = {
  display: "flex",
  flexDirection: "column",
  gap: 28,
  width: 420,
  padding: 12,
};

export default () => jsx(ReactRangeSliderDemo, {});
