// apps/comparison/src/components/solid/fixtures/styled/selectboxgroup.tsx
import h from "solid-js/h";
import { createEffect, createMemo, createSignal, onCleanup, onMount } from "solid-js";
import { hc, renderProp } from "../../solid-h";
import {
  Provider as SolidSpectrumProvider,
  SelectBox as SolidSpectrumSelectBox,
  SelectBoxGroup as SolidSpectrumSelectBoxGroup,
} from "@proyecto-viviana/solid-spectrum";
import {
  initialSelectBoxGroupSelectedKeys,
  normalizeSelectBoxGroupDemoProps,
  selectBoxGroupDemoPropsFromWindow,
  selectBoxGroupIllustrationItemIds,
  selectBoxGroupItems,
  selectBoxGroupKeysFromValue,
  serializeSelectBoxGroupDemoProps,
  serializeSelectBoxGroupKeys,
  type SelectBoxGroupDemoProps,
  comparisonControlsEvent,
} from "@comparison/data/selectboxgroup-demo";
import {
  comparisonThemeChangeEvent,
  getComparisonResolvedThemeFromDocument,
  type ComparisonResolvedTheme,
} from "@comparison/data/theme";
import { providerShellStyle, SolidPlanIllustration } from "../styled-shared.tsx";

function SolidSpectrumSelectBoxGroupDemo() {
  const [demoProps, setDemoProps] = createSignal<SelectBoxGroupDemoProps>(
    selectBoxGroupDemoPropsFromWindow(),
  );
  const [selectedKeys, setSelectedKeys] = createSignal<Set<string>>(
    initialSelectBoxGroupSelectedKeys(demoProps()),
  );
  const [colorScheme, setColorScheme] = createSignal<ComparisonResolvedTheme>(
    getComparisonResolvedThemeFromDocument(),
  );
  const selectedKeyText = createMemo(() => serializeSelectBoxGroupKeys(selectedKeys()));
  let selectBoxGroupRoot: HTMLElement | undefined;

  createEffect(() => {
    selectBoxGroupRoot?.setAttribute(
      "data-comparison-control-props",
      serializeSelectBoxGroupDemoProps(demoProps()),
    );
  });

  onMount(() => {
    const handleControlsChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.component === "selectboxgroup") {
        setDemoProps((current) => {
          const nextProps = normalizeSelectBoxGroupDemoProps({
            ...current,
            ...(event.detail.props ?? {}),
          });
          setSelectedKeys(initialSelectBoxGroupSelectedKeys(nextProps));
          return nextProps;
        });
      }
    };
    const handleThemeChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.resolvedTheme) {
        setColorScheme(event.detail.resolvedTheme as ComparisonResolvedTheme);
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    window.addEventListener(comparisonThemeChangeEvent, handleThemeChange);
    setColorScheme(getComparisonResolvedThemeFromDocument());
    onCleanup(() => {
      window.removeEventListener(comparisonControlsEvent, handleControlsChange);
      window.removeEventListener(comparisonThemeChangeEvent, handleThemeChange);
    });
  });

  return hc(
    SolidSpectrumProvider,
    {
      get colorScheme() {
        return colorScheme();
      },
      background: "base",
      style: providerShellStyle,
    },
    [
      hc(
        "div",
        {
          get "data-comparison-color-scheme"() {
            return colorScheme();
          },
          get "data-comparison-selected-keys"() {
            return selectedKeyText();
          },
        },
        [
          hc(
            SolidSpectrumSelectBoxGroup,
            {
              "aria-label": "Plans",
              "data-comparison-control-root": "selectboxgroup",
              ref: (element: HTMLElement) => {
                selectBoxGroupRoot = element;
              },
              get "data-comparison-control-props"() {
                return serializeSelectBoxGroupDemoProps(demoProps());
              },
              get orientation() {
                return demoProps().orientation;
              },
              get selectionMode() {
                return demoProps().selectionMode;
              },
              get isDisabled() {
                return demoProps().isDisabled;
              },
              get items() {
                return selectBoxGroupItems;
              },
              getKey: (item: (typeof selectBoxGroupItems)[number]) => item.id,
              getTextValue: (item: (typeof selectBoxGroupItems)[number]) => item.label,
              get disabledKeys() {
                return selectBoxGroupKeysFromValue(demoProps().disabledKeys, [], "multiple");
              },
              get selectedKeys() {
                return demoProps().selectionSource === "selectedKeys" ? selectedKeys() : undefined;
              },
              get defaultSelectedKeys() {
                return demoProps().selectionSource === "defaultSelectedKeys"
                  ? selectBoxGroupKeysFromValue(
                      demoProps().defaultSelectedKeys,
                      ["starter"],
                      demoProps().selectionMode,
                    )
                  : undefined;
              },
              onSelectionChange: (keys: "all" | Set<string | number>) =>
                setSelectedKeys(
                  keys === "all"
                    ? new Set(selectBoxGroupItems.map((item) => item.id))
                    : new Set<string>(Array.from(keys, String)),
                ),
            },
            renderProp((item: (typeof selectBoxGroupItems)[number]) =>
              hc(
                SolidSpectrumSelectBox,
                {
                  id: item.id,
                  textValue: item.label,
                  get isDisabled() {
                    return demoProps().disabledItem === item.id;
                  },
                },
                [
                  ...(demoProps().withIllustrations &&
                  selectBoxGroupIllustrationItemIds.has(item.id)
                    ? [
                        hc(SolidPlanIllustration, {
                          slot: "illustration",
                          size: "S",
                          "data-rsp-slot": "illustration",
                        }),
                      ]
                    : []),
                  hc("span", { slot: "label", "data-rsp-slot": "label" }, [item.label]),
                  hc("span", { slot: "description", "data-rsp-slot": "description" }, [
                    item.description,
                  ]),
                ],
              ),
            ),
          ),
        ],
      ),
    ],
  );
}

export default () => h(SolidSpectrumSelectBoxGroupDemo, {});

// apps/comparison/src/components/react/fixtures/styled/selectboxgroup.js
import { jsx, jsxs } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import {
  SelectBox as SpectrumSelectBox,
  SelectBoxGroup as SpectrumSelectBoxGroup,
  Text as SpectrumText,
} from "@react-spectrum/s2";
import {
  initialSelectBoxGroupSelectedKeys,
  normalizeSelectBoxGroupDemoProps,
  selectBoxGroupDemoPropsFromWindow,
  selectBoxGroupIllustrationItemIds,
  selectBoxGroupItems,
  selectBoxGroupKeysFromValue,
  serializeSelectBoxGroupDemoProps,
  serializeSelectBoxGroupKeys,
  comparisonControlsEvent,
} from "@comparison/data/selectboxgroup-demo";
import {
  useComparisonResolvedTheme,
  renderReactSpectrumReference,
  ReactPlanIllustration,
} from "../styled-shared.js";

function ReactSelectBoxGroupDemo() {
  const [demoProps, setDemoProps] = useState(selectBoxGroupDemoPropsFromWindow);
  const [selectedKeys, setSelectedKeys] = useState(() =>
    initialSelectBoxGroupSelectedKeys(demoProps),
  );
  const colorScheme = useComparisonResolvedTheme();
  useEffect(() => {
    const handleControlsChange = (event) => {
      if (event instanceof CustomEvent && event.detail?.component === "selectboxgroup") {
        setDemoProps((current) => {
          const nextProps = normalizeSelectBoxGroupDemoProps({ ...current, ...event.detail.props });
          setSelectedKeys(initialSelectBoxGroupSelectedKeys(nextProps));
          return nextProps;
        });
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    return () => window.removeEventListener(comparisonControlsEvent, handleControlsChange);
  }, []);

  const selectionProps =
    demoProps.selectionSource === "defaultSelectedKeys"
      ? {
          defaultSelectedKeys: selectBoxGroupKeysFromValue(
            demoProps.defaultSelectedKeys,
            ["starter"],
            demoProps.selectionMode,
          ),
        }
      : { selectedKeys };
  const renderKey = [
    demoProps.orientation,
    demoProps.selectionMode,
    demoProps.selectionSource,
    demoProps.selectionSource === "defaultSelectedKeys"
      ? demoProps.defaultSelectedKeys
      : demoProps.selectedKeys,
    demoProps.disabledKeys,
    demoProps.disabledItem,
    demoProps.isDisabled,
    demoProps.withIllustrations,
  ].join("|");

  return renderReactSpectrumReference(
    jsx("div", {
      "data-comparison-selected-keys": serializeSelectBoxGroupKeys(selectedKeys),
      children: jsx(
        SpectrumSelectBoxGroup,
        {
          "aria-label": "Plans",
          "data-comparison-control-root": "selectboxgroup",
          "data-comparison-control-props": serializeSelectBoxGroupDemoProps(demoProps),
          orientation: demoProps.orientation,
          selectionMode: demoProps.selectionMode,
          isDisabled: demoProps.isDisabled,
          disabledKeys: selectBoxGroupKeysFromValue(demoProps.disabledKeys, [], "multiple"),
          ...selectionProps,
          onSelectionChange: (keys) =>
            setSelectedKeys(
              keys === "all" ? new Set(selectBoxGroupItems.map((item) => item.id)) : new Set(keys),
            ),
          children: selectBoxGroupItems.map((item) =>
            jsxs(
              SpectrumSelectBox,
              {
                id: item.id,
                textValue: item.label,
                isDisabled: demoProps.disabledItem === item.id,
                children: [
                  demoProps.withIllustrations && selectBoxGroupIllustrationItemIds.has(item.id)
                    ? jsx(ReactPlanIllustration, { slot: "illustration" })
                    : null,
                  jsx(SpectrumText, { slot: "label", children: item.label }),
                  jsx(SpectrumText, { slot: "description", children: item.description }),
                ],
              },
              item.id,
            ),
          ),
        },
        renderKey,
      ),
    }),
    colorScheme,
  );
}

export default () => jsx(ReactSelectBoxGroupDemo, {});
