// apps/comparison/src/components/solid/fixtures/styled/slider.tsx
import h from "solid-js/h";
import { createMemo, createSignal, onCleanup, onMount } from "solid-js";
import { hc } from "../../solid-h";
import { ContextualHelp as SolidSpectrumContextualHelp } from "@proyecto-viviana/solid-spectrum/ContextualHelp";
import { Heading as SolidSpectrumHeading } from "@proyecto-viviana/solid-spectrum/Heading";
import { Provider as SolidSpectrumProvider } from "@proyecto-viviana/solid-spectrum/Provider";
import { Slider as SolidSpectrumSlider } from "@proyecto-viviana/solid-spectrum/Slider";
import { Text as SolidSpectrumText } from "@proyecto-viviana/solid-spectrum/Text";
import {
  initialSliderDemoValue,
  normalizeSliderDemoProps,
  serializeSliderDemoProps,
  sliderDemoPropsFromWindow,
  type SliderDemoProps,
  comparisonControlsEvent,
} from "@comparison/data/slider-demo";
import {
  comparisonThemeChangeEvent,
  getComparisonResolvedThemeFromDocument,
  type ComparisonResolvedTheme,
} from "@comparison/data/theme";
import { providerShellStyle } from "../styled-shared.tsx";

function SolidSpectrumSliderDemo() {
  const [demoProps, setDemoProps] = createSignal<SliderDemoProps>(sliderDemoPropsFromWindow());
  const [value, setValue] = createSignal(initialSliderDemoValue(demoProps()));
  const [colorScheme, setColorScheme] = createSignal<ComparisonResolvedTheme>(
    getComparisonResolvedThemeFromDocument(),
  );

  onMount(() => {
    const handleControlsChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.component === "slider") {
        const nextProps = normalizeSliderDemoProps(event.detail.props ?? {});
        setDemoProps(nextProps);
        setValue(initialSliderDemoValue(nextProps));
      }
    };
    const handleThemeChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.resolvedTheme) {
        setColorScheme(event.detail.resolvedTheme as ComparisonResolvedTheme);
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    window.addEventListener(comparisonThemeChangeEvent, handleThemeChange);
    setColorScheme(getComparisonResolvedThemeFromDocument());
    onCleanup(() => {
      window.removeEventListener(comparisonControlsEvent, handleControlsChange);
      window.removeEventListener(comparisonThemeChangeEvent, handleThemeChange);
    });
  });

  const serializedProps = createMemo(() => serializeSliderDemoProps(demoProps()));

  return hc(
    SolidSpectrumProvider,
    {
      get colorScheme() {
        return colorScheme();
      },
      background: "base",
      style: providerShellStyle,
    },
    [
      hc(
        "div",
        {
          "data-comparison-control-root": "slider",
          get "data-comparison-color-scheme"() {
            return colorScheme();
          },
          get "data-comparison-control-props"() {
            return serializedProps();
          },
          get "data-comparison-value"() {
            return String(value());
          },
        },
        [
          hc(SolidSpectrumSlider, {
            get label() {
              return demoProps().label;
            },
            get value() {
              return demoProps().valueSource === "value" ? value() : undefined;
            },
            get defaultValue() {
              return demoProps().valueSource === "defaultValue"
                ? demoProps().defaultValue
                : undefined;
            },
            get minValue() {
              return demoProps().minValue;
            },
            get maxValue() {
              return demoProps().maxValue;
            },
            get step() {
              return demoProps().step;
            },
            get size() {
              return demoProps().size;
            },
            get trackStyle() {
              return demoProps().trackStyle;
            },
            get thumbStyle() {
              return demoProps().thumbStyle;
            },
            get fillOffset() {
              return demoProps().fillOffset;
            },
            get labelPosition() {
              return demoProps().labelPosition;
            },
            get labelAlign() {
              return demoProps().labelAlign;
            },
            get contextualHelp() {
              return demoProps().withContextualHelp
                ? hc(SolidSpectrumContextualHelp, {}, [
                    hc(SolidSpectrumHeading, { slot: "title" }, ["Volume help"]),
                    hc(SolidSpectrumText, {}, ["Choose an output level."]),
                  ])
                : undefined;
            },
            get name() {
              return demoProps().name || undefined;
            },
            get form() {
              return demoProps().form || undefined;
            },
            get isEmphasized() {
              return demoProps().isEmphasized;
            },
            get isDisabled() {
              return demoProps().isDisabled;
            },
            onChange: (nextValue: number) => {
              setValue(nextValue);
              setDemoProps((current: SliderDemoProps) =>
                current.valueSource === "value" ? { ...current, value: nextValue } : current,
              );
            },
          }),
        ],
      ),
    ],
  );
}

export default () => h(SolidSpectrumSliderDemo, {});

// apps/comparison/src/components/react/fixtures/styled/slider.js
import { jsx, jsxs } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import {
  ContextualHelp as SpectrumContextualHelp,
  Content as SpectrumContent,
  Heading as SpectrumHeading,
  Slider as SpectrumSlider,
} from "@react-spectrum/s2";
import {
  initialSliderDemoValue,
  normalizeSliderDemoProps,
  serializeSliderDemoProps,
  sliderDemoPropsFromWindow,
  comparisonControlsEvent,
} from "@comparison/data/slider-demo";
import { useComparisonResolvedTheme, renderReactSpectrumReference } from "../styled-shared.js";

function ReactSliderDemo() {
  const [demoProps, setDemoProps] = useState(sliderDemoPropsFromWindow);
  const [value, setValue] = useState(() => initialSliderDemoValue(demoProps));
  const colorScheme = useComparisonResolvedTheme();

  useEffect(() => {
    const handleControlsChange = (event) => {
      if (event instanceof CustomEvent && event.detail?.component === "slider") {
        const nextProps = normalizeSliderDemoProps(event.detail.props ?? {});
        setDemoProps(nextProps);
        setValue(initialSliderDemoValue(nextProps));
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    return () => window.removeEventListener(comparisonControlsEvent, handleControlsChange);
  }, []);
  const valueProps =
    demoProps.valueSource === "defaultValue" ? { defaultValue: demoProps.defaultValue } : { value };
  const renderKey = [
    demoProps.valueSource,
    demoProps.valueSource === "defaultValue" ? demoProps.defaultValue : "controlled",
    demoProps.minValue,
    demoProps.maxValue,
    demoProps.step,
    demoProps.fillOffset,
    demoProps.labelPosition,
    demoProps.labelAlign,
    demoProps.name,
    demoProps.form,
    demoProps.withContextualHelp,
  ].join("|");

  return renderReactSpectrumReference(
    jsx("div", {
      "data-comparison-control-root": "slider",
      "data-comparison-control-props": serializeSliderDemoProps(demoProps),
      "data-comparison-value": String(value),
      children: jsx(
        SpectrumSlider,
        {
          label: demoProps.label,
          ...valueProps,
          minValue: demoProps.minValue,
          maxValue: demoProps.maxValue,
          step: demoProps.step,
          size: demoProps.size,
          trackStyle: demoProps.trackStyle,
          thumbStyle: demoProps.thumbStyle,
          fillOffset: demoProps.fillOffset,
          labelPosition: demoProps.labelPosition,
          labelAlign: demoProps.labelAlign,
          contextualHelp: demoProps.withContextualHelp
            ? jsxs(SpectrumContextualHelp, {
                children: [
                  jsx(SpectrumHeading, { children: "Volume help" }),
                  jsx(SpectrumContent, { children: "Choose an output level." }),
                ],
              })
            : undefined,
          name: demoProps.name || undefined,
          form: demoProps.form || undefined,
          isEmphasized: demoProps.isEmphasized,
          isDisabled: demoProps.isDisabled,
          onChange: (nextValue) => {
            setValue(nextValue);
            setDemoProps((current) =>
              current.valueSource === "value" ? { ...current, value: nextValue } : current,
            );
          },
        },
        renderKey,
      ),
    }),
    colorScheme,
  );
}

export default () => jsx(ReactSliderDemo, {});
