// apps/comparison/src/components/solid/fixtures/styled/steplist.tsx
import h from "solid-js/h";
import { createMemo, createSignal, onCleanup, onMount } from "solid-js";
import { hc } from "../../solid-h";
import { StepList as SolidSpectrumStepList } from "@proyecto-viviana/solid-spectrum/StepList";
import { Provider as SolidSpectrumProvider } from "@proyecto-viviana/solid-spectrum/Provider";
import {
  stepListDemoItems,
  stepListDemoPropsFromWindow,
  stepListKeysFromValue,
  normalizeStepListDemoProps,
  serializeStepListDemoProps,
  type StepListDemoProps,
  comparisonControlsEvent,
} from "@comparison/data/steplist-demo";
import {
  comparisonThemeChangeEvent,
  getComparisonResolvedThemeFromDocument,
  type ComparisonResolvedTheme,
} from "@comparison/data/theme";
import { providerShellStyle } from "../styled-shared.tsx";

// Solid StepList: the solid-spectrum styled StepList over the base
// `createStepList` / `createStepListState` port. The fixed four-step wizard +
// prop-driven completion/selection state pair-diffs against the hand-wired v3
// hooks oracle (React panel). No locale plumbing — D10 is scoped out for
// StepList (see the certified spec).
function SolidSpectrumStepListDemo() {
  const [demoProps, setDemoProps] = createSignal<StepListDemoProps>(stepListDemoPropsFromWindow());
  const [colorScheme, setColorScheme] = createSignal<ComparisonResolvedTheme>(
    getComparisonResolvedThemeFromDocument(),
  );

  onMount(() => {
    const handleControlsChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.component === "steplist") {
        setDemoProps(normalizeStepListDemoProps(event.detail.props ?? {}));
      }
    };
    const handleThemeChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.resolvedTheme) {
        setColorScheme(event.detail.resolvedTheme as ComparisonResolvedTheme);
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    window.addEventListener(comparisonThemeChangeEvent, handleThemeChange);
    setColorScheme(getComparisonResolvedThemeFromDocument());
    onCleanup(() => {
      window.removeEventListener(comparisonControlsEvent, handleControlsChange);
      window.removeEventListener(comparisonThemeChangeEvent, handleThemeChange);
    });
  });

  const renderedStepList = createMemo(() =>
    hc(SolidSpectrumStepList, {
      "aria-label": "Checkout steps",
      items: stepListDemoItems,
      get defaultSelectedKey() {
        return demoProps().defaultSelectedKey || undefined;
      },
      get defaultLastCompletedStep() {
        return demoProps().defaultLastCompletedStep || undefined;
      },
      get disabledKeys() {
        return stepListKeysFromValue(demoProps().disabledKeys);
      },
      get isDisabled() {
        return demoProps().isDisabled;
      },
      get isReadOnly() {
        return demoProps().isReadOnly;
      },
      "data-comparison-control-root": "steplist",
      get "data-comparison-control-props"() {
        return serializeStepListDemoProps(demoProps());
      },
    }),
  );

  return hc(
    SolidSpectrumProvider,
    {
      get colorScheme() {
        return colorScheme();
      },
      background: "base",
      style: providerShellStyle,
    },
    [
      hc("div", { class: "comparison-gridlist-row" }, [
        h("button", {}, "Before"),
        renderedStepList,
        h("button", {}, "After"),
      ]),
    ],
  );
}

export default () => h(SolidSpectrumStepListDemo, {});

// apps/comparison/src/components/react/fixtures/styled/steplist.js
import { jsx, jsxs } from "react/jsx-runtime";
import { Fragment, useEffect, useId, useRef, useState } from "react";
import { useStepList } from "react-aria/private/steplist/useStepList";
import { useStepListItem } from "react-aria/private/steplist/useStepListItem";
import { useStepListState } from "react-stately/private/steplist/useStepListState";
import { Item as StatelyItem } from "react-stately";
import {
  stepListDemoItems,
  stepListDemoPropsFromWindow,
  stepListKeysFromValue,
  normalizeStepListDemoProps,
  serializeStepListDemoProps,
  comparisonControlsEvent,
} from "@comparison/data/steplist-demo";
import { useComparisonResolvedTheme, renderReactSpectrumReference } from "../styled-shared.js";

// Hand-wired v3 StepList oracle: one `useStepListItem` per collection node,
// rendered as an `<a>`. The hook sets NO accessible name — naming is composed by
// the wrapper exactly as the vendored `@adobe/react-spectrum` StepListItem does:
// `aria-labelledby` referencing a marker (step number), a visually-hidden state
// prefix ("Current: " / "Completed: " / "Not completed: "), and the label. Press
// handlers from `useSelectableItem` are DOM props already, so `stepProps` spreads
// whole; the D5/D6 cert never clicks.
function ReactStepListItem({ node, state }) {
  const ref = useRef(null);
  const { stepProps } = useStepListItem({ key: node.key }, state, ref);
  const markerId = useId();
  const stateId = useId();
  const labelId = useId();
  const isSelected = state.selectedKey === node.key;
  const stateText = isSelected
    ? "Current: "
    : state.isCompleted(node.key)
      ? "Completed: "
      : "Not completed: ";
  return jsx("li", {
    children: jsxs("a", {
      ...stepProps,
      ref,
      "aria-labelledby": `${markerId} ${stateId} ${labelId}`,
      children: [
        // Marker + label are aria-hidden; the accessible name is composed only
        // through aria-labelledby (which pierces aria-hidden), mirroring the
        // vendored @adobe/react-spectrum StepListItem (aria-hidden marker wrapper
        // + label div, VisuallyHidden state). This keeps the link from also
        // exposing its raw text content in the AX tree.
        jsx("span", { id: markerId, "aria-hidden": true, children: (node.index ?? 0) + 1 }),
        jsx("span", { id: stateId, children: stateText }),
        jsx("span", { id: labelId, "aria-hidden": true, children: node.rendered }),
      ],
    }),
  });
}

// The hook-calling body. `useStepListState`/`useStepList` run HERE. StepList has
// no localized runtime dependency in this cert (D10 scoped out — see the spec),
// so no I18nProvider is needed; the fixed `aria-label` bypasses the localized
// default name.
function ReactStepListBody({ demoProps, colorScheme }) {
  const ref = useRef(null);
  const listProps = {
    "aria-label": "Checkout steps",
    items: stepListDemoItems,
    children: (item) => jsx(StatelyItem, { children: item.label }, item.key),
    defaultSelectedKey: demoProps.defaultSelectedKey || undefined,
    defaultLastCompletedStep: demoProps.defaultLastCompletedStep || undefined,
    disabledKeys: stepListKeysFromValue(demoProps.disabledKeys),
    isDisabled: demoProps.isDisabled,
    isReadOnly: demoProps.isReadOnly,
    suppressTextValueWarning: true,
  };
  const state = useStepListState(listProps);
  const { listProps: stepListProps } = useStepList(listProps, state, ref);

  return renderReactSpectrumReference(
    jsxs(Fragment, {
      children: [
        jsx("button", { children: "Before" }),
        jsx("ol", {
          ...stepListProps,
          ref,
          "data-comparison-control-root": "steplist",
          "data-comparison-control-props": serializeStepListDemoProps(demoProps),
          children: [...state.collection].map((node) =>
            jsx(ReactStepListItem, { node, state }, node.key),
          ),
        }),
        jsx("button", { children: "After" }),
      ],
    }),
    colorScheme,
  );
}

function ReactStepListDemo() {
  const [demoProps, setDemoProps] = useState(stepListDemoPropsFromWindow);
  const colorScheme = useComparisonResolvedTheme();

  useEffect(() => {
    const handleControlsChange = (event) => {
      if (event instanceof CustomEvent && event.detail?.component === "steplist") {
        setDemoProps(normalizeStepListDemoProps(event.detail.props ?? {}));
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    return () => window.removeEventListener(comparisonControlsEvent, handleControlsChange);
  }, []);

  return jsx(ReactStepListBody, { demoProps, colorScheme });
}

export default () => jsx(ReactStepListDemo, {});
