// apps/comparison/src/components/solid/fixtures/styled/tableview.tsx
import h from "solid-js/h";
import { createMemo, createSignal, onCleanup, onMount } from "solid-js";
import { hc, renderProp } from "../../solid-h";
import { ActionBar as SolidSpectrumActionBar } from "@proyecto-viviana/solid-spectrum/ActionBar";
import { ActionButton as SolidSpectrumActionButton } from "@proyecto-viviana/solid-spectrum/ActionButton";
import {
  Cell as SolidSpectrumCell,
  Column as SolidSpectrumColumn,
  Row as SolidSpectrumRow,
  TableBody as SolidSpectrumTableBody,
  TableHeader as SolidSpectrumTableHeader,
  TableView as SolidSpectrumTableView,
} from "@proyecto-viviana/solid-spectrum/TableView";
import { Content as SolidSpectrumContent } from "@proyecto-viviana/solid-spectrum/Content";
import { Heading as SolidSpectrumHeading } from "@proyecto-viviana/solid-spectrum/Heading";
import { IllustratedMessage as SolidSpectrumIllustratedMessage } from "@proyecto-viviana/solid-spectrum/IllustratedMessage";
import { Provider as SolidSpectrumProvider } from "@proyecto-viviana/solid-spectrum/Provider";
import { Text as SolidSpectrumText } from "@proyecto-viviana/solid-spectrum/Text";
import {
  initialTableViewSelectedKeys,
  normalizeTableViewDemoProps,
  serializeTableViewDemoProps,
  serializeTableViewKeys,
  serializeTableViewSortDescriptor,
  sortTableViewRows,
  tableViewDemoItems,
  tableViewDemoLocaleFromWindow,
  tableViewDemoPropsFromWindow,
  tableViewInitialSortDescriptor,
  tableViewKeysFromValue,
  tableViewVisibleColumns,
  type TableViewDemoProps,
  type TableViewDemoRow,
  type TableViewSortDescriptor,
  comparisonControlsEvent,
} from "@comparison/data/tableview-demo";
import {
  createComparisonResolvedThemeSignal,
  providerShellStyle,
  collectionFixtureStyle,
} from "../styled-shared.tsx";

function SolidSpectrumTableViewDemo() {
  const [demoProps, setDemoProps] = createSignal<TableViewDemoProps>(
    tableViewDemoPropsFromWindow(),
  );
  const [selectedKeys, setSelectedKeys] = createSignal<Set<string>>(
    initialTableViewSelectedKeys(demoProps()),
  );
  const [sortDescriptor, setSortDescriptor] = createSignal<TableViewSortDescriptor | undefined>(
    tableViewInitialSortDescriptor(demoProps()),
  );
  const [actionKey, setActionKey] = createSignal("");
  const colorScheme = createComparisonResolvedThemeSignal();
  const locale = tableViewDemoLocaleFromWindow();
  const baseRows = createMemo(() => tableViewDemoItems(demoProps()));
  const itemKeys = createMemo(() => baseRows().map((item) => item.id));
  const rows = createMemo(() => sortTableViewRows(baseRows(), sortDescriptor()));
  const visibleColumns = createMemo(() => tableViewVisibleColumns(demoProps()));
  const selectedKeyText = createMemo(() => serializeTableViewKeys(selectedKeys()));

  onMount(() => {
    const handleControlsChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.component === "tableview") {
        const nextProps = normalizeTableViewDemoProps({
          ...demoProps(),
          ...(event.detail.props ?? {}),
        });
        setDemoProps(nextProps);
        setSelectedKeys(initialTableViewSelectedKeys(nextProps));
        setSortDescriptor(tableViewInitialSortDescriptor(nextProps));
        setActionKey("");
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    onCleanup(() => window.removeEventListener(comparisonControlsEvent, handleControlsChange));
  });

  return hc(
    SolidSpectrumProvider,
    {
      get colorScheme() {
        return colorScheme();
      },
      locale,
      background: "base",
      style: providerShellStyle,
    },
    [
      hc(
        "div",
        {
          style: { ...collectionFixtureStyle, width: "520px" },
          "data-comparison-control-root": "tableview",
          get "data-comparison-control-props"() {
            return serializeTableViewDemoProps(demoProps());
          },
          get "data-comparison-selected-keys"() {
            return selectedKeyText();
          },
          get "data-comparison-action-key"() {
            return actionKey();
          },
          get "data-comparison-sort-descriptor"() {
            return serializeTableViewSortDescriptor(sortDescriptor());
          },
        },
        [
          hc("button", {}, ["Before"]),
          hc(
            SolidSpectrumTableView,
            {
              "aria-label": "Project documents",
              get items() {
                return rows();
              },
              get columns() {
                return visibleColumns();
              },
              getKey: (row: TableViewDemoRow) => row.id,
              getTextValue: (row: TableViewDemoRow, column: { id?: keyof TableViewDemoRow }) =>
                column.id ? String(row[column.id] ?? "") : "",
              get density() {
                return demoProps().density;
              },
              get overflowMode() {
                return demoProps().overflowMode;
              },
              get isQuiet() {
                return demoProps().isQuiet;
              },
              get selectionMode() {
                return demoProps().selectionMode;
              },
              get disabledKeys() {
                return tableViewKeysFromValue(demoProps().disabledKeys, [], "multiple", itemKeys());
              },
              get selectedKeys() {
                return demoProps().selectionSource === "selectedKeys" ? selectedKeys() : undefined;
              },
              get defaultSelectedKeys() {
                return demoProps().selectionSource === "defaultSelectedKeys"
                  ? tableViewKeysFromValue(
                      demoProps().defaultSelectedKeys,
                      itemKeys().includes("project-brief") ? ["project-brief"] : [],
                      demoProps().selectionMode,
                      itemKeys(),
                    )
                  : undefined;
              },
              get sortDescriptor() {
                return sortDescriptor();
              },
              onSortChange: (descriptor: TableViewSortDescriptor) => setSortDescriptor(descriptor),
              onSelectionChange: (keys: "all" | Set<string | number>) =>
                setSelectedKeys(
                  keys === "all"
                    ? new Set(rows().map((item) => item.id))
                    : new Set<string>(Array.from(keys, String)),
                ),
              onAction: (key: string | number) => setActionKey(String(key)),
              get renderActionBar() {
                return demoProps().showActionBar
                  ? (keys: "all" | Set<string | number>) =>
                      hc(
                        SolidSpectrumActionBar,
                        {
                          selectedItemCount: keys === "all" ? rows().length : keys.size,
                          "data-comparison-tableview-actionbar": "true",
                          onClearSelection: () => setSelectedKeys(new Set<string>()),
                        },
                        [
                          hc(SolidSpectrumActionButton, {}, [
                            hc(SolidSpectrumText, {}, ["Archive"]),
                          ]),
                        ],
                      )
                  : undefined;
              },
              UNSAFE_style: { ...collectionTableStyle, height: "260px" },
            },
            renderProp(() => [
              hc(
                SolidSpectrumTableHeader,
                {},
                visibleColumns().map((column) =>
                  hc(
                    SolidSpectrumColumn,
                    {
                      id: column.id,
                      isRowHeader: column.isRowHeader,
                      get align() {
                        return demoProps().showDividers ? column.align : undefined;
                      },
                      get showDivider() {
                        return demoProps().showDividers ? column.showDivider : undefined;
                      },
                      get allowsSorting() {
                        return demoProps().sortColumn !== "none";
                      },
                      get allowsResizing() {
                        return demoProps().allowsResizing;
                      },
                      get width() {
                        if (!demoProps().allowsResizing) {
                          return undefined;
                        }
                        return column.id === "status"
                          ? 112
                          : column.id === "type"
                            ? 128
                            : undefined;
                      },
                      get minWidth() {
                        return demoProps().allowsResizing && column.id === "name" ? 180 : undefined;
                      },
                      get maxWidth() {
                        return demoProps().allowsResizing && column.id === "name" ? 320 : undefined;
                      },
                    },
                    [column.name],
                  ),
                ),
              ),
              hc(
                SolidSpectrumTableBody,
                {
                  renderEmptyState: () =>
                    hc(SolidSpectrumIllustratedMessage, {}, [
                      hc(SolidSpectrumHeading, {}, ["No documents"]),
                      hc(SolidSpectrumContent, {}, ["Create or upload a file to continue."]),
                    ]),
                },
                renderProp((row: TableViewDemoRow) =>
                  hc(
                    SolidSpectrumRow,
                    {
                      id: row.id,
                      item: row,
                      textValue: row.name,
                      get isDisabled() {
                        return demoProps().disabledItem === row.id;
                      },
                      get href() {
                        return demoProps().rowLinks && row.id === "project-brief"
                          ? "https://example.com/project-brief"
                          : undefined;
                      },
                      get target() {
                        return demoProps().rowLinks && row.id === "project-brief"
                          ? "_blank"
                          : undefined;
                      },
                    },
                    renderProp(() =>
                      visibleColumns().map((column) =>
                        hc(
                          SolidSpectrumCell,
                          {
                            get align() {
                              return demoProps().showDividers ? column.align : undefined;
                            },
                            get showDivider() {
                              return demoProps().showDividers ? column.showDivider : undefined;
                            },
                          },
                          [row[column.id]],
                        ),
                      ),
                    ),
                  ),
                ),
              ),
            ]),
          ),
          hc("button", {}, ["After"]),
        ],
      ),
    ],
  );
}

const collectionTableStyle = {
  width: "100%",
};

export default () => h(SolidSpectrumTableViewDemo, {});

// apps/comparison/src/components/react/fixtures/styled/tableview.js
import { jsx, jsxs } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import {
  ActionBar as SpectrumActionBar,
  ActionButton as SpectrumActionButton,
  Cell as SpectrumCell,
  Column as SpectrumColumn,
  Content as SpectrumContent,
  Heading as SpectrumHeading,
  IllustratedMessage as SpectrumIllustratedMessage,
  Row as SpectrumRow,
  TableBody as SpectrumTableBody,
  TableHeader as SpectrumTableHeader,
  TableView as SpectrumTableView,
  Text as SpectrumText,
} from "@react-spectrum/s2";
import {
  initialTableViewSelectedKeys,
  serializeTableViewDemoProps,
  serializeTableViewKeys,
  serializeTableViewSortDescriptor,
  sortTableViewRows,
  tableViewDemoItems,
  tableViewDemoLocaleFromWindow,
  tableViewDemoPropsFromWindow,
  tableViewInitialSortDescriptor,
  tableViewKeysFromValue,
  tableViewVisibleColumns,
  normalizeTableViewDemoProps,
  comparisonControlsEvent,
} from "@comparison/data/tableview-demo";
import {
  useComparisonResolvedTheme,
  renderReactSpectrumReference,
  collectionFixtureStyle,
} from "../styled-shared.js";

function ReactTableViewDemo() {
  const [demoProps, setDemoProps] = useState(tableViewDemoPropsFromWindow);
  const [selectedKeys, setSelectedKeys] = useState(() => initialTableViewSelectedKeys(demoProps));
  const [sortDescriptor, setSortDescriptor] = useState(() =>
    tableViewInitialSortDescriptor(demoProps),
  );
  const [actionKey, setActionKey] = useState("");
  const colorScheme = useComparisonResolvedTheme();
  const locale = tableViewDemoLocaleFromWindow();
  useEffect(() => {
    const handleControlsChange = (event) => {
      if (event instanceof CustomEvent && event.detail?.component === "tableview") {
        setDemoProps((current) => {
          const nextProps = normalizeTableViewDemoProps({ ...current, ...event.detail.props });
          setSelectedKeys(initialTableViewSelectedKeys(nextProps));
          setSortDescriptor(tableViewInitialSortDescriptor(nextProps));
          setActionKey("");
          return nextProps;
        });
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    return () => window.removeEventListener(comparisonControlsEvent, handleControlsChange);
  }, []);

  const baseRows = tableViewDemoItems(demoProps);
  const itemKeys = baseRows.map((item) => item.id);
  const rows = sortTableViewRows(baseRows, sortDescriptor);
  const visibleColumns = tableViewVisibleColumns(demoProps);
  const disabledKeys = tableViewKeysFromValue(demoProps.disabledKeys, [], "multiple", itemKeys);
  const selectionProps =
    demoProps.selectionSource === "defaultSelectedKeys"
      ? {
          defaultSelectedKeys: tableViewKeysFromValue(
            demoProps.defaultSelectedKeys,
            itemKeys.includes("project-brief") ? ["project-brief"] : [],
            demoProps.selectionMode,
            itemKeys,
          ),
        }
      : { selectedKeys };
  const actionBar = (keys) =>
    jsx(SpectrumActionBar, {
      selectedItemCount: keys === "all" ? rows.length : keys.size,
      "data-comparison-tableview-actionbar": "true",
      onClearSelection: () => setSelectedKeys(new Set()),
      children: jsx(SpectrumActionButton, {
        children: jsx(SpectrumText, { children: "Archive" }),
      }),
    });
  const renderKey = `${serializeTableViewDemoProps(demoProps)}|${serializeTableViewSortDescriptor(
    sortDescriptor,
  )}`;

  return renderReactSpectrumReference(
    jsx("div", {
      style: { ...collectionFixtureStyle, width: 520 },
      "data-comparison-control-root": "tableview",
      "data-comparison-control-props": serializeTableViewDemoProps(demoProps),
      "data-comparison-selected-keys": serializeTableViewKeys(selectedKeys),
      "data-comparison-action-key": actionKey,
      "data-comparison-sort-descriptor": serializeTableViewSortDescriptor(sortDescriptor),
      children: [
        jsx("button", { children: "Before" }, "before"),
        jsxs(
          SpectrumTableView,
          {
            "aria-label": "Project documents",
            density: demoProps.density,
            overflowMode: demoProps.overflowMode,
            isQuiet: demoProps.isQuiet,
            selectionMode: demoProps.selectionMode,
            disabledKeys,
            ...selectionProps,
            sortDescriptor,
            onSortChange: setSortDescriptor,
            onSelectionChange: (keys) =>
              setSelectedKeys(keys === "all" ? new Set(rows.map((row) => row.id)) : new Set(keys)),
            onAction: (key) => setActionKey(String(key)),
            renderActionBar: demoProps.showActionBar ? actionBar : undefined,
            UNSAFE_style: { ...collectionTableStyle, height: 260 },
            children: [
              jsxs(SpectrumTableHeader, {
                children: visibleColumns.map((column) =>
                  jsx(
                    SpectrumColumn,
                    {
                      id: column.id,
                      isRowHeader: column.isRowHeader,
                      align: demoProps.showDividers ? column.align : undefined,
                      showDivider: demoProps.showDividers ? column.showDivider : undefined,
                      allowsSorting: demoProps.sortColumn !== "none",
                      allowsResizing: demoProps.allowsResizing,
                      width:
                        demoProps.allowsResizing && column.id === "status"
                          ? 112
                          : demoProps.allowsResizing && column.id === "type"
                            ? 128
                            : undefined,
                      minWidth: demoProps.allowsResizing && column.id === "name" ? 180 : undefined,
                      maxWidth: demoProps.allowsResizing && column.id === "name" ? 320 : undefined,
                      children: column.name,
                    },
                    column.id,
                  ),
                ),
              }),
              jsx(SpectrumTableBody, {
                items: rows,
                renderEmptyState: () =>
                  jsxs(SpectrumIllustratedMessage, {
                    children: [
                      jsx(SpectrumHeading, { children: "No documents" }),
                      jsx(SpectrumContent, { children: "Create or upload a file to continue." }),
                    ],
                  }),
                children: (row) =>
                  jsxs(
                    SpectrumRow,
                    {
                      id: row.id,
                      textValue: row.name,
                      isDisabled: demoProps.disabledItem === row.id,
                      href:
                        demoProps.rowLinks && row.id === "project-brief"
                          ? "https://example.com/project-brief"
                          : undefined,
                      target:
                        demoProps.rowLinks && row.id === "project-brief" ? "_blank" : undefined,
                      children: visibleColumns.map((column) =>
                        jsx(
                          SpectrumCell,
                          {
                            align: demoProps.showDividers ? column.align : undefined,
                            showDivider: demoProps.showDividers ? column.showDivider : undefined,
                            children: row[column.id],
                          },
                          column.id,
                        ),
                      ),
                    },
                    row.id,
                  ),
              }),
            ],
          },
          renderKey,
        ),
        jsx("button", { children: "After" }, "after"),
      ],
    }),
    colorScheme,
    locale,
  );
}

const collectionTableStyle = {
  width: "100%",
};

export default () => jsx(ReactTableViewDemo, {});
