// apps/comparison/src/components/solid/fixtures/styled/taggroup.tsx
import h from "solid-js/h";
import { createMemo, createSignal, onCleanup, onMount } from "solid-js";
import { hc, renderProp } from "../../solid-h";
import {
  Provider as SolidSpectrumProvider,
  Tag as SolidSpectrumTag,
  TagGroup as SolidSpectrumTagGroup,
  Text as SolidSpectrumText,
} from "@proyecto-viviana/solid-spectrum";
import {
  disabledTagGroupKeys,
  initialTagGroupSelectedKeys,
  normalizeTagGroupDemoProps,
  serializeTagGroupDemoProps,
  serializeTagGroupKeys,
  tagGroupDemoLocaleFromWindow,
  tagGroupDemoPropsFromWindow,
  tagGroupInitialItems,
  tagGroupItems,
  tagGroupKeysFromValue,
  type TagGroupDemoProps,
  comparisonControlsEvent,
} from "@comparison/data/taggroup-demo";
import {
  createComparisonResolvedThemeSignal,
  providerShellStyle,
  collectionFixtureStyle,
  SolidNewIcon,
} from "../styled-shared.tsx";

function SolidSpectrumTagGroupDemo() {
  const colorScheme = createComparisonResolvedThemeSignal();
  const locale = tagGroupDemoLocaleFromWindow();
  const [demoProps, setDemoProps] = createSignal<TagGroupDemoProps>(tagGroupDemoPropsFromWindow());
  const [tags, setTags] = createSignal(tagGroupInitialItems(demoProps()));
  const [selectedKeys, setSelectedKeys] = createSignal(initialTagGroupSelectedKeys(demoProps()));
  const [actionCount, setActionCount] = createSignal(0);
  const serializedProps = createMemo(() => serializeTagGroupDemoProps(demoProps()));
  const selectedValue = createMemo(() => serializeTagGroupKeys(selectedKeys()));

  onMount(() => {
    const handleControlsChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.component === "taggroup") {
        const nextProps = normalizeTagGroupDemoProps({
          ...demoProps(),
          ...event.detail.props,
        });
        setDemoProps(nextProps);
        setTags(tagGroupInitialItems(nextProps));
        setSelectedKeys(initialTagGroupSelectedKeys(nextProps));
        setActionCount(0);
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    onCleanup(() => window.removeEventListener(comparisonControlsEvent, handleControlsChange));
  });

  return hc(
    SolidSpectrumProvider,
    {
      get colorScheme() {
        return colorScheme();
      },
      // Threaded so the D10 RTL driver's `?locale=ar-AE` gives the Provider
      // `direction: 'rtl'` and `createTag` flips its inline-axis nav.
      locale,
      background: "base",
      style: providerShellStyle,
    },
    [
      // Boundary buttons flank the grid so the D5 walk can Tab into the group and
      // Shift+Tab into it from after — exercising entry-direction in both ways.
      h("button", {}, "Before"),
      hc(
        "div",
        {
          style: collectionFixtureStyle,
          "data-comparison-control-root": "taggroup",
          "data-comparison-control-props": serializedProps,
          "data-comparison-selected-keys": selectedValue,
          get "data-comparison-tag-count"() {
            return String(tags().length);
          },
          get "data-comparison-action-count"() {
            return String(actionCount());
          },
        },
        [
          hc(
            SolidSpectrumTagGroup,
            {
              get label() {
                return demoProps().label;
              },
              get items() {
                return tags();
              },
              get size() {
                return demoProps().size;
              },
              get labelPosition() {
                return demoProps().labelPosition;
              },
              get labelAlign() {
                return demoProps().labelAlign;
              },
              get selectionMode() {
                return demoProps().selectionMode;
              },
              get selectionBehavior() {
                return demoProps().selectionBehavior;
              },
              get selectedKeys() {
                return demoProps().selectionSource === "selectedKeys" ? selectedKeys() : undefined;
              },
              get defaultSelectedKeys() {
                return demoProps().selectionSource === "defaultSelectedKeys"
                  ? tagGroupKeysFromValue(
                      demoProps().defaultSelectedKeys,
                      ["landscape"],
                      demoProps().selectionMode,
                    )
                  : undefined;
              },
              get disabledKeys() {
                return disabledTagGroupKeys(demoProps());
              },
              get isEmphasized() {
                return demoProps().isEmphasized;
              },
              get isInvalid() {
                return demoProps().isInvalid;
              },
              get isDisabled() {
                return demoProps().isDisabled;
              },
              get description() {
                return demoProps().showDescription
                  ? "Use tags to organize photo metadata."
                  : undefined;
              },
              get errorMessage() {
                return demoProps().isInvalid && demoProps().showErrorMessage
                  ? "Choose at least one usable tag."
                  : undefined;
              },
              renderEmptyState: () => "No categories",
              UNSAFE_style: collectionTagGroupStyle,
              get groupActionLabel() {
                return demoProps().withGroupAction ? "Add tag" : undefined;
              },
              onGroupAction: () => setActionCount((count) => count + 1),
              onAction: () => setActionCount((count) => count + 1),
              onSelectionChange: (keys: Set<string | number> | "all") =>
                setSelectedKeys(
                  keys === "all"
                    ? new Set(tagGroupItems.map((item) => item.id))
                    : new Set<string>(Array.from(keys, String)),
                ),
              get onRemove() {
                if (!demoProps().allowsRemoving) {
                  return undefined;
                }

                return (keys: Set<string | number>) => {
                  setTags((currentTags) => currentTags.filter((item) => !keys.has(item.id)));
                  setSelectedKeys((currentKeys) => {
                    const nextKeys = new Set(currentKeys);
                    for (const key of keys) {
                      nextKeys.delete(String(key));
                    }
                    return nextKeys;
                  });
                };
              },
            },
            renderProp((item: (typeof tagGroupItems)[number]) =>
              hc(
                SolidSpectrumTag,
                { id: item.id },
                demoProps().contentMode === "icon"
                  ? [
                      h(SolidNewIcon, { "aria-hidden": "true" }),
                      h(SolidSpectrumText, {}, item.name),
                    ]
                  : [item.name],
              ),
            ),
          ),
        ],
      ),
      h("button", {}, "After"),
    ],
  );
}

const collectionTagGroupStyle = {
  "max-width": "320px",
};

export default () => h(SolidSpectrumTagGroupDemo, {});

// apps/comparison/src/components/react/fixtures/styled/taggroup.js
import { jsx, jsxs } from "react/jsx-runtime";
import { Fragment, useEffect, useState } from "react";
import {
  Tag as SpectrumTag,
  TagGroup as SpectrumTagGroup,
  Text as SpectrumText,
} from "@react-spectrum/s2";
import {
  disabledTagGroupKeys,
  initialTagGroupSelectedKeys,
  normalizeTagGroupDemoProps,
  serializeTagGroupDemoProps,
  serializeTagGroupKeys,
  tagGroupDemoLocaleFromWindow,
  tagGroupDemoPropsFromWindow,
  tagGroupInitialItems,
  tagGroupItems,
  tagGroupKeysFromValue,
  comparisonControlsEvent,
} from "@comparison/data/taggroup-demo";
import {
  useComparisonResolvedTheme,
  renderReactSpectrumReference,
  collectionFixtureStyle,
  ReactButtonIcon,
} from "../styled-shared.js";

function ReactTagGroupDemo() {
  const colorScheme = useComparisonResolvedTheme();
  const locale = tagGroupDemoLocaleFromWindow();
  const [demoProps, setDemoProps] = useState(tagGroupDemoPropsFromWindow);
  const [tags, setTags] = useState(() => tagGroupInitialItems(demoProps));
  const [selectedKeys, setSelectedKeys] = useState(() => initialTagGroupSelectedKeys(demoProps));
  const [actionCount, setActionCount] = useState(0);

  useEffect(() => {
    const handleControlsChange = (event) => {
      if (event instanceof CustomEvent && event.detail?.component === "taggroup") {
        setDemoProps((current) => {
          const nextProps = normalizeTagGroupDemoProps({ ...current, ...event.detail.props });
          setTags(tagGroupInitialItems(nextProps));
          setSelectedKeys(initialTagGroupSelectedKeys(nextProps));
          setActionCount(0);
          return nextProps;
        });
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    return () => window.removeEventListener(comparisonControlsEvent, handleControlsChange);
  }, []);

  const selectionProps =
    demoProps.selectionSource === "defaultSelectedKeys"
      ? {
          defaultSelectedKeys: tagGroupKeysFromValue(
            demoProps.defaultSelectedKeys,
            ["landscape"],
            demoProps.selectionMode,
          ),
        }
      : { selectedKeys };
  const selectedValue = serializeTagGroupKeys(selectedKeys);
  const renderKey = [
    demoProps.size,
    demoProps.labelPosition,
    demoProps.labelAlign,
    demoProps.selectionMode,
    demoProps.selectionBehavior,
    demoProps.selectionSource,
    demoProps.selectionSource === "defaultSelectedKeys"
      ? demoProps.defaultSelectedKeys
      : demoProps.selectedKeys,
    demoProps.disabledKeys,
    demoProps.disabledItem,
    demoProps.itemCount,
    demoProps.contentMode,
    demoProps.isEmphasized,
    demoProps.isInvalid,
    demoProps.isDisabled,
    demoProps.showDescription,
    demoProps.showErrorMessage,
    demoProps.allowsRemoving,
    demoProps.withGroupAction,
  ].join("|");

  return renderReactSpectrumReference(
    jsxs(Fragment, {
      // Boundary buttons flank the grid so the D5 focus walk can Tab into the
      // group from before it and Shift+Tab into it from after it — exercising the
      // trampoline's entry-direction logic in both directions.
      children: [
        jsx("button", { children: "Before" }),
        jsx("div", {
          style: collectionFixtureStyle,
          "data-comparison-control-root": "taggroup",
          "data-comparison-control-props": serializeTagGroupDemoProps(demoProps),
          "data-comparison-selected-keys": selectedValue,
          "data-comparison-tag-count": String(tags.length),
          "data-comparison-action-count": String(actionCount),
          children: jsx(SpectrumTagGroup, {
            key: renderKey,
            label: demoProps.label,
            size: demoProps.size,
            labelPosition: demoProps.labelPosition,
            labelAlign: demoProps.labelAlign,
            selectionMode: demoProps.selectionMode,
            selectionBehavior: demoProps.selectionBehavior,
            isEmphasized: demoProps.isEmphasized,
            isInvalid: demoProps.isInvalid,
            isDisabled: demoProps.isDisabled,
            description: demoProps.showDescription
              ? "Use tags to organize photo metadata."
              : undefined,
            errorMessage:
              demoProps.isInvalid && demoProps.showErrorMessage
                ? "Choose at least one usable tag."
                : undefined,
            renderEmptyState: () => "No categories",
            disabledKeys: disabledTagGroupKeys(demoProps),
            items: tags,
            ...selectionProps,
            onSelectionChange: (keys) =>
              setSelectedKeys(
                keys === "all" ? new Set(tagGroupItems.map((item) => item.id)) : new Set(keys),
              ),
            onRemove: demoProps.allowsRemoving
              ? (keys) => {
                  setTags((currentTags) => currentTags.filter((item) => !keys.has(item.id)));
                  setSelectedKeys((currentKeys) => {
                    const nextKeys = new Set(currentKeys);
                    for (const key of keys) {
                      nextKeys.delete(key);
                    }
                    return nextKeys;
                  });
                }
              : undefined,
            onAction: () => setActionCount((count) => count + 1),
            groupActionLabel: demoProps.withGroupAction ? "Add tag" : undefined,
            onGroupAction: demoProps.withGroupAction
              ? () => setActionCount((count) => count + 1)
              : undefined,
            UNSAFE_style: collectionTagGroupStyle,
            children: (item) =>
              jsx(SpectrumTag, {
                children:
                  demoProps.contentMode === "icon"
                    ? jsxs(Fragment, {
                        children: [
                          jsx(ReactButtonIcon, { "aria-hidden": "true" }),
                          jsx(SpectrumText, { children: item.name }),
                        ],
                      })
                    : item.name,
              }),
          }),
        }),
        jsx("button", { children: "After" }),
      ],
    }),
    colorScheme,
    locale,
  );
}

const collectionTagGroupStyle = {
  maxWidth: 320,
};

export default () => jsx(ReactTagGroupDemo, {});
