// apps/comparison/src/components/solid/fixtures/styled/timefield.tsx
import h from "@solidjs/h";
import { createMemo, createSignal, onSettled } from "solid-js";
import { hc } from "../../solid-h";
import { Content as SolidSpectrumContent } from "@proyecto-viviana/solid-spectrum/Content";
import { ContextualHelp as SolidSpectrumContextualHelp } from "@proyecto-viviana/solid-spectrum/ContextualHelp";
import { Heading as SolidSpectrumHeading } from "@proyecto-viviana/solid-spectrum/Heading";
import { Provider as SolidSpectrumProvider } from "@proyecto-viviana/solid-spectrum/Provider";
import { TimeField as SolidSpectrumTimeField } from "@proyecto-viviana/solid-spectrum/TimeField";
import {
  timeFieldMaxValue,
  timeFieldMinValue,
  timeFieldDemoPropsFromWindow,
  timeFieldValueFromDemo,
  normalizeTimeFieldDemoProps,
  serializeTimeFieldDemoProps,
  serializeTimeFieldValue,
  type TimeFieldDemoProps,
  comparisonControlsEvent,
} from "@comparison/data/timefield-demo";
import {
  comparisonThemeChangeEvent,
  getComparisonResolvedThemeFromDocument,
  type ComparisonResolvedTheme,
} from "@comparison/data/theme";
import { providerShellStyle } from "../styled-shared.tsx";

function SolidSpectrumTimeFieldDemo() {
  const initialDemoProps = timeFieldDemoPropsFromWindow();
  const [demoProps, setDemoProps] = createSignal<TimeFieldDemoProps>(initialDemoProps);
  const [value, setValue] = createSignal(timeFieldValueFromDemo(initialDemoProps));
  const [colorScheme, setColorScheme] = createSignal<ComparisonResolvedTheme>(
    getComparisonResolvedThemeFromDocument(),
  );

  onSettled(() => {
    const handleControlsChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.component === "timefield") {
        const nextProps = normalizeTimeFieldDemoProps(event.detail.props ?? {});
        setDemoProps(nextProps);
        setValue(() => timeFieldValueFromDemo(nextProps));
      }
    };
    const handleThemeChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.resolvedTheme) {
        setColorScheme(event.detail.resolvedTheme as ComparisonResolvedTheme);
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    window.addEventListener(comparisonThemeChangeEvent, handleThemeChange);
    setColorScheme(getComparisonResolvedThemeFromDocument());
    return () => {
      window.removeEventListener(comparisonControlsEvent, handleControlsChange);
      window.removeEventListener(comparisonThemeChangeEvent, handleThemeChange);
    };
  });

  const serializedProps = createMemo(() => serializeTimeFieldDemoProps(demoProps()));
  const contextualHelp = createMemo(() =>
    demoProps().withContextualHelp
      ? hc(SolidSpectrumContextualHelp, {}, [
          hc(SolidSpectrumHeading, { slot: "title" }, ["Time help"]),
          hc(SolidSpectrumContent, {}, ["Choose a start time in your schedule."]),
        ])
      : undefined,
  );

  return hc(
    SolidSpectrumProvider,
    {
      get colorScheme() {
        return colorScheme();
      },
      get locale() {
        return demoProps().locale || undefined;
      },
      background: "base",
      style: providerShellStyle,
    },
    [
      hc(
        "div",
        {
          "data-comparison-control-root": "timefield",
          get "data-comparison-control-props"() {
            return serializedProps();
          },
          get "data-comparison-color-scheme"() {
            return colorScheme();
          },
          get "data-comparison-locale"() {
            return demoProps().locale;
          },
          get "data-comparison-value"() {
            return serializeTimeFieldValue(value());
          },
        },
        [
          hc(SolidSpectrumTimeField, {
            class: "comparison-timefield-root",
            get label() {
              return demoProps().label;
            },
            get size() {
              return demoProps().size;
            },
            get labelPosition() {
              return demoProps().labelPosition;
            },
            get labelAlign() {
              return demoProps().labelAlign;
            },
            get necessityIndicator() {
              return demoProps().necessityIndicator;
            },
            get contextualHelp() {
              return contextualHelp();
            },
            get value() {
              return value() ?? undefined;
            },
            get granularity() {
              return demoProps().granularity;
            },
            get shouldForceLeadingZeros() {
              return demoProps().shouldForceLeadingZeros;
            },
            get hourCycle() {
              return demoProps().hourCycle ? Number(demoProps().hourCycle) : undefined;
            },
            get hideTimeZone() {
              return demoProps().hideTimeZone;
            },
            get minValue() {
              return demoProps().constrainRange ? timeFieldMinValue() : undefined;
            },
            get maxValue() {
              return demoProps().constrainRange ? timeFieldMaxValue() : undefined;
            },
            get name() {
              return demoProps().name || undefined;
            },
            get form() {
              return demoProps().form || undefined;
            },
            get validationBehavior() {
              return demoProps().validationBehavior || undefined;
            },
            get description() {
              return demoProps().description;
            },
            get errorMessage() {
              return demoProps().errorMessage;
            },
            get isDisabled() {
              return demoProps().isDisabled;
            },
            get isReadOnly() {
              return demoProps().isReadOnly;
            },
            get isRequired() {
              return demoProps().isRequired;
            },
            get isInvalid() {
              return demoProps().isInvalid;
            },
            onChange: setValue,
          }),
        ],
      ),
    ],
  );
}

export default () => h(SolidSpectrumTimeFieldDemo, {});

// apps/comparison/src/components/react/fixtures/styled/timefield.js
import { jsx, jsxs } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import {
  ContextualHelp as SpectrumContextualHelp,
  Content as SpectrumContent,
  Heading as SpectrumHeading,
  TimeField as SpectrumTimeField,
} from "@react-spectrum/s2";
import {
  timeFieldMaxValue,
  timeFieldMinValue,
  timeFieldDemoPropsFromWindow,
  timeFieldValueFromDemo,
  isTimeFieldDemoValueInvalid,
  normalizeTimeFieldDemoProps,
  serializeTimeFieldDemoProps,
  serializeTimeFieldValue,
  comparisonControlsEvent,
} from "@comparison/data/timefield-demo";
import { useComparisonResolvedTheme, renderReactSpectrumReference } from "../styled-shared.js";

function ReactTimeFieldDemo() {
  const initialDemoProps = timeFieldDemoPropsFromWindow();
  const [demoProps, setDemoProps] = useState(() => initialDemoProps);
  const [value, setValue] = useState(() => timeFieldValueFromDemo(initialDemoProps));
  const colorScheme = useComparisonResolvedTheme();
  const serializedProps = serializeTimeFieldDemoProps(demoProps);
  useEffect(() => {
    const handleControlsChange = (event) => {
      if (event instanceof CustomEvent && event.detail?.component === "timefield") {
        const nextProps = normalizeTimeFieldDemoProps(event.detail.props ?? {});
        setDemoProps(nextProps);
        setValue(timeFieldValueFromDemo(nextProps));
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    return () => window.removeEventListener(comparisonControlsEvent, handleControlsChange);
  }, []);

  const contextualHelp = demoProps.withContextualHelp
    ? jsxs(SpectrumContextualHelp, {
        children: [
          jsx(SpectrumHeading, { slot: "title", children: "Time help" }),
          jsx(SpectrumContent, { children: "Choose a start time in your schedule." }),
        ],
      })
    : undefined;
  const isAriaBuiltinInvalid =
    demoProps.validationBehavior === "aria" && isTimeFieldDemoValueInvalid(demoProps, value);
  const isInvalid = demoProps.isInvalid || isAriaBuiltinInvalid;

  return renderReactSpectrumReference(
    jsx("div", {
      "data-comparison-control-root": "timefield",
      "data-comparison-control-props": serializedProps,
      "data-comparison-react-builtin-invalid": String(isAriaBuiltinInvalid),
      "data-comparison-value": serializeTimeFieldValue(value),
      "data-comparison-locale": demoProps.locale,
      "data-comparison-color-scheme": colorScheme,
      children: jsx(SpectrumTimeField, {
        label: demoProps.label,
        size: demoProps.size,
        labelPosition: demoProps.labelPosition,
        labelAlign: demoProps.labelAlign,
        necessityIndicator: demoProps.necessityIndicator,
        contextualHelp,
        value: value ?? undefined,
        granularity: demoProps.granularity,
        shouldForceLeadingZeros: demoProps.shouldForceLeadingZeros,
        hourCycle: demoProps.hourCycle ? Number(demoProps.hourCycle) : undefined,
        hideTimeZone: demoProps.hideTimeZone,
        minValue: demoProps.constrainRange ? timeFieldMinValue() : undefined,
        maxValue: demoProps.constrainRange ? timeFieldMaxValue() : undefined,
        name: demoProps.name || undefined,
        form: demoProps.form || undefined,
        validationBehavior: demoProps.validationBehavior || undefined,
        description: demoProps.description,
        errorMessage: demoProps.errorMessage,
        isDisabled: demoProps.isDisabled,
        isReadOnly: demoProps.isReadOnly,
        isRequired: demoProps.isRequired,
        isInvalid,
        onChange: (nextValue) => setValue(nextValue),
        UNSAFE_className: "comparison-timefield-root",
      }),
    }),
    colorScheme,
    demoProps.locale || void 0,
  );
}

export default () => jsx(ReactTimeFieldDemo, {});
