// apps/comparison/src/components/react/fixtures/styled/avatar.js
import { jsx } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import { Avatar as SpectrumAvatar } from "@react-spectrum/s2";
import {
  avatarDemoPropsFromWindow,
  comparisonHarnessAvatarSrc,
  normalizeAvatarDemoProps,
  serializeAvatarDemoProps,
} from "@comparison/data/avatar-demo";
import { comparisonControlsEvent } from "@comparison/data/button-demo";
import { useComparisonResolvedTheme, renderReactSpectrumReference } from "../styled-shared.js";

function ReactAvatarDemo() {
  const [demoProps, setDemoProps] = useState(avatarDemoPropsFromWindow);
  const colorScheme = useComparisonResolvedTheme();

  useEffect(() => {
    const handleControlsChange = (event) => {
      if (event instanceof CustomEvent && event.detail?.component === "avatar") {
        setDemoProps(normalizeAvatarDemoProps(event.detail.props ?? {}));
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    return () => window.removeEventListener(comparisonControlsEvent, handleControlsChange);
  }, []);

  return renderReactSpectrumReference(
    jsx("div", {
      className: "comparison-avatar-row",
      "data-comparison-avatar-over-background": demoProps.isOverBackground ? "true" : "false",
      "data-comparison-control-root": "avatar",
      "data-comparison-control-props": serializeAvatarDemoProps(demoProps),
      children: jsx(SpectrumAvatar, {
        alt: demoProps.alt,
        src: comparisonHarnessAvatarSrc(demoProps.src, "react") || undefined,
        size: Number(demoProps.size),
        isOverBackground: demoProps.isOverBackground,
      }),
    }),
    colorScheme,
  );
}

export default () => jsx(ReactAvatarDemo, {});

// apps/comparison/src/components/solid/fixtures/styled/avatar.tsx
import h from "@solidjs/h";
import { createSignal, onSettled } from "solid-js";
import { hc } from "../../solid-h";
import { Avatar as SolidSpectrumAvatar } from "@proyecto-viviana/solid-spectrum/Avatar";
import { Provider as SolidSpectrumProvider } from "@proyecto-viviana/solid-spectrum/Provider";
import {
  avatarDemoPropsFromWindow,
  comparisonHarnessAvatarSrc,
  normalizeAvatarDemoProps,
  serializeAvatarDemoProps,
  type AvatarDemoProps,
} from "@comparison/data/avatar-demo";
import { comparisonControlsEvent } from "@comparison/data/button-demo";
import {
  comparisonThemeChangeEvent,
  getComparisonResolvedThemeFromDocument,
  type ComparisonResolvedTheme,
} from "@comparison/data/theme";
import { providerShellStyle } from "../styled-shared.tsx";

function SolidSpectrumAvatarDemo() {
  const [demoProps, setDemoProps] = createSignal<AvatarDemoProps>(avatarDemoPropsFromWindow());
  const [colorScheme, setColorScheme] = createSignal<ComparisonResolvedTheme>(
    getComparisonResolvedThemeFromDocument(),
  );

  onSettled(() => {
    const handleControlsChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.component === "avatar") {
        setDemoProps(normalizeAvatarDemoProps(event.detail.props ?? {}));
      }
    };
    const handleThemeChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.resolvedTheme) {
        setColorScheme(event.detail.resolvedTheme as ComparisonResolvedTheme);
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    window.addEventListener(comparisonThemeChangeEvent, handleThemeChange);
    setColorScheme(getComparisonResolvedThemeFromDocument());
    return () => {
      window.removeEventListener(comparisonControlsEvent, handleControlsChange);
      window.removeEventListener(comparisonThemeChangeEvent, handleThemeChange);
    };
  });

  return hc(
    SolidSpectrumProvider,
    {
      get colorScheme() {
        return colorScheme();
      },
      background: "base",
      style: providerShellStyle,
    },
    [
      hc(
        "div",
        {
          class: "comparison-avatar-row",
          get "data-comparison-avatar-over-background"() {
            return demoProps().isOverBackground ? "true" : "false";
          },
          "data-comparison-control-root": "avatar",
          get "data-comparison-control-props"() {
            return serializeAvatarDemoProps(demoProps());
          },
        },
        [
          () =>
            h(SolidSpectrumAvatar, {
              get alt() {
                return demoProps().alt;
              },
              get src() {
                return comparisonHarnessAvatarSrc(demoProps().src, "solid") || undefined;
              },
              get size() {
                return Number(demoProps().size);
              },
              get isOverBackground() {
                return demoProps().isOverBackground;
              },
            }),
        ],
      ),
    ],
  );
}

export default () => h(SolidSpectrumAvatarDemo, {});
