// apps/comparison/src/components/react/fixtures/styled/breadcrumbs.js
import { jsx } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import {
  Breadcrumb as SpectrumBreadcrumb,
  Breadcrumbs as SpectrumBreadcrumbs,
} from "@react-spectrum/s2";
import {
  breadcrumbsDemoPropsFromWindow,
  breadcrumbsItemsForSet,
  normalizeBreadcrumbsDemoProps,
  serializeBreadcrumbPath,
  serializeBreadcrumbsDemoProps,
  comparisonControlsEvent,
} from "@comparison/data/breadcrumbs-demo";
import { useComparisonResolvedTheme, renderReactSpectrumReference } from "../styled-shared.js";

function ReactBreadcrumbsDemo() {
  const colorScheme = useComparisonResolvedTheme();
  const [demoProps, setDemoProps] = useState(breadcrumbsDemoPropsFromWindow);
  const [pathItems, setPathItems] = useState(() =>
    breadcrumbsItemsForSet(breadcrumbsDemoPropsFromWindow().itemSet),
  );
  const [actionCount, setActionCount] = useState(0);
  const [lastAction, setLastAction] = useState("");

  useEffect(() => {
    const handleControlsChange = (event) => {
      if (event instanceof CustomEvent && event.detail?.component === "breadcrumbs") {
        const nextProps = normalizeBreadcrumbsDemoProps(event.detail.props ?? {});
        setDemoProps(nextProps);
        setPathItems(breadcrumbsItemsForSet(nextProps.itemSet));
        setActionCount(0);
        setLastAction("");
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    return () => window.removeEventListener(comparisonControlsEvent, handleControlsChange);
  }, []);

  const handleAction = (key) => {
    const nextKey = String(key);
    const sourceItems = breadcrumbsItemsForSet(demoProps.itemSet);
    const index = sourceItems.findIndex((item) => item.id === nextKey);
    setActionCount((count) => count + 1);
    setLastAction(nextKey);
    if (index >= 0) {
      setPathItems(sourceItems.slice(0, index + 1));
    }
  };

  const breadcrumbs =
    demoProps.itemSet === "standard"
      ? jsx(SpectrumBreadcrumbs, {
          size: demoProps.size,
          isDisabled: demoProps.isDisabled,
          UNSAFE_style: { width: "100%" },
          "aria-label": "Project location",
          onAction: handleAction,
          children: pathItems.map((item) =>
            jsx(
              SpectrumBreadcrumb,
              {
                id: item.id,
                href: item.href,
                children: item.label,
              },
              item.id,
            ),
          ),
        })
      : jsx(SpectrumBreadcrumbs, {
          items: pathItems,
          size: demoProps.size,
          isDisabled: demoProps.isDisabled,
          UNSAFE_style: { width: "100%" },
          "aria-label": "Project location",
          onAction: handleAction,
          children: (item) =>
            jsx(SpectrumBreadcrumb, {
              id: item.id,
              href: item.href,
              children: item.label,
            }),
        });

  return renderReactSpectrumReference(
    jsx("div", {
      className: "comparison-breadcrumbs-row",
      "data-comparison-control-root": "breadcrumbs",
      "data-comparison-control-props": serializeBreadcrumbsDemoProps(demoProps),
      "data-comparison-breadcrumbs-props": serializeBreadcrumbsDemoProps(demoProps),
      "data-comparison-action-count": String(actionCount),
      "data-comparison-last-action": lastAction,
      "data-comparison-path": serializeBreadcrumbPath(pathItems),
      children: breadcrumbs,
    }),
    colorScheme,
  );
}

export default () => jsx(ReactBreadcrumbsDemo, {});

// apps/comparison/src/components/solid/fixtures/styled/breadcrumbs.tsx
import h from "solid-js/h";
import { createSignal, onCleanup, onMount } from "solid-js";
import { hc, renderProp } from "../../solid-h";
import {
  Breadcrumb as SolidSpectrumBreadcrumb,
  Breadcrumbs as SolidSpectrumBreadcrumbs,
} from "@proyecto-viviana/solid-spectrum/Breadcrumbs";
import { Provider as SolidSpectrumProvider } from "@proyecto-viviana/solid-spectrum/Provider";
import {
  breadcrumbsDemoPropsFromWindow,
  breadcrumbsItemsForSet,
  normalizeBreadcrumbsDemoProps,
  serializeBreadcrumbPath,
  serializeBreadcrumbsDemoProps,
  type BreadcrumbsDemoProps,
  type BreadcrumbsItem,
  comparisonControlsEvent,
} from "@comparison/data/breadcrumbs-demo";
import {
  comparisonThemeChangeEvent,
  getComparisonResolvedThemeFromDocument,
  type ComparisonResolvedTheme,
} from "@comparison/data/theme";
import { providerShellStyle } from "../styled-shared.tsx";

function SolidSpectrumBreadcrumbsDemo() {
  const [demoProps, setDemoProps] = createSignal<BreadcrumbsDemoProps>(
    breadcrumbsDemoPropsFromWindow(),
  );
  const [pathItems, setPathItems] = createSignal<BreadcrumbsItem[]>(
    breadcrumbsItemsForSet(breadcrumbsDemoPropsFromWindow().itemSet),
  );
  const [actionCount, setActionCount] = createSignal(0);
  const [lastAction, setLastAction] = createSignal("");
  const [colorScheme, setColorScheme] = createSignal<ComparisonResolvedTheme>(
    getComparisonResolvedThemeFromDocument(),
  );

  onMount(() => {
    const handleControlsChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.component === "breadcrumbs") {
        const nextProps = normalizeBreadcrumbsDemoProps(event.detail.props ?? {});
        setDemoProps(nextProps);
        setPathItems(breadcrumbsItemsForSet(nextProps.itemSet));
        setActionCount(0);
        setLastAction("");
      }
    };
    const handleThemeChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.resolvedTheme) {
        setColorScheme(event.detail.resolvedTheme as ComparisonResolvedTheme);
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    window.addEventListener(comparisonThemeChangeEvent, handleThemeChange);
    setColorScheme(getComparisonResolvedThemeFromDocument());
    onCleanup(() => {
      window.removeEventListener(comparisonControlsEvent, handleControlsChange);
      window.removeEventListener(comparisonThemeChangeEvent, handleThemeChange);
    });
  });

  const handleAction = (key: string | number) => {
    const nextKey = String(key);
    const sourceItems = breadcrumbsItemsForSet(demoProps().itemSet);
    const index = sourceItems.findIndex((item) => item.id === nextKey);
    setActionCount((count) => count + 1);
    setLastAction(nextKey);
    if (index >= 0) {
      setPathItems(sourceItems.slice(0, index + 1));
    }
  };

  return hc(
    SolidSpectrumProvider,
    {
      get colorScheme() {
        return colorScheme();
      },
      background: "base",
      style: providerShellStyle,
    },
    [
      hc(
        "div",
        {
          class: "comparison-breadcrumbs-row",
          "data-comparison-control-root": "breadcrumbs",
          get "data-comparison-control-props"() {
            return serializeBreadcrumbsDemoProps(demoProps());
          },
          get "data-comparison-breadcrumbs-props"() {
            return serializeBreadcrumbsDemoProps(demoProps());
          },
          get "data-comparison-action-count"() {
            return String(actionCount());
          },
          get "data-comparison-last-action"() {
            return lastAction();
          },
          get "data-comparison-path"() {
            return serializeBreadcrumbPath(pathItems());
          },
        },
        [
          () =>
            demoProps().itemSet === "standard"
              ? hc(
                  SolidSpectrumBreadcrumbs,
                  {
                    get size() {
                      return demoProps().size;
                    },
                    get isDisabled() {
                      return demoProps().isDisabled;
                    },
                    UNSAFE_style: { width: "100%" },
                    "aria-label": "Project location",
                    onAction: handleAction,
                  },
                  [
                    () =>
                      pathItems().map((item) =>
                        h(
                          SolidSpectrumBreadcrumb,
                          {
                            id: item.id,
                            href: item.href,
                          },
                          item.label,
                        ),
                      ),
                  ],
                )
              : hc(
                  SolidSpectrumBreadcrumbs,
                  {
                    get items() {
                      return pathItems();
                    },
                    getKey: (item: BreadcrumbsItem) => item.id,
                    get size() {
                      return demoProps().size;
                    },
                    get isDisabled() {
                      return demoProps().isDisabled;
                    },
                    UNSAFE_style: { width: "100%" },
                    "aria-label": "Project location",
                    onAction: handleAction,
                  },
                  renderProp((item: BreadcrumbsItem) =>
                    h(
                      SolidSpectrumBreadcrumb,
                      {
                        id: item.id,
                        href: item.href,
                      },
                      item.label,
                    ),
                  ),
                ),
        ],
      ),
    ],
  );
}

export default () => h(SolidSpectrumBreadcrumbsDemo, {});
