// apps/comparison/src/components/react/fixtures/styled/card.js
import { jsx, jsxs } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import {
  Card as SpectrumCard,
  CardPreview as SpectrumCardPreview,
  Content as SpectrumContent,
  Footer as SpectrumFooter,
  Image as SpectrumImage,
  Skeleton as SpectrumSkeleton,
  StatusLight as SpectrumStatusLight,
  Text as SpectrumText,
} from "@react-spectrum/s2";
import {
  cardDemoPropsFromWindow,
  normalizeCardDemoProps,
  serializeCardDemoProps,
  comparisonControlsEvent,
} from "@comparison/data/card-demo";
import { useComparisonResolvedTheme, renderReactSpectrumReference } from "../styled-shared.js";

const cardPreviewImageSrc =
  "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 320 180'%3E%3Crect width='320' height='180' fill='%232c7be5'/%3E%3Cpath d='M0 132 82 74l68 42 62-58 108 96v26H0z' fill='%23d6e9ff' opacity='.9'/%3E%3Ccircle cx='248' cy='48' r='24' fill='%23fff3b0'/%3E%3C/svg%3E";

function ReactCardDemo() {
  const [demoProps, setDemoProps] = useState(cardDemoPropsFromWindow);
  const colorScheme = useComparisonResolvedTheme();
  useEffect(() => {
    const handleControlsChange = (event) => {
      if (event instanceof CustomEvent && event.detail?.component === "card") {
        setDemoProps((current) => normalizeCardDemoProps({ ...current, ...event.detail.props }));
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    return () => window.removeEventListener(comparisonControlsEvent, handleControlsChange);
  }, []);

  const card = jsx(SpectrumCard, {
    size: demoProps.size,
    density: demoProps.density,
    variant: demoProps.variant,
    href: demoProps.href || undefined,
    target: demoProps.href ? "_blank" : undefined,
    rel: demoProps.href ? "noreferrer" : undefined,
    isDisabled: demoProps.isDisabled,
    textValue: demoProps.textValue,
    UNSAFE_style: { width: 240 },
    children: [
      demoProps.showPreview
        ? jsx(SpectrumCardPreview, {
            children: jsx(SpectrumImage, { src: cardPreviewImageSrc, alt: "" }),
          })
        : null,
      jsxs(SpectrumContent, {
        children: [
          jsx(SpectrumText, { slot: "title", children: demoProps.title }),
          jsx(SpectrumText, { slot: "description", children: demoProps.description }),
        ],
      }),
      demoProps.showFooter
        ? jsx(SpectrumFooter, {
            children: jsx(SpectrumStatusLight, { variant: "positive", children: "Synced" }),
          })
        : null,
    ],
  });

  return renderReactSpectrumReference(
    jsx("div", {
      "data-comparison-control-root": "card",
      "data-comparison-control-props": serializeCardDemoProps(demoProps),
      children: jsx(SpectrumSkeleton, {
        isLoading: demoProps.skeleton,
        children: card,
      }),
    }),
    colorScheme,
  );
}

export default () => jsx(ReactCardDemo, {});

// apps/comparison/src/components/solid/fixtures/styled/card.tsx
import h from "solid-js/h";
import { createSignal, onCleanup, onMount } from "solid-js";
import { hc } from "../../solid-h";
import {
  Card as SolidSpectrumCard,
  CardPreview as SolidSpectrumCardPreview,
} from "@proyecto-viviana/solid-spectrum/Card";
import { Content as SolidSpectrumContent } from "@proyecto-viviana/solid-spectrum/Content";
import { Footer as SolidSpectrumFooter } from "@proyecto-viviana/solid-spectrum/Footer";
import { Image as SolidSpectrumImage } from "@proyecto-viviana/solid-spectrum/Image";
import { Provider as SolidSpectrumProvider } from "@proyecto-viviana/solid-spectrum/Provider";
import { Skeleton as SolidSpectrumSkeleton } from "@proyecto-viviana/solid-spectrum/Skeleton";
import { StatusLight as SolidSpectrumStatusLight } from "@proyecto-viviana/solid-spectrum/StatusLight";
import { Text as SolidSpectrumText } from "@proyecto-viviana/solid-spectrum/Text";
import {
  cardDemoPropsFromWindow,
  normalizeCardDemoProps,
  serializeCardDemoProps,
  type CardDemoProps,
  comparisonControlsEvent,
} from "@comparison/data/card-demo";
import { createComparisonResolvedThemeSignal, providerShellStyle } from "../styled-shared.tsx";

const cardPreviewImageSrc =
  "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 320 180'%3E%3Crect width='320' height='180' fill='%232c7be5'/%3E%3Cpath d='M0 132 82 74l68 42 62-58 108 96v26H0z' fill='%23d6e9ff' opacity='.9'/%3E%3Ccircle cx='248' cy='48' r='24' fill='%23fff3b0'/%3E%3C/svg%3E";

function SolidSpectrumCardDemo() {
  const [demoProps, setDemoProps] = createSignal<CardDemoProps>(cardDemoPropsFromWindow());
  const colorScheme = createComparisonResolvedThemeSignal();

  onMount(() => {
    const handleControlsChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.component === "card") {
        setDemoProps((current) =>
          normalizeCardDemoProps({ ...current, ...(event.detail.props ?? {}) }),
        );
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    onCleanup(() => window.removeEventListener(comparisonControlsEvent, handleControlsChange));
  });

  return hc(
    SolidSpectrumProvider,
    {
      get colorScheme() {
        return colorScheme();
      },
      background: "base",
      style: providerShellStyle,
    },
    [
      hc(
        "div",
        {
          get "data-comparison-color-scheme"() {
            return colorScheme();
          },
          "data-comparison-control-root": "card",
          get "data-comparison-control-props"() {
            return serializeCardDemoProps(demoProps());
          },
        },
        [
          hc(
            SolidSpectrumSkeleton,
            {
              get isLoading() {
                return demoProps().skeleton;
              },
            },
            [
              hc(
                SolidSpectrumCard,
                {
                  get size() {
                    return demoProps().size;
                  },
                  get density() {
                    return demoProps().density;
                  },
                  get variant() {
                    return demoProps().variant;
                  },
                  get href() {
                    return demoProps().href || undefined;
                  },
                  get target() {
                    return demoProps().href ? "_blank" : undefined;
                  },
                  get rel() {
                    return demoProps().href ? "noreferrer" : undefined;
                  },
                  get isDisabled() {
                    return demoProps().isDisabled;
                  },
                  get textValue() {
                    return demoProps().textValue;
                  },
                  UNSAFE_style: { width: "240px" },
                },
                [
                  () => [
                    ...(demoProps().showPreview
                      ? [
                          hc(SolidSpectrumCardPreview, {}, [
                            hc(SolidSpectrumImage, { src: cardPreviewImageSrc, alt: "" }),
                          ]),
                        ]
                      : []),
                    hc(SolidSpectrumContent, {}, [
                      hc(SolidSpectrumText, { slot: "title" }, [() => demoProps().title]),
                      hc(SolidSpectrumText, { slot: "description" }, [
                        () => demoProps().description,
                      ]),
                    ]),
                    ...(demoProps().showFooter
                      ? [
                          hc(SolidSpectrumFooter, {}, [
                            hc(SolidSpectrumStatusLight, { variant: "positive" }, ["Synced"]),
                          ]),
                        ]
                      : []),
                  ],
                ],
              ),
            ],
          ),
        ],
      ),
    ],
  );
}

export default () => h(SolidSpectrumCardDemo, {});
