// apps/comparison/src/components/react/fixtures/styled/checkbox.js
import { jsx } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import { Checkbox as SpectrumCheckbox } from "@react-spectrum/s2";
import {
  checkboxDemoPropsFromWindow,
  initialCheckboxDemoSelected,
  normalizeCheckboxDemoProps,
  serializeCheckboxDemoProps,
  comparisonControlsEvent,
} from "@comparison/data/checkbox-demo";
import { useComparisonResolvedTheme, renderReactSpectrumReference } from "../styled-shared.js";

function ReactCheckboxDemo() {
  const [demoProps, setDemoProps] = useState(checkboxDemoPropsFromWindow);
  const [isSelected, setIsSelected] = useState(() => initialCheckboxDemoSelected(demoProps));
  const colorScheme = useComparisonResolvedTheme();
  useEffect(() => {
    const handleControlsChange = (event) => {
      if (event instanceof CustomEvent && event.detail?.component === "checkbox") {
        const nextProps = normalizeCheckboxDemoProps(event.detail.props);
        setDemoProps(nextProps);
        setIsSelected(initialCheckboxDemoSelected(nextProps));
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    return () => window.removeEventListener(comparisonControlsEvent, handleControlsChange);
  }, []);
  const selectionProps =
    demoProps.selectionSource === "defaultSelected"
      ? { defaultSelected: demoProps.defaultSelected }
      : { isSelected };
  const renderKey = [
    demoProps.selectionSource,
    demoProps.selectionSource === "defaultSelected" ? demoProps.defaultSelected : "controlled",
    demoProps.name,
    demoProps.value,
    demoProps.form,
    demoProps.validationBehavior,
    demoProps.isRequired,
  ].join("|");

  return renderReactSpectrumReference(
    jsx("div", {
      "data-comparison-checked": String(isSelected),
      children: jsx(
        SpectrumCheckbox,
        {
          "data-comparison-control-root": "checkbox",
          "data-comparison-control-props": serializeCheckboxDemoProps(demoProps),
          size: demoProps.size,
          ...selectionProps,
          isIndeterminate: demoProps.isIndeterminate,
          isEmphasized: demoProps.isEmphasized,
          name: demoProps.name || undefined,
          value: demoProps.value || undefined,
          form: demoProps.form || undefined,
          validationBehavior: demoProps.validationBehavior || undefined,
          isDisabled: demoProps.isDisabled,
          isReadOnly: demoProps.isReadOnly,
          isRequired: demoProps.isRequired,
          isInvalid: demoProps.isInvalid,
          onChange: (nextSelected) => {
            setIsSelected(nextSelected);
            setDemoProps((current) =>
              current.selectionSource === "isSelected"
                ? { ...current, isSelected: nextSelected }
                : current,
            );
          },
          children: demoProps.children,
        },
        renderKey,
      ),
    }),
    colorScheme,
  );
}

export default () => jsx(ReactCheckboxDemo, {});

// apps/comparison/src/components/solid/fixtures/styled/checkbox.tsx
import h from "@solidjs/h";
import { createMemo, createSignal, onSettled } from "solid-js";
import { createComponent } from "@solidjs/web";
import { hc, Keyed } from "../../solid-h";
import { Checkbox as SolidSpectrumCheckbox } from "@proyecto-viviana/solid-spectrum/Checkbox";
import { Provider as SolidSpectrumProvider } from "@proyecto-viviana/solid-spectrum/Provider";
import {
  checkboxDemoPropsFromWindow,
  initialCheckboxDemoSelected,
  normalizeCheckboxDemoProps,
  serializeCheckboxDemoProps,
  type CheckboxDemoProps,
  comparisonControlsEvent,
} from "@comparison/data/checkbox-demo";
import {
  comparisonThemeChangeEvent,
  getComparisonResolvedThemeFromDocument,
  type ComparisonResolvedTheme,
} from "@comparison/data/theme";
import { providerShellStyle } from "../styled-shared.tsx";

function SolidSpectrumCheckboxDemo() {
  const [demoProps, setDemoProps] = createSignal(checkboxDemoPropsFromWindow());
  const [isSelected, setIsSelected] = createSignal(initialCheckboxDemoSelected(demoProps()));
  const [colorScheme, setColorScheme] = createSignal<ComparisonResolvedTheme>(
    getComparisonResolvedThemeFromDocument(),
  );

  onSettled(() => {
    const handleControlsChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.component === "checkbox") {
        const nextProps = normalizeCheckboxDemoProps(event.detail.props ?? {});
        setDemoProps(nextProps);
        setIsSelected(initialCheckboxDemoSelected(nextProps));
      }
    };
    const handleThemeChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.resolvedTheme) {
        setColorScheme(event.detail.resolvedTheme as ComparisonResolvedTheme);
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    window.addEventListener(comparisonThemeChangeEvent, handleThemeChange);
    setColorScheme(getComparisonResolvedThemeFromDocument());
    return () => {
      window.removeEventListener(comparisonControlsEvent, handleControlsChange);
      window.removeEventListener(comparisonThemeChangeEvent, handleThemeChange);
    };
  });

  const serializedProps = createMemo(() => serializeCheckboxDemoProps(demoProps()));
  const renderKey = createMemo(() =>
    [
      demoProps().selectionSource,
      demoProps().selectionSource === "defaultSelected"
        ? demoProps().defaultSelected
        : "controlled",
      demoProps().name,
      demoProps().value,
      demoProps().form,
      demoProps().validationBehavior,
      demoProps().isRequired,
    ].join("|"),
  );

  return hc(
    SolidSpectrumProvider,
    {
      get colorScheme() {
        return colorScheme();
      },
      background: "base",
      style: providerShellStyle,
    },
    [
      () =>
        hc(
          "div",
          {
            get "data-comparison-color-scheme"() {
              return colorScheme();
            },
            get "data-comparison-checked"() {
              return String(isSelected());
            },
          },
          [
            createComponent(Keyed, {
              get when() {
                return renderKey();
              },
              children: (_key: string) =>
                hc(
                  SolidSpectrumCheckbox,
                  {
                    "data-comparison-control-root": "checkbox",
                    get "data-comparison-control-props"() {
                      return serializedProps();
                    },
                    get size() {
                      return demoProps().size;
                    },
                    get isSelected() {
                      return demoProps().selectionSource === "isSelected"
                        ? isSelected()
                        : undefined;
                    },
                    get defaultSelected() {
                      return demoProps().selectionSource === "defaultSelected"
                        ? demoProps().defaultSelected
                        : undefined;
                    },
                    get isIndeterminate() {
                      return demoProps().isIndeterminate;
                    },
                    get isEmphasized() {
                      return demoProps().isEmphasized;
                    },
                    get name() {
                      return demoProps().name || undefined;
                    },
                    get value() {
                      return demoProps().value || undefined;
                    },
                    get form() {
                      return demoProps().form || undefined;
                    },
                    get validationBehavior() {
                      return demoProps().validationBehavior || undefined;
                    },
                    get isDisabled() {
                      return demoProps().isDisabled;
                    },
                    get isReadOnly() {
                      return demoProps().isReadOnly;
                    },
                    get isRequired() {
                      return demoProps().isRequired;
                    },
                    get isInvalid() {
                      return demoProps().isInvalid;
                    },
                    onChange: (nextSelected: boolean) => {
                      setIsSelected(nextSelected);
                      setDemoProps((current: CheckboxDemoProps) =>
                        current.selectionSource === "isSelected"
                          ? { ...current, isSelected: nextSelected }
                          : current,
                      );
                    },
                  },
                  [() => demoProps().children],
                )(),
            }),
          ],
        ),
    ],
  );
}

export default () => h(SolidSpectrumCheckboxDemo, {});
