// apps/comparison/src/components/react/fixtures/styled/contextualhelp.js
import { jsx, jsxs } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import {
  ContextualHelp as SpectrumContextualHelp,
  Content as SpectrumContent,
  Footer as SpectrumFooter,
  Heading as SpectrumHeading,
  Link as SpectrumLink,
} from "@react-spectrum/s2";
import {
  contextualHelpDemoPropsFromWindow,
  isContextualHelpOpenControlChecked,
  normalizeContextualHelpDemoProps,
  serializeContextualHelpDemoProps,
  comparisonControlsEvent,
} from "@comparison/data/contextualhelp-demo";
import { useComparisonResolvedTheme, renderReactSpectrumReference } from "../styled-shared.js";

function ReactContextualHelpDemo() {
  const [demoProps, setDemoProps] = useState(contextualHelpDemoPropsFromWindow);
  const colorScheme = useComparisonResolvedTheme();

  useEffect(() => {
    const handleControlsChange = (event) => {
      if (event instanceof CustomEvent && event.detail?.component === "contextualhelp") {
        setDemoProps(normalizeContextualHelpDemoProps(event.detail.props ?? {}));
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    setDemoProps(contextualHelpDemoPropsFromWindow());
    return () => window.removeEventListener(comparisonControlsEvent, handleControlsChange);
  }, []);

  return renderReactSpectrumReference(
    jsx("div", {
      className: "comparison-button-row",
      "data-comparison-control-root": "contextualhelp",
      "data-comparison-control-props": serializeContextualHelpDemoProps(demoProps),
      children: jsxs(SpectrumContextualHelp, {
        "aria-label": demoProps.triggerLabel,
        containerPadding: demoProps.containerPadding,
        crossOffset: demoProps.crossOffset,
        isOpen: demoProps.isOpen,
        offset: demoProps.offset,
        onOpenChange: (nextOpen) => {
          setDemoProps((current) =>
            current.isOpen && !nextOpen && isContextualHelpOpenControlChecked()
              ? current
              : normalizeContextualHelpDemoProps({
                  ...current,
                  isOpen: nextOpen,
                }),
          );
        },
        placement: demoProps.placement,
        shouldFlip: demoProps.shouldFlip,
        size: demoProps.size,
        variant: demoProps.variant,
        children: [
          jsx(SpectrumHeading, { children: demoProps.heading }),
          jsx(SpectrumContent, { children: demoProps.content }),
          jsx(SpectrumFooter, {
            children: jsx(SpectrumLink, {
              isStandalone: true,
              href: "#",
              target: "_blank",
              children: "Learn more about segments",
            }),
          }),
        ],
      }),
    }),
    colorScheme,
  );
}

export default () => jsx(ReactContextualHelpDemo, {});

// apps/comparison/src/components/solid/fixtures/styled/contextualhelp.tsx
import h from "@solidjs/h";
import { createSignal, onSettled } from "solid-js";
import { hc } from "../../solid-h";
import { Content as SolidSpectrumContent } from "@proyecto-viviana/solid-spectrum/Content";
import { ContextualHelp as SolidSpectrumContextualHelp } from "@proyecto-viviana/solid-spectrum/ContextualHelp";
import { Footer as SolidSpectrumFooter } from "@proyecto-viviana/solid-spectrum/Footer";
import { Heading as SolidSpectrumHeading } from "@proyecto-viviana/solid-spectrum/Heading";
import { Link as SolidSpectrumLink } from "@proyecto-viviana/solid-spectrum/Link";
import { Provider as SolidSpectrumProvider } from "@proyecto-viviana/solid-spectrum/Provider";
import {
  contextualHelpDemoPropsFromWindow,
  isContextualHelpOpenControlChecked,
  normalizeContextualHelpDemoProps,
  serializeContextualHelpDemoProps,
  type ContextualHelpDemoProps,
  comparisonControlsEvent,
} from "@comparison/data/contextualhelp-demo";
import {
  comparisonThemeChangeEvent,
  getComparisonResolvedThemeFromDocument,
  type ComparisonResolvedTheme,
} from "@comparison/data/theme";
import { providerShellStyle } from "../styled-shared.tsx";

function SolidSpectrumContextualHelpDemo() {
  const [demoProps, setDemoProps] = createSignal<ContextualHelpDemoProps>(
    contextualHelpDemoPropsFromWindow(),
  );
  const [colorScheme, setColorScheme] = createSignal<ComparisonResolvedTheme>(
    getComparisonResolvedThemeFromDocument(),
  );

  onSettled(() => {
    const handleControlsChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.component === "contextualhelp") {
        setDemoProps(normalizeContextualHelpDemoProps(event.detail.props ?? {}));
      }
    };
    const handleThemeChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.resolvedTheme) {
        setColorScheme(event.detail.resolvedTheme as ComparisonResolvedTheme);
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    window.addEventListener(comparisonThemeChangeEvent, handleThemeChange);
    setDemoProps(contextualHelpDemoPropsFromWindow());
    setColorScheme(getComparisonResolvedThemeFromDocument());
    return () => {
      window.removeEventListener(comparisonControlsEvent, handleControlsChange);
      window.removeEventListener(comparisonThemeChangeEvent, handleThemeChange);
    };
  });

  return hc(
    SolidSpectrumProvider,
    {
      get colorScheme() {
        return colorScheme();
      },
      background: "base",
      style: providerShellStyle,
    },
    [
      hc(
        "div",
        {
          class: "comparison-button-row",
          "data-comparison-control-root": "contextualhelp",
          get "data-comparison-control-props"() {
            return serializeContextualHelpDemoProps(demoProps());
          },
        },
        [
          hc(
            SolidSpectrumContextualHelp,
            {
              get "aria-label"() {
                return demoProps().triggerLabel;
              },
              get containerPadding() {
                return demoProps().containerPadding;
              },
              get crossOffset() {
                return demoProps().crossOffset;
              },
              get isOpen() {
                return demoProps().isOpen;
              },
              get offset() {
                return demoProps().offset;
              },
              onOpenChange: (nextOpen: boolean) => {
                setDemoProps((current: ContextualHelpDemoProps) =>
                  current.isOpen && !nextOpen && isContextualHelpOpenControlChecked()
                    ? current
                    : normalizeContextualHelpDemoProps({
                        ...current,
                        isOpen: nextOpen,
                      }),
                );
              },
              get placement() {
                return demoProps().placement;
              },
              get shouldFlip() {
                return demoProps().shouldFlip;
              },
              get size() {
                return demoProps().size;
              },
              get variant() {
                return demoProps().variant;
              },
            },
            [
              hc(SolidSpectrumHeading, {}, [() => demoProps().heading]),
              hc(SolidSpectrumContent, {}, [() => demoProps().content]),
              hc(SolidSpectrumFooter, {}, [
                hc(SolidSpectrumLink, { isStandalone: true, href: "#", target: "_blank" }, [
                  "Learn more about segments",
                ]),
              ]),
            ],
          ),
        ],
      ),
    ],
  );
}

export default () => h(SolidSpectrumContextualHelpDemo, {});
