// apps/comparison/src/components/react/fixtures/styled/datefield.js
import { jsx, jsxs } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import {
  ContextualHelp as SpectrumContextualHelp,
  Content as SpectrumContent,
  Heading as SpectrumHeading,
} from "@react-spectrum/s2";
import { DateField as SpectrumDateField } from "@react-spectrum/s2/DateField";
import {
  dateFieldMaxValue,
  dateFieldMinValue,
  dateFieldDemoPropsFromWindow,
  dateFieldValueFromDemo,
  isDateFieldDateUnavailable,
  isDateFieldDemoValueInvalid,
  normalizeDateFieldDemoProps,
  serializeDateFieldDemoProps,
  serializeDateFieldValue,
  comparisonControlsEvent,
} from "@comparison/data/datefield-demo";
import { useComparisonResolvedTheme, renderReactSpectrumReference } from "../styled-shared.js";

function ReactDateFieldDemo() {
  const initialDemoProps = dateFieldDemoPropsFromWindow();
  const [demoProps, setDemoProps] = useState(() => initialDemoProps);
  const [value, setValue] = useState(() => dateFieldValueFromDemo(initialDemoProps));
  const colorScheme = useComparisonResolvedTheme();
  const serializedProps = serializeDateFieldDemoProps(demoProps);
  useEffect(() => {
    const handleControlsChange = (event) => {
      if (event instanceof CustomEvent && event.detail?.component === "datefield") {
        const nextProps = normalizeDateFieldDemoProps(event.detail.props ?? {});
        setDemoProps(nextProps);
        setValue(dateFieldValueFromDemo(nextProps));
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    return () => window.removeEventListener(comparisonControlsEvent, handleControlsChange);
  }, []);

  const contextualHelp = demoProps.withContextualHelp
    ? jsxs(SpectrumContextualHelp, {
        children: [
          jsx(SpectrumHeading, { slot: "title", children: "Date help" }),
          jsx(SpectrumContent, { children: "Choose an available appointment date." }),
        ],
      })
    : undefined;
  const isAriaBuiltinInvalid =
    demoProps.validationBehavior === "aria" && isDateFieldDemoValueInvalid(demoProps, value);
  const isInvalid = demoProps.isInvalid || isAriaBuiltinInvalid;

  return renderReactSpectrumReference(
    jsx("div", {
      "data-comparison-control-root": "datefield",
      "data-comparison-control-props": serializedProps,
      "data-comparison-react-builtin-invalid": String(isAriaBuiltinInvalid),
      "data-comparison-value": serializeDateFieldValue(value),
      "data-comparison-locale": demoProps.locale,
      "data-comparison-color-scheme": colorScheme,
      children: jsx(
        SpectrumDateField,
        {
          label: demoProps.label,
          size: demoProps.size,
          labelPosition: demoProps.labelPosition,
          labelAlign: demoProps.labelAlign,
          necessityIndicator: demoProps.necessityIndicator,
          contextualHelp,
          value: value ?? undefined,
          granularity: demoProps.granularity,
          shouldForceLeadingZeros: demoProps.shouldForceLeadingZeros,
          hourCycle: demoProps.hourCycle ? Number(demoProps.hourCycle) : undefined,
          hideTimeZone: demoProps.hideTimeZone,
          minValue: demoProps.constrainRange ? dateFieldMinValue(demoProps.granularity) : undefined,
          maxValue: demoProps.constrainRange ? dateFieldMaxValue(demoProps.granularity) : undefined,
          isDateUnavailable: demoProps.unavailableDates ? isDateFieldDateUnavailable : undefined,
          name: demoProps.name || undefined,
          form: demoProps.form || undefined,
          validationBehavior: demoProps.validationBehavior || undefined,
          description: demoProps.description,
          errorMessage: demoProps.errorMessage,
          isDisabled: demoProps.isDisabled,
          isReadOnly: demoProps.isReadOnly,
          isRequired: demoProps.isRequired,
          isInvalid,
          onChange: (nextValue) => setValue(nextValue),
          UNSAFE_className: "comparison-datefield-root",
        },
        serializedProps,
      ),
    }),
    colorScheme,
    demoProps.locale || void 0,
  );
}

export default () => jsx(ReactDateFieldDemo, {});

// apps/comparison/src/components/solid/fixtures/styled/datefield.tsx
import h from "@solidjs/h";
import { createMemo, createSignal, onSettled } from "solid-js";
import { hc } from "../../solid-h";
import { Content as SolidSpectrumContent } from "@proyecto-viviana/solid-spectrum/Content";
import { ContextualHelp as SolidSpectrumContextualHelp } from "@proyecto-viviana/solid-spectrum/ContextualHelp";
import { DateField as SolidSpectrumDateField } from "@proyecto-viviana/solid-spectrum/DateField";
import { Heading as SolidSpectrumHeading } from "@proyecto-viviana/solid-spectrum/Heading";
import { Provider as SolidSpectrumProvider } from "@proyecto-viviana/solid-spectrum/Provider";
import {
  dateFieldMaxValue,
  dateFieldMinValue,
  dateFieldDemoPropsFromWindow,
  dateFieldValueFromDemo,
  isDateFieldDateUnavailable,
  normalizeDateFieldDemoProps,
  serializeDateFieldDemoProps,
  serializeDateFieldValue,
  type DateFieldDemoProps,
  comparisonControlsEvent,
} from "@comparison/data/datefield-demo";
import {
  comparisonThemeChangeEvent,
  getComparisonResolvedThemeFromDocument,
  type ComparisonResolvedTheme,
} from "@comparison/data/theme";
import { providerShellStyle } from "../styled-shared.tsx";

function SolidSpectrumDateFieldDemo() {
  const initialDemoProps = dateFieldDemoPropsFromWindow();
  const [demoProps, setDemoProps] = createSignal<DateFieldDemoProps>(initialDemoProps);
  const [value, setValue] = createSignal(dateFieldValueFromDemo(initialDemoProps));
  const [colorScheme, setColorScheme] = createSignal<ComparisonResolvedTheme>(
    getComparisonResolvedThemeFromDocument(),
  );

  onSettled(() => {
    const handleControlsChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.component === "datefield") {
        const nextProps = normalizeDateFieldDemoProps(event.detail.props ?? {});
        setDemoProps(nextProps);
        setValue(() => dateFieldValueFromDemo(nextProps));
      }
    };
    const handleThemeChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.resolvedTheme) {
        setColorScheme(event.detail.resolvedTheme as ComparisonResolvedTheme);
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    window.addEventListener(comparisonThemeChangeEvent, handleThemeChange);
    setColorScheme(getComparisonResolvedThemeFromDocument());
    return () => {
      window.removeEventListener(comparisonControlsEvent, handleControlsChange);
      window.removeEventListener(comparisonThemeChangeEvent, handleThemeChange);
    };
  });

  const serializedProps = createMemo(() => serializeDateFieldDemoProps(demoProps()));
  const contextualHelp = createMemo(() =>
    demoProps().withContextualHelp
      ? hc(SolidSpectrumContextualHelp, {}, [
          hc(SolidSpectrumHeading, { slot: "title" }, ["Date help"]),
          hc(SolidSpectrumContent, {}, ["Choose an available appointment date."]),
        ])
      : undefined,
  );

  return hc(
    SolidSpectrumProvider,
    {
      get colorScheme() {
        return colorScheme();
      },
      get locale() {
        return demoProps().locale || undefined;
      },
      background: "base",
      style: providerShellStyle,
    },
    [
      hc(
        "div",
        {
          "data-comparison-control-root": "datefield",
          get "data-comparison-control-props"() {
            return serializedProps();
          },
          get "data-comparison-color-scheme"() {
            return colorScheme();
          },
          get "data-comparison-locale"() {
            return demoProps().locale;
          },
          get "data-comparison-value"() {
            return serializeDateFieldValue(value());
          },
        },
        [
          hc(SolidSpectrumDateField, {
            class: "comparison-datefield-root",
            get label() {
              return demoProps().label;
            },
            get size() {
              return demoProps().size;
            },
            get labelPosition() {
              return demoProps().labelPosition;
            },
            get labelAlign() {
              return demoProps().labelAlign;
            },
            get necessityIndicator() {
              return demoProps().necessityIndicator;
            },
            get contextualHelp() {
              return contextualHelp();
            },
            get value() {
              return value() ?? undefined;
            },
            get granularity() {
              return demoProps().granularity;
            },
            get shouldForceLeadingZeros() {
              return demoProps().shouldForceLeadingZeros;
            },
            get hourCycle() {
              return demoProps().hourCycle ? Number(demoProps().hourCycle) : undefined;
            },
            get hideTimeZone() {
              return demoProps().hideTimeZone;
            },
            get minValue() {
              return demoProps().constrainRange
                ? dateFieldMinValue(demoProps().granularity)
                : undefined;
            },
            get maxValue() {
              return demoProps().constrainRange
                ? dateFieldMaxValue(demoProps().granularity)
                : undefined;
            },
            get isDateUnavailable() {
              return demoProps().unavailableDates ? isDateFieldDateUnavailable : undefined;
            },
            get name() {
              return demoProps().name || undefined;
            },
            get form() {
              return demoProps().form || undefined;
            },
            get validationBehavior() {
              return demoProps().validationBehavior || undefined;
            },
            get description() {
              return demoProps().description;
            },
            get errorMessage() {
              return demoProps().errorMessage;
            },
            get isDisabled() {
              return demoProps().isDisabled;
            },
            get isReadOnly() {
              return demoProps().isReadOnly;
            },
            get isRequired() {
              return demoProps().isRequired;
            },
            get isInvalid() {
              return demoProps().isInvalid;
            },
            onChange: setValue,
          }),
        ],
      ),
    ],
  );
}

export default () => h(SolidSpectrumDateFieldDemo, {});
