// apps/comparison/src/components/react/fixtures/styled/illustratedmessage.js
import { jsx, jsxs } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import {
  Button as SpectrumButton,
  ButtonGroup as SpectrumButtonGroup,
  Content as SpectrumContent,
  Heading as SpectrumHeading,
  IllustratedMessage as SpectrumIllustratedMessage,
} from "@react-spectrum/s2";
import {
  illustratedMessageDemoPropsFromWindow,
  normalizeIllustratedMessageDemoProps,
  serializeIllustratedMessageDemoProps,
} from "@comparison/data/illustratedmessage-demo";
import { comparisonControlsEvent } from "@comparison/data/button-demo";
import {
  useComparisonResolvedTheme,
  renderReactSpectrumReference,
  ReactIllustratedMessageIllustration,
} from "../styled-shared.js";

function ReactIllustratedMessageDemo() {
  const colorScheme = useComparisonResolvedTheme();
  const [demoProps, setDemoProps] = useState(illustratedMessageDemoPropsFromWindow);
  useEffect(() => {
    const handleControlsChange = (event) => {
      if (event instanceof CustomEvent && event.detail?.component === "illustratedmessage") {
        setDemoProps(normalizeIllustratedMessageDemoProps(event.detail.props ?? {}));
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    return () => window.removeEventListener(comparisonControlsEvent, handleControlsChange);
  }, []);

  return renderReactSpectrumReference(
    jsx("div", {
      className: "comparison-illustrated-message-row",
      "data-comparison-color-scheme": colorScheme,
      children: jsxs(SpectrumIllustratedMessage, {
        "data-comparison-control-root": "illustratedmessage",
        "data-comparison-control-props": serializeIllustratedMessageDemoProps(demoProps),
        id: "illustratedmessage-route-root",
        role: "status",
        "aria-label": "Asset empty state",
        "aria-describedby": "illustratedmessage-route-description",
        "aria-details": "illustratedmessage-route-details",
        size: demoProps.size,
        orientation: demoProps.orientation,
        children: [
          jsx(ReactIllustratedMessageIllustration, { slot: "illustration" }),
          jsx(SpectrumHeading, { children: "Create your first asset" }),
          jsx(SpectrumContent, { children: "Upload or import a file to begin." }),
          jsx("span", {
            id: "illustratedmessage-route-description",
            hidden: true,
            children: "Illustrated empty-state guidance.",
          }),
          jsx("span", {
            id: "illustratedmessage-route-details",
            hidden: true,
            children: "The comparison route covers illustration, heading, content, and actions.",
          }),
          demoProps.withActions
            ? jsxs(SpectrumButtonGroup, {
                children: [
                  jsx(SpectrumButton, { variant: "secondary", children: "Import" }),
                  jsx(SpectrumButton, { variant: "accent", children: "Upload" }),
                ],
              })
            : null,
        ],
      }),
    }),
    colorScheme,
  );
}

export default () => jsx(ReactIllustratedMessageDemo, {});

// apps/comparison/src/components/solid/fixtures/styled/illustratedmessage.tsx
import h from "solid-js/h";
import { createMemo, createSignal, onCleanup, onMount } from "solid-js";
import { hc } from "../../solid-h";
import { Button as SolidSpectrumButton } from "@proyecto-viviana/solid-spectrum/Button";
import { ButtonGroup as SolidSpectrumButtonGroup } from "@proyecto-viviana/solid-spectrum/ButtonGroup";
import { Content as SolidSpectrumContent } from "@proyecto-viviana/solid-spectrum/Content";
import { Heading as SolidSpectrumHeading } from "@proyecto-viviana/solid-spectrum/Heading";
import { IllustratedMessage as SolidSpectrumIllustratedMessage } from "@proyecto-viviana/solid-spectrum/IllustratedMessage";
import { Provider as SolidSpectrumProvider } from "@proyecto-viviana/solid-spectrum/Provider";
import {
  illustratedMessageDemoPropsFromWindow,
  normalizeIllustratedMessageDemoProps,
  serializeIllustratedMessageDemoProps,
  type IllustratedMessageDemoProps,
} from "@comparison/data/illustratedmessage-demo";
import { comparisonControlsEvent } from "@comparison/data/button-demo";
import {
  comparisonThemeChangeEvent,
  getComparisonResolvedThemeFromDocument,
  type ComparisonResolvedTheme,
} from "@comparison/data/theme";
import { SolidIllustratedMessageIllustration, providerShellStyle } from "../styled-shared.tsx";

function SolidSpectrumIllustratedMessageDemo() {
  const [demoProps, setDemoProps] = createSignal<IllustratedMessageDemoProps>(
    illustratedMessageDemoPropsFromWindow(),
  );
  const [colorScheme, setColorScheme] = createSignal<ComparisonResolvedTheme>(
    getComparisonResolvedThemeFromDocument(),
  );

  onMount(() => {
    const handleControlsChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.component === "illustratedmessage") {
        setDemoProps(normalizeIllustratedMessageDemoProps(event.detail.props ?? {}));
      }
    };
    const handleThemeChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.resolvedTheme) {
        setColorScheme(event.detail.resolvedTheme as ComparisonResolvedTheme);
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    window.addEventListener(comparisonThemeChangeEvent, handleThemeChange);
    setColorScheme(getComparisonResolvedThemeFromDocument());
    onCleanup(() => {
      window.removeEventListener(comparisonControlsEvent, handleControlsChange);
      window.removeEventListener(comparisonThemeChangeEvent, handleThemeChange);
    });
  });

  const renderedMessage = createMemo(() =>
    hc(SolidSpectrumIllustratedMessage, {
      "data-comparison-control-root": "illustratedmessage",
      get "data-comparison-control-props"() {
        return serializeIllustratedMessageDemoProps(demoProps());
      },
      id: "illustratedmessage-route-root",
      role: "status",
      "aria-label": "Asset empty state",
      "aria-describedby": "illustratedmessage-route-description",
      "aria-details": "illustratedmessage-route-details",
      get size() {
        return demoProps().size;
      },
      get orientation() {
        return demoProps().orientation;
      },
      get children() {
        const children = [
          h(SolidIllustratedMessageIllustration, { slot: "illustration" }),
          h(SolidSpectrumHeading, {}, "Create your first asset"),
          h(SolidSpectrumContent, {}, "Upload or import a file to begin."),
          h(
            "span",
            {
              id: "illustratedmessage-route-description",
              hidden: true,
            },
            "Illustrated empty-state guidance.",
          ),
          h(
            "span",
            {
              id: "illustratedmessage-route-details",
              hidden: true,
            },
            "The comparison route covers illustration, heading, content, and actions.",
          ),
        ];

        if (demoProps().withActions) {
          children.push(
            hc(SolidSpectrumButtonGroup, {}, [
              h(SolidSpectrumButton, { variant: "secondary" }, "Import"),
              h(SolidSpectrumButton, { variant: "accent" }, "Upload"),
            ]),
          );
        }

        return children;
      },
    }),
  );

  return hc(
    SolidSpectrumProvider,
    {
      get colorScheme() {
        return colorScheme();
      },
      background: "base",
      style: providerShellStyle,
    },
    [
      hc(
        "div",
        {
          class: "comparison-illustrated-message-row",
          get "data-comparison-color-scheme"() {
            return colorScheme();
          },
        },
        [renderedMessage],
      ),
    ],
  );
}

export default () => h(SolidSpectrumIllustratedMessageDemo, {});
