// apps/comparison/src/components/react/fixtures/styled/menu.js
import { jsx, jsxs } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import {
  ActionButton as SpectrumActionButton,
  Keyboard as SpectrumKeyboard,
  Menu as SpectrumMenu,
  MenuItem as SpectrumMenuItem,
  MenuTrigger as SpectrumMenuTrigger,
  Text as SpectrumText,
} from "@react-spectrum/s2";
import {
  defaultMenuSelectedKeys,
  menuDemoPropsFromWindow,
  menuItems,
  normalizeMenuDemoProps,
  serializeMenuDemoProps,
  serializeMenuSelectedKeys,
  comparisonControlsEvent,
} from "@comparison/data/menu-demo";
import {
  useComparisonResolvedTheme,
  renderReactSpectrumReference,
  ReactButtonIcon,
} from "../styled-shared.js";

function ReactMenuDemo() {
  const colorScheme = useComparisonResolvedTheme();
  const [demoProps, setDemoProps] = useState(menuDemoPropsFromWindow);
  const [selectedKeys, setSelectedKeys] = useState(() =>
    defaultMenuSelectedKeys(menuDemoPropsFromWindow().selectionMode),
  );
  const [actionCount, setActionCount] = useState(0);
  const [lastAction, setLastAction] = useState("");
  const [openChangeCount, setOpenChangeCount] = useState(0);
  const [lastOpenState, setLastOpenState] = useState("false");
  const [selectionChangeCount, setSelectionChangeCount] = useState(0);

  useEffect(() => {
    const handleControlsChange = (event) => {
      if (event instanceof CustomEvent && event.detail?.component === "menu") {
        const nextProps = normalizeMenuDemoProps(event.detail.props ?? {});
        setDemoProps(nextProps);
        setSelectedKeys(defaultMenuSelectedKeys(nextProps.selectionMode));
        setActionCount(0);
        setLastAction("");
        setOpenChangeCount(0);
        setLastOpenState("false");
        setSelectionChangeCount(0);
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    return () => window.removeEventListener(comparisonControlsEvent, handleControlsChange);
  }, []);

  const handleSelectionChange = (keys) => {
    const nextKeys =
      keys === "all"
        ? new Set(menuItems.map((item) => item.id))
        : new Set(Array.from(keys).map(String));
    setSelectedKeys(nextKeys);
    setSelectionChangeCount((count) => count + 1);
  };
  const selectionProps =
    demoProps.selectionMode === "none"
      ? {}
      : {
          selectionMode: demoProps.selectionMode,
          selectedKeys,
          onSelectionChange: handleSelectionChange,
        };

  return renderReactSpectrumReference(
    jsx("div", {
      className: "comparison-menu-row",
      "data-comparison-control-root": "menu",
      "data-comparison-control-props": serializeMenuDemoProps(demoProps),
      "data-comparison-menu-props": serializeMenuDemoProps(demoProps),
      "data-comparison-action-count": String(actionCount),
      "data-comparison-last-action": lastAction,
      "data-comparison-open-change-count": String(openChangeCount),
      "data-comparison-last-open-state": lastOpenState,
      "data-comparison-selection-change-count": String(selectionChangeCount),
      "data-comparison-selected-keys": serializeMenuSelectedKeys(selectedKeys),
      children: jsxs(SpectrumMenuTrigger, {
        align: demoProps.align,
        direction: demoProps.direction,
        shouldFlip: demoProps.shouldFlip,
        onOpenChange: (isOpen) => {
          setOpenChangeCount((count) => count + 1);
          setLastOpenState(String(isOpen));
        },
        children: [
          jsx(SpectrumActionButton, {
            size: demoProps.triggerSize,
            isDisabled: demoProps.isDisabled,
            "aria-label": "Layer actions",
            children: "Layer actions",
          }),
          jsx(SpectrumMenu, {
            size: demoProps.size,
            "aria-label": "Layer actions",
            onAction: (key) => {
              setActionCount((count) => count + 1);
              setLastAction(String(key));
            },
            ...selectionProps,
            children: menuItems.map((item) =>
              jsxs(
                SpectrumMenuItem,
                {
                  id: item.id,
                  textValue: item.label,
                  children: [
                    jsx(ReactButtonIcon, { "aria-hidden": "true" }),
                    jsx(SpectrumText, { slot: "label", children: item.label }),
                    jsx(SpectrumText, { slot: "description", children: item.description }),
                    jsx(SpectrumKeyboard, { children: item.shortcut }),
                  ],
                },
                item.id,
              ),
            ),
          }),
        ],
      }),
    }),
    colorScheme,
  );
}

export default () => jsx(ReactMenuDemo, {});

// apps/comparison/src/components/solid/fixtures/styled/menu.tsx
import h from "@solidjs/h";
import { createSignal, onSettled } from "solid-js";
import { hc } from "../../solid-h";
import { ActionButton as SolidSpectrumActionButton } from "@proyecto-viviana/solid-spectrum/ActionButton";
import { Keyboard as SolidSpectrumKeyboard } from "@proyecto-viviana/solid-spectrum/Keyboard";
import {
  Menu as SolidSpectrumMenu,
  MenuItem as SolidSpectrumMenuItem,
  MenuTrigger as SolidSpectrumMenuTrigger,
} from "@proyecto-viviana/solid-spectrum/Menu";
import { Provider as SolidSpectrumProvider } from "@proyecto-viviana/solid-spectrum/Provider";
import { Text as SolidSpectrumText } from "@proyecto-viviana/solid-spectrum/Text";
import {
  defaultMenuSelectedKeys,
  menuDemoPropsFromWindow,
  menuItems,
  normalizeMenuDemoProps,
  serializeMenuDemoProps,
  serializeMenuSelectedKeys,
  type MenuDemoProps,
  comparisonControlsEvent,
} from "@comparison/data/menu-demo";
import {
  comparisonThemeChangeEvent,
  getComparisonResolvedThemeFromDocument,
  type ComparisonResolvedTheme,
} from "@comparison/data/theme";
import { providerShellStyle, SolidNewIcon } from "../styled-shared.tsx";

function SolidSpectrumMenuDemo() {
  const [demoProps, setDemoProps] = createSignal<MenuDemoProps>(menuDemoPropsFromWindow());
  const [selectedKeys, setSelectedKeys] = createSignal<Set<string>>(
    defaultMenuSelectedKeys(menuDemoPropsFromWindow().selectionMode),
  );
  const [actionCount, setActionCount] = createSignal(0);
  const [lastAction, setLastAction] = createSignal("");
  const [openChangeCount, setOpenChangeCount] = createSignal(0);
  const [lastOpenState, setLastOpenState] = createSignal("false");
  const [selectionChangeCount, setSelectionChangeCount] = createSignal(0);
  const [colorScheme, setColorScheme] = createSignal<ComparisonResolvedTheme>(
    getComparisonResolvedThemeFromDocument(),
  );

  onSettled(() => {
    const handleControlsChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.component === "menu") {
        const nextProps = normalizeMenuDemoProps(event.detail.props ?? {});
        setDemoProps(nextProps);
        setSelectedKeys(defaultMenuSelectedKeys(nextProps.selectionMode));
        setActionCount(0);
        setLastAction("");
        setOpenChangeCount(0);
        setLastOpenState("false");
        setSelectionChangeCount(0);
      }
    };
    const handleThemeChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.resolvedTheme) {
        setColorScheme(event.detail.resolvedTheme as ComparisonResolvedTheme);
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    window.addEventListener(comparisonThemeChangeEvent, handleThemeChange);
    setColorScheme(getComparisonResolvedThemeFromDocument());
    return () => {
      window.removeEventListener(comparisonControlsEvent, handleControlsChange);
      window.removeEventListener(comparisonThemeChangeEvent, handleThemeChange);
    };
  });

  const activeSelectionMode = () =>
    demoProps().selectionMode === "none" ? undefined : demoProps().selectionMode;
  const handleSelectionChange = (keys: unknown) => {
    const nextKeys =
      keys === "all"
        ? new Set(menuItems.map((item) => item.id))
        : new Set(Array.from(keys as Iterable<unknown>).map(String));
    setSelectedKeys(nextKeys);
    setSelectionChangeCount((count) => count + 1);
  };

  return hc(
    SolidSpectrumProvider,
    {
      get colorScheme() {
        return colorScheme();
      },
      background: "base",
      style: providerShellStyle,
    },
    [
      hc(
        "div",
        {
          class: "comparison-menu-row",
          "data-comparison-control-root": "menu",
          get "data-comparison-control-props"() {
            return serializeMenuDemoProps(demoProps());
          },
          get "data-comparison-menu-props"() {
            return serializeMenuDemoProps(demoProps());
          },
          get "data-comparison-action-count"() {
            return String(actionCount());
          },
          get "data-comparison-last-action"() {
            return lastAction();
          },
          get "data-comparison-open-change-count"() {
            return String(openChangeCount());
          },
          get "data-comparison-last-open-state"() {
            return lastOpenState();
          },
          get "data-comparison-selection-change-count"() {
            return String(selectionChangeCount());
          },
          get "data-comparison-selected-keys"() {
            return serializeMenuSelectedKeys(selectedKeys());
          },
        },
        [
          hc(
            SolidSpectrumMenuTrigger,
            {
              get align() {
                return demoProps().align;
              },
              get direction() {
                return demoProps().direction;
              },
              get shouldFlip() {
                return demoProps().shouldFlip;
              },
              onOpenChange: (isOpen: boolean) => {
                setOpenChangeCount((count) => count + 1);
                setLastOpenState(String(isOpen));
              },
            },
            [
              h(
                SolidSpectrumActionButton,
                {
                  get size() {
                    return demoProps().triggerSize;
                  },
                  get isDisabled() {
                    return demoProps().isDisabled;
                  },
                  "aria-label": "Layer actions",
                },
                "Layer actions",
              ),
              hc(
                SolidSpectrumMenu,
                {
                  get size() {
                    return demoProps().size;
                  },
                  "aria-label": "Layer actions",
                  get selectionMode() {
                    return activeSelectionMode();
                  },
                  get selectedKeys() {
                    return activeSelectionMode() ? selectedKeys() : undefined;
                  },
                  onSelectionChange: handleSelectionChange,
                  onAction: (key: unknown) => {
                    setActionCount((count) => count + 1);
                    setLastAction(String(key));
                  },
                },
                [
                  () =>
                    menuItems.map((item) =>
                      hc(
                        SolidSpectrumMenuItem,
                        {
                          id: item.id,
                          textValue: item.label,
                        },
                        [
                          () => [
                            h(SolidNewIcon, { "aria-hidden": "true" }),
                            h(SolidSpectrumText, { slot: "label" }, item.label),
                            h(SolidSpectrumText, { slot: "description" }, item.description),
                            h(SolidSpectrumKeyboard, {}, item.shortcut),
                          ],
                        ],
                      ),
                    ),
                ],
              ),
            ],
          ),
        ],
      ),
    ],
  );
}

export default () => h(SolidSpectrumMenuDemo, {});
