// apps/comparison/src/components/react/fixtures/styled/progresscircle.js
import { jsx } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import { ProgressCircle as SpectrumProgressCircle } from "@react-spectrum/s2";
import { comparisonControlsEvent } from "@comparison/data/button-demo";
import {
  normalizeProgressCircleDemoProps,
  progressCircleDemoPropsFromWindow,
  serializeProgressCircleDemoProps,
} from "@comparison/data/progress-demo";
import {
  useComparisonResolvedTheme,
  renderReactSpectrumReference,
  staticColorBackdropProps,
} from "../styled-shared.js";

function ReactProgressCircleDemo() {
  const colorScheme = useComparisonResolvedTheme();
  const [demoProps, setDemoProps] = useState(progressCircleDemoPropsFromWindow);
  useEffect(() => {
    const handleControlsChange = (event) => {
      if (event instanceof CustomEvent && event.detail?.component === "progresscircle") {
        setDemoProps(normalizeProgressCircleDemoProps(event.detail.props ?? {}));
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    return () => window.removeEventListener(comparisonControlsEvent, handleControlsChange);
  }, []);

  return renderReactSpectrumReference(
    jsx("div", {
      ...staticColorBackdropProps(demoProps.staticColor, "comparison-progresscircle-row"),
      style: progressCircleRowStyle,
      "data-comparison-control-root": "progresscircle",
      "data-comparison-control-props": serializeProgressCircleDemoProps(demoProps),
      children: jsx(SpectrumProgressCircle, {
        "aria-label": demoProps.ariaLabel,
        value: demoProps.value,
        minValue: demoProps.minValue,
        maxValue: demoProps.maxValue,
        size: demoProps.size,
        staticColor: demoProps.staticColor || undefined,
        isIndeterminate: demoProps.isIndeterminate,
        "data-comparison-progresscircle": "controlled",
      }),
    }),
    colorScheme,
  );
}

const progressCircleRowStyle = {
  display: "flex",
  alignItems: "center",
  gap: 24,
  padding: 12,
};

export default () => jsx(ReactProgressCircleDemo, {});

// apps/comparison/src/components/solid/fixtures/styled/progresscircle.tsx
import h from "solid-js/h";
import { createSignal, onCleanup, onMount } from "solid-js";
import { hc } from "../../solid-h";
import { ProgressCircle as SolidSpectrumProgressCircle } from "@proyecto-viviana/solid-spectrum/ProgressCircle";
import { Provider as SolidSpectrumProvider } from "@proyecto-viviana/solid-spectrum/Provider";
import { comparisonControlsEvent } from "@comparison/data/button-demo";
import {
  normalizeProgressCircleDemoProps,
  progressCircleDemoPropsFromWindow,
  serializeProgressCircleDemoProps,
  type ProgressCircleDemoProps,
} from "@comparison/data/progress-demo";
import {
  createComparisonResolvedThemeSignal,
  providerShellStyle,
  staticColorBackdropClass,
  staticColorBackdropValue,
} from "../styled-shared.tsx";

function SolidSpectrumProgressCircleDemo() {
  const colorScheme = createComparisonResolvedThemeSignal();
  const [demoProps, setDemoProps] = createSignal<ProgressCircleDemoProps>(
    progressCircleDemoPropsFromWindow(),
  );

  onMount(() => {
    const handleControlsChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.component === "progresscircle") {
        setDemoProps(normalizeProgressCircleDemoProps(event.detail.props ?? {}));
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    onCleanup(() => window.removeEventListener(comparisonControlsEvent, handleControlsChange));
  });

  return hc(
    SolidSpectrumProvider,
    {
      get colorScheme() {
        return colorScheme();
      },
      background: "base",
      style: providerShellStyle,
    },
    [
      hc(
        "div",
        {
          get class() {
            return staticColorBackdropClass(
              demoProps().staticColor,
              "comparison-progresscircle-row",
            );
          },
          get "data-comparison-static-color"() {
            return staticColorBackdropValue(demoProps().staticColor);
          },
          style: progressCircleRowStyle,
          "data-comparison-control-root": "progresscircle",
          get "data-comparison-control-props"() {
            return serializeProgressCircleDemoProps(demoProps());
          },
        },
        [
          h(SolidSpectrumProgressCircle, {
            get "aria-label"() {
              return demoProps().ariaLabel;
            },
            get value() {
              return demoProps().value;
            },
            get minValue() {
              return demoProps().minValue;
            },
            get maxValue() {
              return demoProps().maxValue;
            },
            get size() {
              return demoProps().size;
            },
            get staticColor() {
              return demoProps().staticColor || undefined;
            },
            get isIndeterminate() {
              return demoProps().isIndeterminate;
            },
            "data-comparison-progresscircle": "controlled",
          }),
        ],
      ),
    ],
  );
}

const progressCircleRowStyle = {
  display: "flex",
  "align-items": "center",
  gap: "24px",
  padding: "12px",
};

export default () => h(SolidSpectrumProgressCircleDemo, {});
