// apps/comparison/src/components/react/fixtures/styled/progressbar.js
import { jsx } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import { ProgressBar as SpectrumProgressBar } from "@react-spectrum/s2";
import { comparisonControlsEvent } from "@comparison/data/button-demo";
import {
  progressBarFormatOptionsForPreset,
  normalizeProgressBarDemoProps,
  progressBarDemoPropsFromWindow,
  serializeProgressBarDemoProps,
} from "@comparison/data/progress-demo";
import {
  useComparisonResolvedTheme,
  renderReactSpectrumReference,
  staticColorBackdropProps,
} from "../styled-shared.js";

function ReactProgressBarDemo() {
  const colorScheme = useComparisonResolvedTheme();
  const [demoProps, setDemoProps] = useState(progressBarDemoPropsFromWindow);
  useEffect(() => {
    const handleControlsChange = (event) => {
      if (event instanceof CustomEvent && event.detail?.component === "progressbar") {
        setDemoProps(normalizeProgressBarDemoProps(event.detail.props ?? {}));
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    return () => window.removeEventListener(comparisonControlsEvent, handleControlsChange);
  }, []);

  return renderReactSpectrumReference(
    jsx("div", {
      ...staticColorBackdropProps(demoProps.staticColor, "comparison-progressbar-row"),
      style: progressFixtureStackStyle,
      "data-comparison-control-root": "progressbar",
      "data-comparison-control-props": serializeProgressBarDemoProps(demoProps),
      children: jsx(SpectrumProgressBar, {
        label: demoProps.label,
        value: demoProps.value,
        minValue: demoProps.minValue,
        maxValue: demoProps.maxValue,
        valueLabel: demoProps.valueLabel || undefined,
        formatOptions: progressBarFormatOptionsForPreset(demoProps.formatOptions),
        size: demoProps.size,
        staticColor: demoProps.staticColor || undefined,
        labelPosition: demoProps.labelPosition,
        isIndeterminate: demoProps.isIndeterminate,
        "data-comparison-progressbar": "controlled",
      }),
    }),
    colorScheme,
  );
}

const progressFixtureStackStyle = {
  display: "flex",
  flexDirection: "column",
  gap: 24,
  width: 360,
  padding: 12,
};

export default () => jsx(ReactProgressBarDemo, {});

// apps/comparison/src/components/solid/fixtures/styled/progressbar.tsx
import h from "solid-js/h";
import { createSignal, onCleanup, onMount } from "solid-js";
import { hc } from "../../solid-h";
import { ProgressBar as SolidSpectrumProgressBar } from "@proyecto-viviana/solid-spectrum/ProgressBar";
import { Provider as SolidSpectrumProvider } from "@proyecto-viviana/solid-spectrum/Provider";
import { comparisonControlsEvent } from "@comparison/data/button-demo";
import {
  progressBarFormatOptionsForPreset,
  normalizeProgressBarDemoProps,
  progressBarDemoPropsFromWindow,
  serializeProgressBarDemoProps,
  type ProgressBarDemoProps,
} from "@comparison/data/progress-demo";
import {
  createComparisonResolvedThemeSignal,
  providerShellStyle,
  staticColorBackdropClass,
  staticColorBackdropValue,
} from "../styled-shared.tsx";

function SolidSpectrumProgressBarDemo() {
  const colorScheme = createComparisonResolvedThemeSignal();
  const [demoProps, setDemoProps] = createSignal<ProgressBarDemoProps>(
    progressBarDemoPropsFromWindow(),
  );

  onMount(() => {
    const handleControlsChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.component === "progressbar") {
        setDemoProps(normalizeProgressBarDemoProps(event.detail.props ?? {}));
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    onCleanup(() => window.removeEventListener(comparisonControlsEvent, handleControlsChange));
  });

  return hc(
    SolidSpectrumProvider,
    {
      get colorScheme() {
        return colorScheme();
      },
      background: "base",
      style: providerShellStyle,
    },
    [
      hc(
        "div",
        {
          get class() {
            return staticColorBackdropClass(demoProps().staticColor, "comparison-progressbar-row");
          },
          get "data-comparison-static-color"() {
            return staticColorBackdropValue(demoProps().staticColor);
          },
          style: progressFixtureStackStyle,
          "data-comparison-control-root": "progressbar",
          get "data-comparison-control-props"() {
            return serializeProgressBarDemoProps(demoProps());
          },
        },
        [
          h(SolidSpectrumProgressBar, {
            get label() {
              return demoProps().label;
            },
            get value() {
              return demoProps().value;
            },
            get minValue() {
              return demoProps().minValue;
            },
            get maxValue() {
              return demoProps().maxValue;
            },
            get valueLabel() {
              return demoProps().valueLabel || undefined;
            },
            get formatOptions() {
              return progressBarFormatOptionsForPreset(demoProps().formatOptions);
            },
            get size() {
              return demoProps().size;
            },
            get staticColor() {
              return demoProps().staticColor || undefined;
            },
            get labelPosition() {
              return demoProps().labelPosition;
            },
            get isIndeterminate() {
              return demoProps().isIndeterminate;
            },
            "data-comparison-progressbar": "controlled",
          }),
        ],
      ),
    ],
  );
}

const progressFixtureStackStyle = {
  display: "flex",
  "flex-direction": "column",
  gap: "24px",
  width: "360px",
  padding: "12px",
};

export default () => h(SolidSpectrumProgressBarDemo, {});
