// apps/comparison/src/components/react/fixtures/styled/rangecalendar.js
import { jsx } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import { RangeCalendar as SpectrumRangeCalendar } from "@react-spectrum/s2";
import { calendarCreateCalendarForDemo } from "@comparison/data/calendar-demo";
import {
  comparisonControlsEvent as rangeCalendarControlsEvent,
  isRangeCalendarDateUnavailable,
  normalizeRangeCalendarDemoProps,
  rangeCalendarDateFromString,
  rangeCalendarDemoPropsFromWindow,
  rangeCalendarMaxValue,
  rangeCalendarMinValue,
  rangeCalendarValueFromDemo,
  rangeCalendarVisibleMonthsFromString,
  serializeRangeCalendarDemoProps,
  serializeRangeCalendarValue,
} from "@comparison/data/rangecalendar-demo";
import { useComparisonResolvedTheme, renderReactSpectrumReference } from "../styled-shared.js";

function ReactRangeCalendarDemo() {
  const initialDemoProps = rangeCalendarDemoPropsFromWindow();
  const [demoProps, setDemoProps] = useState(() => initialDemoProps);
  const [value, setValue] = useState(() => rangeCalendarValueFromDemo(initialDemoProps));
  const [focusedValue, setFocusedValue] = useState(() =>
    rangeCalendarDateFromString(initialDemoProps.focusedValue || initialDemoProps.startValue),
  );
  const colorScheme = useComparisonResolvedTheme();

  useEffect(() => {
    const handleControlsChange = (event) => {
      if (event instanceof CustomEvent && event.detail?.component === "rangecalendar") {
        setDemoProps((currentProps) => {
          const nextProps = normalizeRangeCalendarDemoProps({
            ...currentProps,
            ...(event.detail.props ?? {}),
          });
          setValue(rangeCalendarValueFromDemo(nextProps));
          setFocusedValue(
            rangeCalendarDateFromString(nextProps.focusedValue || nextProps.startValue),
          );
          return nextProps;
        });
      }
    };
    window.addEventListener(rangeCalendarControlsEvent, handleControlsChange);
    return () => window.removeEventListener(rangeCalendarControlsEvent, handleControlsChange);
  }, []);

  const selectedValue = value;
  const visibleMonths = rangeCalendarVisibleMonthsFromString(demoProps.visibleMonths);
  const resolvedVisibleMonths = visibleMonths ?? 1;
  const calendarReferenceWidth = `${resolvedVisibleMonths * 224 + (resolvedVisibleMonths - 1) * 24}px`;
  const rangeCalendarProps = {
    "aria-label": "Trip dates",
    value: selectedValue ?? undefined,
    onChange: (nextValue) => setValue(nextValue),
    minValue: demoProps.constrainRange ? rangeCalendarMinValue : undefined,
    maxValue: demoProps.constrainRange ? rangeCalendarMaxValue : undefined,
    isDateUnavailable: demoProps.unavailableDates ? isRangeCalendarDateUnavailable : undefined,
    allowsNonContiguousRanges: demoProps.allowsNonContiguousRanges,
    isDisabled: demoProps.isDisabled,
    isReadOnly: demoProps.isReadOnly,
    isInvalid: demoProps.isInvalid,
    errorMessage: demoProps.errorMessage,
    firstDayOfWeek: demoProps.firstDayOfWeek || undefined,
    visibleMonths,
    pageBehavior: demoProps.pageBehavior || undefined,
    selectionAlignment: demoProps.selectionAlignment || undefined,
    createCalendar: calendarCreateCalendarForDemo(demoProps.calendarSystem),
    focusedValue: demoProps.focusedValue ? (focusedValue ?? undefined) : undefined,
    onFocusChange: (nextFocusedValue) => setFocusedValue(nextFocusedValue),
    UNSAFE_className: "comparison-rangecalendar-root",
    UNSAFE_style: {
      "--cell-responsive-size": "32px",
      width: calendarReferenceWidth,
      maxWidth: "100%",
    },
  };

  return renderReactSpectrumReference(
    jsx("div", {
      "data-comparison-control-root": "rangecalendar",
      "data-comparison-control-props": serializeRangeCalendarDemoProps(demoProps),
      "data-comparison-value": serializeRangeCalendarValue(selectedValue),
      "data-comparison-focused-value": focusedValue ? String(focusedValue) : "",
      "data-comparison-color-scheme": colorScheme,
      "data-comparison-locale": demoProps.locale,
      "data-comparison-calendar-system": demoProps.calendarSystem,
      children: jsx(SpectrumRangeCalendar, rangeCalendarProps),
    }),
    colorScheme,
    demoProps.locale || undefined,
  );
}

export default () => jsx(ReactRangeCalendarDemo, {});

// apps/comparison/src/components/solid/fixtures/styled/rangecalendar.tsx
import h from "solid-js/h";
import { createMemo, createSignal, onCleanup, onMount } from "solid-js";
import { hc } from "../../solid-h";
import {
  Provider as SolidSpectrumProvider,
  RangeCalendar as SolidSpectrumRangeCalendar,
} from "@proyecto-viviana/solid-spectrum";
import { calendarCreateCalendarForDemo } from "@comparison/data/calendar-demo";
import {
  comparisonControlsEvent as rangeCalendarControlsEvent,
  isRangeCalendarDateUnavailable,
  normalizeRangeCalendarDemoProps,
  rangeCalendarDateFromString,
  rangeCalendarDemoPropsFromWindow,
  rangeCalendarMaxValue,
  rangeCalendarMinValue,
  rangeCalendarValueFromDemo,
  rangeCalendarVisibleMonthsFromString,
  serializeRangeCalendarDemoProps,
  serializeRangeCalendarValue,
  type RangeCalendarDemoProps,
} from "@comparison/data/rangecalendar-demo";
import {
  comparisonThemeChangeEvent,
  getComparisonResolvedThemeFromDocument,
  type ComparisonResolvedTheme,
} from "@comparison/data/theme";
import { providerShellStyle } from "../styled-shared.tsx";

function SolidSpectrumRangeCalendarDemo() {
  const [demoProps, setDemoProps] = createSignal<RangeCalendarDemoProps>(
    rangeCalendarDemoPropsFromWindow(),
  );
  const [value, setValue] = createSignal(rangeCalendarValueFromDemo(demoProps()));
  const [focusedValue, setFocusedValue] = createSignal(
    rangeCalendarDateFromString(demoProps().focusedValue || demoProps().startValue),
  );
  const [colorScheme, setColorScheme] = createSignal<ComparisonResolvedTheme>(
    getComparisonResolvedThemeFromDocument(),
  );

  onMount(() => {
    const handleControlsChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.component === "rangecalendar") {
        const nextProps = normalizeRangeCalendarDemoProps({
          ...demoProps(),
          ...(event.detail.props ?? {}),
        });
        setDemoProps(nextProps);
        setValue(() => rangeCalendarValueFromDemo(nextProps));
        setFocusedValue(() =>
          rangeCalendarDateFromString(nextProps.focusedValue || nextProps.startValue),
        );
      }
    };
    const handleThemeChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.resolvedTheme) {
        setColorScheme(event.detail.resolvedTheme as ComparisonResolvedTheme);
      }
    };
    window.addEventListener(rangeCalendarControlsEvent, handleControlsChange);
    window.addEventListener(comparisonThemeChangeEvent, handleThemeChange);
    setColorScheme(getComparisonResolvedThemeFromDocument());
    onCleanup(() => {
      window.removeEventListener(rangeCalendarControlsEvent, handleControlsChange);
      window.removeEventListener(comparisonThemeChangeEvent, handleThemeChange);
    });
  });

  const serializedProps = createMemo(() => serializeRangeCalendarDemoProps(demoProps()));

  return hc(
    SolidSpectrumProvider,
    {
      get colorScheme() {
        return colorScheme();
      },
      get locale() {
        return demoProps().locale || undefined;
      },
      background: "base",
      style: providerShellStyle,
    },
    [
      hc(
        "div",
        {
          get "data-comparison-color-scheme"() {
            return colorScheme();
          },
          get "data-comparison-locale"() {
            return demoProps().locale;
          },
          get "data-comparison-calendar-system"() {
            return demoProps().calendarSystem;
          },
          get "data-comparison-value"() {
            return serializeRangeCalendarValue(value());
          },
          get "data-comparison-focused-value"() {
            return focusedValue() ? String(focusedValue()) : "";
          },
          "data-comparison-control-root": "rangecalendar",
          get "data-comparison-control-props"() {
            return serializedProps();
          },
        },
        [
          hc(SolidSpectrumRangeCalendar, {
            class: "comparison-rangecalendar-root",
            "aria-label": "Trip dates",
            get value() {
              return value() ?? undefined;
            },
            onChange: (nextValue: ReturnType<typeof value>) => {
              setValue(() => nextValue);
            },
            get minValue() {
              return demoProps().constrainRange ? rangeCalendarMinValue : undefined;
            },
            get maxValue() {
              return demoProps().constrainRange ? rangeCalendarMaxValue : undefined;
            },
            get isDateUnavailable() {
              return demoProps().unavailableDates ? isRangeCalendarDateUnavailable : undefined;
            },
            get allowsNonContiguousRanges() {
              return demoProps().allowsNonContiguousRanges;
            },
            get isDisabled() {
              return demoProps().isDisabled;
            },
            get isReadOnly() {
              return demoProps().isReadOnly;
            },
            get isInvalid() {
              return demoProps().isInvalid;
            },
            get errorMessage() {
              return demoProps().errorMessage;
            },
            get firstDayOfWeek() {
              return demoProps().firstDayOfWeek || undefined;
            },
            get visibleMonths() {
              return rangeCalendarVisibleMonthsFromString(demoProps().visibleMonths);
            },
            get pageBehavior() {
              return demoProps().pageBehavior || undefined;
            },
            get selectionAlignment() {
              return demoProps().selectionAlignment || undefined;
            },
            get createCalendar() {
              return calendarCreateCalendarForDemo(demoProps().calendarSystem);
            },
            get UNSAFE_style() {
              const visibleMonths = rangeCalendarVisibleMonthsFromString(demoProps().visibleMonths);
              const resolvedVisibleMonths = visibleMonths ?? 1;
              return {
                "--cell-responsive-size": "32px",
                width: `${resolvedVisibleMonths * 224 + (resolvedVisibleMonths - 1) * 24}px`,
                maxWidth: "100%",
              };
            },
            get focusedValue() {
              return demoProps().focusedValue ? (focusedValue() ?? undefined) : undefined;
            },
            onFocusChange: (nextFocusedValue: ReturnType<typeof focusedValue>) => {
              setFocusedValue(() => nextFocusedValue);
            },
          }),
        ],
      ),
    ],
  );
}

export default () => h(SolidSpectrumRangeCalendarDemo, {});
