// apps/comparison/src/components/react/fixtures/styled/togglebutton.js
import { jsx } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import { ToggleButton as SpectrumToggleButton } from "@react-spectrum/s2";
import { buttonDemoLocaleFromWindow, comparisonControlsEvent } from "@comparison/data/button-demo";
import {
  normalizeToggleButtonDemoProps,
  serializeToggleButtonDemoProps,
  toggleButtonDemoPropsFromWindow,
} from "@comparison/data/button-family-demo";
import {
  renderReactSpectrumReference,
  staticColorBackdropProps,
  renderSingleButtonFamilyChildren,
} from "../styled-shared.js";

function ReactToggleButtonDemo() {
  const [demoProps, setDemoProps] = useState(toggleButtonDemoPropsFromWindow);
  const [selected, setSelected] = useState(demoProps.isSelected);
  const locale = buttonDemoLocaleFromWindow();
  useEffect(() => {
    const handleControlsChange = (event) => {
      if (event instanceof CustomEvent && event.detail?.component === "togglebutton") {
        const nextProps = normalizeToggleButtonDemoProps(event.detail.props ?? {});
        setDemoProps(nextProps);
        setSelected(nextProps.isSelected);
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    return () => window.removeEventListener(comparisonControlsEvent, handleControlsChange);
  }, []);

  return renderReactSpectrumReference(
    jsx("div", {
      ...staticColorBackdropProps(demoProps.staticColor),
      "data-comparison-selected": String(selected),
      children: jsx(SpectrumToggleButton, {
        "data-comparison-control-root": "togglebutton",
        "data-comparison-control-props": serializeToggleButtonDemoProps({
          ...demoProps,
          isSelected: selected,
        }),
        size: demoProps.size,
        staticColor: demoProps.staticColor,
        isQuiet: demoProps.isQuiet,
        isEmphasized: demoProps.isEmphasized,
        isDisabled: demoProps.isDisabled,
        isSelected: selected,
        onChange: setSelected,
        "aria-label": demoProps.iconPlacement === "only" ? demoProps.children : void 0,
        children: renderSingleButtonFamilyChildren(demoProps.children, demoProps.iconPlacement),
      }),
    }),
    undefined,
    locale,
  );
}

export default () => jsx(ReactToggleButtonDemo, {});

// apps/comparison/src/components/solid/fixtures/styled/togglebutton.tsx
import h from "@solidjs/h";
import { createMemo, createSignal, onSettled } from "solid-js";
import { hc } from "../../solid-h";
import { Provider as SolidSpectrumProvider } from "@proyecto-viviana/solid-spectrum/Provider";
import { ToggleButton as SolidSpectrumToggleButton } from "@proyecto-viviana/solid-spectrum/ToggleButton";
import { s2ToggleButtonText } from "../../../../../../../packages/solid-spectrum/src/button/s2-action-button-styles";
import { buttonDemoLocaleFromWindow, comparisonControlsEvent } from "@comparison/data/button-demo";
import {
  normalizeToggleButtonDemoProps,
  serializeToggleButtonDemoProps,
  toggleButtonDemoPropsFromWindow,
  type ToggleButtonDemoProps,
} from "@comparison/data/button-family-demo";
import {
  solidSingleButtonFamilyChildren,
  providerShellStyle,
  staticColorBackdropClass,
  staticColorBackdropValue,
} from "../styled-shared.tsx";

function SolidSpectrumToggleButtonDemo() {
  const [demoProps, setDemoProps] = createSignal<ToggleButtonDemoProps>(
    toggleButtonDemoPropsFromWindow(),
  );
  const [selected, setSelected] = createSignal(demoProps().isSelected);
  const locale = buttonDemoLocaleFromWindow();

  onSettled(() => {
    const handleControlsChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.component === "togglebutton") {
        const nextProps = normalizeToggleButtonDemoProps(event.detail.props ?? {});
        setDemoProps(nextProps);
        setSelected(nextProps.isSelected);
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    return () => window.removeEventListener(comparisonControlsEvent, handleControlsChange);
  });

  const renderedToggleButton = createMemo(() => {
    const props = demoProps();
    // Pass `isSelected` as the reactive `selected` accessor (hc unwraps a
    // zero-arg function prop into a reactive getter) rather than reading
    // `selected()` here. Reading it inside this memo would retrack it, so every
    // toggle would recompute the memo and rebuild the whole element — unmounting
    // the live <button> and dropping keyboard focus to <body>. Deferring the
    // read keeps the same instance and updates `isSelected` in place, matching
    // compiled JSX `isSelected={selected()}` and React's controlled reconcile.
    return hc(
      SolidSpectrumToggleButton,
      {
        "data-comparison-control-root": "togglebutton",
        get "data-comparison-control-props"() {
          return serializeToggleButtonDemoProps({ ...props, isSelected: selected() });
        },
        size: props.size,
        staticColor: props.staticColor,
        isQuiet: props.isQuiet,
        isEmphasized: props.isEmphasized,
        isDisabled: props.isDisabled,
        "aria-label": props.iconPlacement === "only" ? props.children : undefined,
        isSelected: selected,
        onChange: setSelected,
      },
      solidSingleButtonFamilyChildren(
        props.children,
        props.iconPlacement,
        () => s2ToggleButtonText,
      ),
    );
  });

  return hc(
    SolidSpectrumProvider,
    { colorScheme: "dark", locale, background: "base", style: providerShellStyle },
    [
      hc(
        "div",
        {
          get class() {
            return staticColorBackdropClass(demoProps().staticColor);
          },
          get "data-comparison-static-color"() {
            return staticColorBackdropValue(demoProps().staticColor);
          },
          get "data-comparison-selected"() {
            return String(selected());
          },
        },
        [renderedToggleButton],
      ),
    ],
  );
}

export default () => h(SolidSpectrumToggleButtonDemo, {});
